schema_version = "1.7.0"
modified = "2024-03-07T00:00:00Z"
published = "2024-03-07T00:00:00Z"
summary = "Gitlab -- Vulnerabilities"
details = """
Gitlab reports:

> Bypassing CODEOWNERS approval allowing to steal protected variables
>
> Guest with manage group access tokens can rotate and see group access token with owner permissions"""
affected = []
id = "FBSD-2024-0273"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-0199"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-1299"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2024/03/06/security-release-gitlab-16-9-2-released/"

[database_specific]
vid = "b2caae55-dc38-11ee-96dc-001b217b3468"
discovery = "2024-03-06T00:00:00Z"
