schema_version = "1.7.0"
modified = "2025-01-30T00:00:00Z"
published = "2025-01-30T00:00:00Z"
summary = "FreeBSD -- Unprivileged access to system files"
details = """
Problem Description:
====================

When etcupdate encounters conflicts while merging files, it
saves a version containing conflict markers in /var/db/etcupdate/conflicts.
This version does not preserve the mode of the input file, and is
world-readable. This applies to files that would normally have
restricted visibility, such as /etc/master.passwd.

Impact:
=======

An unprivileged local user may be able to read encrypted root
and user passwords from the temporary master.passwd file created
in /var/db/etcupdate/conflicts. This is possible only when conflicts
within the password file arise during an update, and the unprotected
file is deleted when conflicts are resolved."""
affected = []
id = "FBSD-2025-0242"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-0374"

[[references]]
type = "ADVISORY"
url = "https://www.freebsd.org/security/advisories/FreeBSD-SA-25:03.etcupdate.asc"

[database_specific]
vid = "fa9ae646-debc-11ef-87ba-002590c1f29c"
discovery = "2025-01-29T00:00:00Z"
