schema_version = "1.7.0"
modified = "2025-04-13T00:00:00Z"
published = "2025-04-13T00:00:00Z"
summary = "Mozilla -- null pointer dereference"
details = """
security@mozilla.org reports:

> A null pointer dereference may have inadvertently
> occurred in `pk12util`, and specifically in the
> `SEC\\_ASN1DecodeItem\\_Util` function, when handling malformed
> or improperly formatted input files."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-11706" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-11706" },
]
id = "FBSD-2025-0267"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "133.0" },
    { introduced = "0" },
]

[database_specific]
vid = "ba6361be-1887-11f0-a8ce-b42e991fc52e"
discovery = "2024-11-26T00:00:00Z"
