schema_version = "1.7.0"
modified = "2024-03-01T00:00:00Z"
published = "2024-03-01T00:00:00Z"
summary = "NodeJS -- Vulnerabilities"
details = """
Node.js reports:

> Code injection and privilege escalation through Linux capabilities- (High)
>
> http: Reading unprocessed HTTP request with unbounded chunk extension allows DoS attacks- (High)
>
> Path traversal by monkey-patching Buffer internals- (High)
>
> setuid() does not drop all privileges due to io\\_uring - (High)
>
> Node.js is vulnerable to the Marvin Attack (timing variant of the Bleichenbacher attack against PKCS#1 v1.5 padding) - (Medium)
>
> Multiple permission model bypasses due to improper path traversal sequence sanitization - (Medium)
>
> Improper handling of wildcards in --allow-fs-read and --allow-fs-write (Medium)
>
> Denial of Service by resource exhaustion in fetch() brotli decoding - (Medium)"""
id = "FBSD-2024-0277"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-21892"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-22019"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-21896"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-22017"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-46809"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-21891"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-21890"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-22025"

[[references]]
type = "WEB"
url = "https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#2024-02-14-version-20111-iron-lts-rafaelgss-prepared-by-marco-ippolito"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "node16"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "16.0.0" },
    { fixed = "16.20.3" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "node18"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "18.0.0" },
    { fixed = "18.19.1" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "node20"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "20.0.0" },
    { fixed = "20.11.1" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "node21"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "21.0.0" },
    { fixed = "21.6.2" },
]

[database_specific]
vid = "77a6f1c9-d7d2-11ee-bb12-001b217b3468"
discovery = "2024-02-14T00:00:00Z"
