schema_version = "1.7.0"
modified = "2024-09-05T00:00:00Z"
published = "2024-09-05T00:00:00Z"
summary = "qt5-webengine -- Multiple vulnerabilities"
details = """
> Backports for 6 security bugs in Chromium:
>
> * CVE-2024-5496: Use after free in Media Session
> * CVE-2024-5846: Use after free in PDFium
> * CVE-2024-6291: Use after free in Swiftshader
> * CVE-2024-6989: Use after free in Loader
> * CVE-2024-6996: Race in Frames
> * CVE-2024-7536: Use after free in WebAudio"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-5496" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-5846" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6291" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6989" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6996" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-7536" },
    { type = "WEB", url = "https://code.qt.io/cgit/qt/qtwebengine-chromium.git/log/?h=87-based" },
]
affected = []
id = "FBSD-2024-0118"

[database_specific]
vid = "66907dab-6bb2-11ef-b813-4ccc6adda413"
discovery = "2024-08-05T00:00:00Z"
