schema_version = "1.7.0"
modified = "2025-06-14T00:00:00Z"
published = "2025-06-14T00:00:00Z"
summary = "Yelp -- arbitrary file read"
details = """
secalert@redhat.com reports:

> A flaw was found in Yelp. The Gnome user help application allows
> the help document to execute arbitrary scripts. This vulnerability
> allows malicious users to input help documents, which may exfiltrate
> user files to an external environment."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-3155" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-3155" },
]
affected = []
id = "FBSD-2025-0087"

[database_specific]
vid = "0e200a73-289a-489e-b405-40b997911036"
discovery = "2025-04-03T00:00:00Z"
