schema_version = "1.7.0"
modified = "2025-07-29T00:00:00Z"
published = "2025-07-29T00:00:00Z"
summary = "p5-Crypt-CBC -- Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG)"
details = """
Lib-Crypt-CBC project reports:

> Crypt::CBC versions between 1.21 and 3.05 for Perl may use the rand() function as the default
> source of entropy, which is not cryptographically secure, for cryptographic functions.
> This issue affects operating systems where \"/dev/urandom'\" is unavailable.
> In that case, Crypt::CBC will fallback to use the insecure rand() function."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-2814" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-2814" },
]
affected = []
id = "FBSD-2025-0013"

[database_specific]
vid = "cd7f969e-6cb4-11f0-97c4-40b034429ecf"
discovery = "2025-04-12T00:00:00Z"
