schema_version = "1.7.0"
modified = "2024-10-15T00:00:00Z"
published = "2024-10-15T00:00:00Z"
summary = "element-web -- Potential exposure of access token via authenticated media"
details = """
Element team reports:

> Element Web versions 1.11.70 through 1.11.80 contain a
> vulnerability which can, under specially crafted conditions,
> lead to the access token becoming exposed to third
> parties. At least one vector has been identified internally,
> involving malicious widgets, but other vectors may
> exist. Users are strongly advised to upgrade to version
> 1.11.81 to remediate the issue."""
affected = []
id = "FBSD-2024-0076"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-47779"

[[references]]
type = "WEB"
url = "https://github.com/element-hq/element-web/security/advisories/GHSA-3jm3-x98c-r34x"

[database_specific]
vid = "851ce3e4-8b03-11ef-84e9-901b0e9408dc"
discovery = "2024-10-15T00:00:00Z"
