schema_version = "1.7.0"
modified = "2024-06-22T00:00:00Z"
published = "2024-06-22T00:00:00Z"
summary = "traefik -- Azure Identity Libraries Elevation of Privilege Vulnerability"
details = """
The traefik authors report:

> There is a vulnerability in Azure Identity Libraries and
> Microsoft Authentication Library Elevation of Privilege Vulnerability."""
affected = []
id = "FBSD-2024-0181"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-35255"

[[references]]
type = "WEB"
url = "https://github.com/traefik/traefik/security/advisories/GHSA-rvj4-q8q5-8grf"

[database_specific]
vid = "82830965-3073-11ef-a17d-5404a68ad561"
discovery = "2024-06-11T00:00:00Z"
