schema_version = "1.7.0"
modified = "2025-04-09T00:00:00Z"
published = "2025-04-09T00:00:00Z"
summary = "expat: improper restriction of xml entity expansion depth"
details = """
secalert@redhat.com reports:

> A stack overflow vulnerability exists in the libexpat library due
> to the way it handles recursive entity expansion in XML documents.
> When parsing an XML document with deeply nested entity references,
> libexpat can be forced to recurse indefinitely, exhausting the stack
> space and causing a crash. This issue could lead to denial of
> service (DoS) or, in some cases, exploitable memory corruption,
> depending on the environment and library usage."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-8176" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-8176" },
]
affected = []
id = "FBSD-2025-0160"

[database_specific]
vid = "8f71ad3b-14f5-11f0-87ba-002590c1f29c"
discovery = "2025-03-14T00:00:00Z"
