schema_version = "1.7.0"
modified = "2024-08-25T00:00:00Z"
published = "2024-08-25T00:00:00Z"
summary = "Gitlab -- vulnerabilities"
details = """
Gitlab reports:

> The GitLab Web Interface Does Not Guarantee Information Integrity When Downloading Source Code from Releases
>
> Denial of Service by importing maliciously crafted GitHub repository
>
> Prompt injection in \"Resolve Vulnerabilty\" results in arbitrary command execution in victim's pipeline
>
> An unauthorized user can perform certain actions through GraphQL after a group owner enables IP restrictions"""
id = "FBSD-2024-0132"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-6502"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8041"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-7110"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-3127"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2024/08/21/patch-release-gitlab-17-3-1-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.3.0" },
    { fixed = "17.3.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.2.0" },
    { fixed = "17.2.4" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "8.2.0" },
    { fixed = "17.1.6" },
]

[database_specific]
vid = "49ef501c-62b6-11ef-bba5-2cf05da270f3"
discovery = "2024-08-21T00:00:00Z"
