schema_version = "1.7.0"
modified = "2025-03-22T00:00:00Z"
published = "2025-03-22T00:00:00Z"
summary = "www/varnish7 -- client-side desync vulnerability"
details = """
The Varnish Development Team reports:

> A client-side desync vulnerability can be triggered in Varnish Cache
> and Varnish Enterprise. This vulnerability can be triggered under
> specific circumstances involving malformed HTTP/1 requests."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-30346" },
    { type = "WEB", url = "https://varnish-cache.org/security/VSV00015.html#vsv00015" },
]
affected = []
id = "FBSD-2025-0194"

[database_specific]
vid = "26f6733d-06a9-11f0-ba0b-641c67a117d8"
discovery = "2024-12-17T00:00:00Z"
