schema_version = "1.7.0"
modified = "2025-03-30T00:00:00Z"
published = "2025-03-30T00:00:00Z"
summary = "mozilla -- multiple vulnerabilities"
details = """
security@mozilla.org reports:

> An inconsistent comparator in xslt/txNodeSorter could have resulted
> in potentially exploitable out-of-bounds access. Only affected
> version 122 and later. This vulnerability affects Firefox <
> 136, Firefox ESR < 128.8, Thunderbird < 136, and Thunderbird
> < 128.8.
>
> Under certain circumstances, a user opt-in setting that Focus should
> require authentication before use could have been be bypassed
> (distinct from CVE-2025-0245). This vulnerability affects Firefox
> < 136.
>
> When String.toUpperCase() caused a string to get longer it was
> possible for uninitialized memory to be incorporated into the result
> string This vulnerability affects Firefox < 136 and Thunderbird
> < 136.
>
> Websites redirecting to a non-HTTP scheme URL could allow a website
> address to be spoofed for a malicious page This vulnerability affects
> Firefox for iOS < 136."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-1932" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-1932" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-1941" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-1941" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-1942" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-1942" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-27424" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-27424" },
]
id = "FBSD-2025-0187"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.8,1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "136.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.8" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "librewolf"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "136.0" },
    { introduced = "0" },
]

[database_specific]
vid = "1a67144d-0d86-11f0-8542-b42e991fc52e"
discovery = "2025-03-04T00:00:00Z"
