schema_version = "1.7.0"
modified = "2024-09-05T00:00:00Z"
published = "2024-09-03T00:00:00Z"
summary = "OpenSSL -- Multiple vulnerabilities"
details = """
The OpenSSL project reports:

> Possible denial of service in X.509 name checks [Moderate severity]
> Applications performing certificate name checks (e.g., TLS clients
> checking server certificates) may attempt to read an invalid
> memory address resulting in abnormal termination of the application
> process.
>
> SSL\\_select\\_next\\_proto buffer overread [Low severity]
> Calling the OpenSSL API function SSL\\_select\\_next\\_proto with an empty
> supported client protocols buffer may cause a crash or memory
> contents to be sent to the peer."""
id = "FBSD-2024-0125"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-5535"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-6119"

[[references]]
type = "WEB"
url = "https://openssl-library.org/news/secadv/20240627.txt"

[[references]]
type = "WEB"
url = "https://openssl-library.org/news/secadv/20240903.txt"

[[references]]
type = "ADVISORY"
url = "https://www.freebsd.org/security/advisories/FreeBSD-SA-24:13.openssl.asc"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "openssl31"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.1.7" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "openssl32"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.2.3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "openssl33"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.3.2" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "openssl-quictls"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.0.15" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "openssl31-quictls"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.1.7" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "FreeBSD"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "14.1" },
    { fixed = "14.1_4" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "14.0" },
    { fixed = "14.0_10" },
]

[database_specific]
vid = "21f505f4-6a1c-11ef-b611-84a93843eb75"
discovery = "2024-09-03T00:00:00Z"
