schema_version = "1.7.0"
modified = "2025-06-06T00:00:00Z"
published = "2025-06-06T00:00:00Z"
summary = "ModSecurity -- possible DoS vulnerability"
details = """
security-advisories@github.com reports:

> ModSecurity is an open source, cross platform web
> application firewall (WAF) engine for Apache, IIS
> and Nginx. Versions prior to 2.9.10 contain a denial of
> service vulnerability similar to
> GHSA-859r-vvv8-rm8r/CVE-2025-47947. The `sanitiseArg`
> (and `sanitizeArg` - this is the same action but an
> alias) is vulnerable to adding an excessive number
> of arguments, thereby leading to denial of service.
> Version 2.9.10 fixes the issue. As a workaround, avoid
> using rules that contain the `sanitiseArg` (or
> `sanitizeArg`) action."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-48866" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-48866" },
]
affected = []
id = "FBSD-2025-0090"

[database_specific]
vid = "fa1d42c8-42fe-11f0-a9fa-b42e991fc52e"
discovery = "2025-06-02T00:00:00Z"
