schema_version = "1.7.0"
modified = "2025-06-19T00:00:00Z"
published = "2025-06-19T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 3 security fixes:
>
> * [420697404] High CVE-2025-6191: Integer overflow in V8. Reported by Shaheen Fazim on 2025-05-27
> * [421471016] High CVE-2025-6192: Use after free in Profiler. Reported by Chaoyuan Peng (@ret2happy) on 2025-05-31"""
id = "FBSD-2025-0077"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-6191"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-6192"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2025/06/stable-channel-update-for-desktop_17.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "137.0.7151.119" },
    { introduced = "0" },
]

[database_specific]
vid = "333b4663-4cde-11f0-8cb5-a8a1599412c6"
discovery = "2025-06-17T00:00:00Z"
