schema_version = "1.7.0"
modified = "2024-12-06T00:00:00Z"
published = "2024-12-06T00:00:00Z"
summary = "gstreamer1-plugins-gdkpixbuf -- NULL-pointer dereference"
details = """
The GStreamer Security Center reports:

> A NULL-pointer dereference in the gdk-pixbuf decoder that can
> cause crashes for certain input files."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-47613" },
    { type = "WEB", url = "https://gstreamer.freedesktop.org/security/sa-2024-0025.html" },
]
affected = []
id = "FBSD-2024-0023"

[database_specific]
vid = "772d8625-b3e8-11ef-b680-4ccc6adda413"
discovery = "2024-12-03T00:00:00Z"
