schema_version = "1.7.0"
modified = "2024-10-26T00:00:00Z"
published = "2024-10-26T00:00:00Z"
summary = "tnef -- Invalid read and write operations, controlled by an attacker"
details = """
cve@mitre.org reports:

> CVE-2017-6307: An issue was discovered in tnef before
> 1.4.13. Two OOB Writes have been identified in
> src/mapi\\_attr.c:mapi\\_attr\\_read(). These might lead to
> invalid read and write operations, controlled by an
> attacker.

> CVE-2017-6308: An issue was discovered in tnef before
> 1.4.13. Several Integer Overflows, which can lead to Heap
> Overflows, have been identified in the functions that wrap
> memory allocation.

> CVE-2017-6309: An issue was discovered in tnef before
> 1.4.13. Two type confusions have been identified in the
> parse\\_file() function. These might lead to invalid read and
> write operations, controlled by an attacker.

> CVE-2017-6310: An issue was discovered in tnef before
> 1.4.13. Four type confusions have been identified in the
> file\\_add\\_mapi\\_attrs() function. These might lead to invalid
> read and write operations, controlled by an attacker."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2017-6307" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2017-6307" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2017-6308" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2017-6308" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2017-6309" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2017-6309" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2017-6310" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2017-6310" },
]
affected = []
id = "FBSD-2024-0056"

[database_specific]
vid = "70cf37c8-939b-11ef-87ad-a8a15998b5cb"
discovery = "2017-02-24T00:00:00Z"
