schema_version = "1.7.0"
modified = "2025-05-08T00:00:00Z"
published = "2025-05-08T00:00:00Z"
summary = "PostgreSQL -- PostgreSQL GB18030 encoding validation can read one byte past end of allocation for text that fails validation"
details = """
PostgreSQL project reports:

> A buffer over-read in PostgreSQL GB18030 encoding
> validation allows a database input provider to achieve
> temporary denial of service on platforms where a 1-byte
> over-read can elicit process termination. This affects
> the database server and also libpq. Versions before
> PostgreSQL 17.5, 16.9, 15.13, 14.18, and 13.21 are
> affected."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-4207" },
    { type = "WEB", url = "https://www.postgresql.org/support/security/CVE-2025-4207/" },
]
id = "FBSD-2025-0138"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql16-client"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "16.9" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql15-client"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "15.13" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql14-client"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "14.18" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql13-client"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "13.21" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql17-server"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "17.5" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql16-server"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "16.9" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql15-server"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "15.13" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql14-server"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "14.18" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql13-server"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "13.21" },
    { introduced = "0" },
]

[database_specific]
vid = "78b8e808-2c45-11f0-9a65-6cc21735f730"
discovery = "2025-05-08T00:00:00Z"
