schema_version = "1.7.0"
modified = "2025-01-30T00:00:00Z"
published = "2025-01-30T00:00:00Z"
summary = "dendrite -- Server-side request forgery vulnerability"
details = """
Dendrite team reports:

> This is a security release, gomatrixserverlib was vulnerable to server-side request forgery, serving content from a private network it can access, under certain conditions."""
affected = []
id = "FBSD-2025-0240"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-52594"

[[references]]
type = "WEB"
url = "https://github.com/matrix-org/gomatrixserverlib/security/advisories/GHSA-4ff6-858j-r822"

[database_specific]
vid = "cd2ace09-df23-11ef-a205-901b0e9408dc"
discovery = "2025-01-16T00:00:00Z"
