schema_version = "1.7.0"
modified = "2024-08-18T00:00:00Z"
published = "2024-08-18T00:00:00Z"
summary = "electron{29,30} -- multiple vulnerabilities"
details = """
Electron developers report:

> This update fixes the following vulnerabilities:
>
> * Security: backported fix for CVE-2024-6776.
> * Security: backported fix for CVE-2024-6778.
> * Security: backported fix for CVE-2024-6777.
> * Security: backported fix for CVE-2024-6773.
> * Security: backported fix for CVE-2024-6774.
> * Security: backported fix for CVE-2024-6772.
> * Security: backported fix for CVE-2024-6775.
> * Security: backported fix for CVE-2024-6779.
> * Security: backported fix for CVE-2024-6989.
> * Security: backported fix for CVE-2024-6991."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6776" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-7hjm-9cg2-rcg6" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6778" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-9m98-937v-r97x" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6777" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-w2v8-c457-cjvf" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6773" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-7gj8-545r-5295" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6774" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-cgm7-mqr6-f7vg" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6772" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-cc8c-62x7-qwjr" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6775" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-mxwm-jm3p-mh5m" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6779" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-v4v9-v4wf-9c86" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6989" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-32j6-235r-7fmm" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6991" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-3v8g-fm64-g4mc" },
]
id = "FBSD-2024-0141"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "electron30"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "30.4.0" },
    { introduced = "0" },
]

[database_specific]
vid = "ac025402-4cbc-4177-bd99-c20c03a07f23"
discovery = "2024-08-16T00:00:00Z"
