schema_version = "1.7.0"
modified = "2025-08-01T00:00:00Z"
published = "2025-07-31T00:00:00Z"
summary = "SQLite -- integer overflow in key info allocation"
details = """
cve-coordination@google.com reports:

> An integer overflow in the sqlite3KeyInfoFromExprList function in
> SQLite versions 3.39.2 through 3.41.1 allows an attacker with the
> ability to execute arbitrary SQL statements to cause a denial of
> service or disclose sensitive information from process memory via
> a crafted SELECT statement with a large number of expressions in
> the ORDER BY clause."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-7458" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-7458" },
]
affected = []
id = "FBSD-2025-0012"

[database_specific]
vid = "f51077bd-6dd7-11f0-9d62-b42e991fc52e"
discovery = "2025-07-29T00:00:00Z"
