schema_version = "1.7.0"
modified = "2025-07-24T00:00:00Z"
published = "2025-07-24T00:00:00Z"
summary = "Mozilla -- Insufficient input escaping"
details = """
security@mozilla.org reports:

> Insufficient escaping in the Copy as cURL feature could
> potentially be used to trick a user into executing
> unexpected code."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-8030" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-8030" },
]
id = "FBSD-2025-0027"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "140.1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.13" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "141.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "140.1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.13" },
    { introduced = "0" },
]

[database_specific]
vid = "44b3048b-685e-11f0-a12d-b42e991fc52e"
discovery = "2025-07-22T00:00:00Z"
