schema_version = "1.7.0"
modified = "2024-03-04T00:00:00Z"
published = "2024-03-04T00:00:00Z"
summary = "Django -- multiple vulnerabilities"
details = """
Django reports:

> CVE-2024-27351: Potential regular expression denial-of-service in
> django.utils.text.Truncator.words()."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-27351" },
    { type = "WEB", url = "https://www.djangoproject.com/weblog/2024/mar/04/security-releases/" },
]
id = "FBSD-2024-0276"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py310-django32"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.2.25" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py311-django32"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.2.25" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py39-django42"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "4.2.11" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py310-django42"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "4.2.11" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py311-django42"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "4.2.11" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py310-django50"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "5.0.3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py311-django50"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "5.0.3" },
    { introduced = "0" },
]

[database_specific]
vid = "0ef3398e-da21-11ee-b23a-080027a5b8e9"
discovery = "2024-02-25T00:00:00Z"
