schema_version = "1.7.0"
modified = "2024-08-10T00:00:00Z"
published = "2024-08-10T00:00:00Z"
summary = "Roundcube -- Multiple vulnerabilities"
details = """
The Roundcube project reports:

> XSS vulnerability in post-processing of sanitized HTML content [CVE-2024-42009]
>
> XSS vulnerability in serving of attachments other than HTML or SVG [CVE-2024-42008]
>
> information leak (access to remote content) via insufficient CSS filtering [CVE-2024-42010]"""
affected = []
id = "FBSD-2024-0148"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-42009"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-42008"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-42010"

[[references]]
type = "WEB"
url = "https://roundcube.net/news/2024/08/04/security-updates-1.6.8-and-1.5.8"

[database_specific]
vid = "5776cc4f-5717-11ef-b611-84a93843eb75"
discovery = "2024-08-04T00:00:00Z"
