schema_version = "1.7.0"
modified = "2024-08-10T00:00:00Z"
published = "2024-08-10T00:00:00Z"
summary = "AMD CPUs -- Guest Memory Vulnerabilities"
details = """
AMD reports:

> Researchers from IOActive have reported that it may be possible for
> an attacker with ring 0 access to modify the configuration of System
> Management Mode (SMM) even when SMM Lock is enabled. Improper
> validation in a model specific register (MSR) could allow a malicious
> program with ring0 access to modify SMM configuration while SMI lock
> is enabled, potentially leading to arbitrary code execution."""
affected = []
id = "FBSD-2024-0147"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-31315"

[[references]]
type = "WEB"
url = "https://www.amd.com/en/resources/product-security/bulletin/amd-sb-7014.html"

[database_specific]
vid = "7d631146-5769-11ef-b618-1c697a616631"
discovery = "2024-08-09T00:00:00Z"
