schema_version = "1.7.0"
modified = "2024-07-03T00:00:00Z"
published = "2024-07-03T00:00:00Z"
summary = "go -- net/http: denial of service due to improper 100-continue handling"
details = """
The Go project reports:

> net/http: denial of service due to improper 100-continue handling
>
> The net/http HTTP/1.1 client mishandled the case where a
> server responds to a request with an \"Expect: 100-continue\"
> header with a non-informational (200 or higher) status. This
> mishandling could leave a client connection in an invalid
> state, where the next request sent on the connection will
> fail.
>
> An attacker sending a request to a
> net/http/httputil.ReverseProxy proxy can exploit this
> mishandling to cause a denial of service by sending \"Expect:
> 100-continue\" requests which elicit a non-informational
> response from the backend. Each such request leaves the
> proxy with an invalid connection, and causes one subsequent
> request using that connection to fail."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-24791" },
    { type = "WEB", url = "https://go.dev/issue/67555" },
]
id = "FBSD-2024-0172"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "go121"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.21.12" },
    { introduced = "0" },
]

[database_specific]
vid = "b0374722-3912-11ef-a77e-901b0e9408dc"
discovery = "2024-07-02T00:00:00Z"
