schema_version = "1.7.0"
modified = "2025-04-22T00:00:00Z"
published = "2025-04-22T00:00:00Z"
summary = "powerdns-recursor -- denial of service"
details = """
PowerDNS Team reports:

> PowerDNS Security Advisory 2025-01: A crafted zone can
> lead to an illegal memory access in the Recursor"""
affected = []
id = "FBSD-2025-0143"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-30195"

[[references]]
type = "WEB"
url = "https://docs.powerdns.com/recursor/security-advisories/powerdns-advisory-2025-01.html"

[database_specific]
vid = "d70d5e0a-1f5e-11f0-9c67-6805ca2fa271"
discovery = "2025-04-07T00:00:00Z"
