schema_version = "1.7.0"
modified = "2024-12-17T00:00:00Z"
published = "2024-12-17T00:00:00Z"
summary = "gitea -- multiple vulnerabilities"
details = """
Problem Description:
====================

* Fix delete branch perm checking
* Upgrade crypto library"""
references = [
    { type = "WEB", url = "https://github.com/go-gitea/gitea/pull/32791" },
    { type = "WEB", url = "https://github.com/go-gitea/gitea/pull/32654" },
]
affected = []
id = "FBSD-2024-0007"

[database_specific]
vid = "453cd84e-bca4-11ef-8926-9b4f2d14eb53"
discovery = "2024-11-27T00:00:00Z"
