schema_version = "1.7.0"
modified = "2025-04-03T00:00:00Z"
published = "2025-04-03T00:00:00Z"
summary = "MongoDB -- Malformed wire protocol messages may cause mongos to crash"
details = """
cna@mongodb.com reports:

> Specifically crafted MongoDB wire protocol messages can cause mongos
> to crash during command validation. This can occur without using
> an authenticated connection. This issue affects MongoDB v5.0
> versions prior to 5.0.31, MongoDB v6.0 versions prior to6.0.20 and
> MongoDB v7.0 versions prior to 7.0.16"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-3083" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-3083" },
]
id = "FBSD-2025-0183"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "mongodb60"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "6.0.20" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "mongodb70"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "7.0.16" },
    { introduced = "0" },
]

[database_specific]
vid = "32f5e57f-107f-11f0-8195-b42e991fc52e"
discovery = "2025-04-01T00:00:00Z"
