schema_version = "1.7.0"
modified = "2025-07-07T00:00:00Z"
published = "2025-07-07T00:00:00Z"
summary = "redis,valkey -- DoS Vulnerability due to bad connection error handling"
details = """
@julienperriercornet reports:

> An unauthenticated connection can cause repeated IP
> protocol errors, leading to client starvation and,
> ultimately, a denial of service."""
id = "FBSD-2025-0052"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-48367"

[[references]]
type = "WEB"
url = "https://github.com/redis/redis/security/advisories/GHSA-4q32-c38c-pwgq"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "redis74"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "7.4.0" },
    { fixed = "7.4.5" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "redis72"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "7.2.0" },
    { fixed = "7.2.10" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "redis62"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "6.2.0" },
    { fixed = "6.2.19" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "valkey"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "8.1.3" },
    { introduced = "0" },
]

[database_specific]
vid = "7b3e7f71-5b30-11f0-b507-000c295725e4"
discovery = "2025-07-06T00:00:00Z"
