schema_version = "1.7.0"
modified = "2025-05-13T00:00:00Z"
published = "2025-05-13T00:00:00Z"
summary = "libxslt -- multiple vulnerabilities"
details = """
[CVE-2024-55549] Fix UAF related to excluded namespaces
=======================================================

> xsltGetInheritedNsList in libxslt before 1.1.43 has a use-after-free issue related to exclusion of result prefixes.

[CVE-2025-24855] Fix use-after-free of XPath context node
=========================================================

> numbers.c in libxslt before 1.1.43 has a use-after-free because
> , in nested XPath evaluations, an XPath context node can be
> modified but never restored. This is related to
> xsltNumberFormatGetValue, xsltEvalXPathPredicate,
> xsltEvalXPathStringNs, and xsltComputeSortResultInternal."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-55549" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-24855" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-55549" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-24855" },
]
affected = []
id = "FBSD-2025-0129"

[database_specific]
vid = "a96cd659-303e-11f0-94b5-54ee755069b5"
discovery = "2025-03-13T00:00:00Z"
