schema_version = "1.7.0"
modified = "2025-07-24T00:00:00Z"
published = "2025-07-24T00:00:00Z"
summary = "Mozilla -- Memory safety bugs"
details = """
security@mozilla.org reports:

> Memory safety bugs present in Firefox ESR 140.0,
> Thunderbird ESR 140.0, Firefox 140 and Thunderbird 140.
> Some of these bugs showed evidence of memory corruption and
> we presume that with enough effort some of these could have
> been exploited to run arbitrary code."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-8040" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-8040" },
]
id = "FBSD-2025-0017"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "140.1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "141.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "140.1" },
    { introduced = "0" },
]

[database_specific]
vid = "62f1a68f-685e-11f0-a12d-b42e991fc52e"
discovery = "2025-07-22T00:00:00Z"
