schema_version = "1.7.0"
modified = "2025-07-22T00:00:00Z"
published = "2025-07-22T00:00:00Z"
summary = "7-Zip -- Multi-byte write heap buffer overflow in NCompress::NRar5::CDecoder"
details = """
security-advisories@github.com reports:

> 7-Zip is a file archiver with a high compression ratio. Zeroes
> written outside heap buffer in RAR5 handler may lead to memory
> corruption and denial of service in versions of 7-Zip prior to
> 25.0.0. Version 25.0.0 contains a fix for the issue."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-53816" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-53816" },
]
affected = []
id = "FBSD-2025-0035"

[database_specific]
vid = "80411ba2-6729-11f0-a5cb-8c164580114f"
discovery = "2025-07-17T00:00:00Z"
