schema_version = "1.7.0"
modified = "2024-06-15T00:00:00Z"
published = "2024-06-15T00:00:00Z"
summary = "traefik -- Unexpected behavior with IPv4-mapped IPv6 addresses"
details = """
The traefik authors report:

> There is a vulnerability in Go managing various Is methods
> (IsPrivate, IsLoopback, etc) for IPv4-mapped IPv6 addresses.
> They didn't work as expected returning false for addresses
> which would return true in their traditional IPv4 forms."""
affected = []
id = "FBSD-2024-0188"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-24790"

[[references]]
type = "WEB"
url = "https://github.com/traefik/traefik/security/advisories/GHSA-7jmw-8259-q9jx"

[database_specific]
vid = "219aaa1e-2aff-11ef-ab37-5404a68ad561"
discovery = "2024-06-05T00:00:00Z"
