schema_version = "1.7.0"
modified = "2025-08-01T00:00:00Z"
published = "2024-09-29T00:00:00Z"
summary = "sqlite -- use-after-free bug in jsonparseaddnodearray"
details = """
secalert@redhat.com reports:

> A heap use-after-free issue has been identified in SQLite in the
> jsonParseAddNodeArray() function in sqlite3.c. This flaw allows a
> local attacker to leverage a victim to pass specially crafted
> malicious input to the application, potentially causing a crash and
> leading to a denial of service."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-0232" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-0232" },
]
id = "FBSD-2024-0092"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "linux-rl9-sqlite"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "3.43.0,1" },
    { fixed = "3.43.2,1" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "linux-c7-sqlite"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "3.43.0,1" },
    { fixed = "3.43.2,1" },
]

[database_specific]
vid = "42ec2207-7e85-11ef-89a4-b42e991fc52e"
discovery = "2024-01-16T00:00:00Z"
