schema_version = "1.7.0"
modified = "2024-07-13T00:00:00Z"
published = "2024-07-13T00:00:00Z"
summary = "electron29 -- multiple vulnerabilities"
details = """
Electron developers report:

> This update fixes the following vulnerabilities:
>
> * Security: backported fix for CVE-2024-6291.
> * Security: backported fix for CVE-2024-6293.
> * Security: backported fix for CVE-2024-6290.
> * Security: backported fix for CVE-2024-6292."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6291" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-rpvg-h6p6-42qj" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6293" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-9f8f-453p-rg87" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6290" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-r5mh-qgc2-26p2" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-6292" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-m848-8f5r-6j4g" },
]
affected = []
id = "FBSD-2024-0166"

[database_specific]
vid = "55d4a92f-c75f-43e8-ab1f-4a0efc9795c4"
discovery = "2024-07-11T00:00:00Z"
