schema_version = "1.7.0"
modified = "2025-07-24T00:00:00Z"
published = "2025-07-24T00:00:00Z"
summary = "Mozilla -- IonMonkey-JIT bad stack write"
details = """
security@mozilla.org reports:

> On 64-bit platforms IonMonkey-JIT only wrote 32 bits of
> the 64-bit return value space on the stack. Baseline-JIT,
> however, read the entire 64 bits."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-8027" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-8027" },
]
id = "FBSD-2025-0030"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "140.1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.13" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "115.26" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "141.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "140.1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.13" },
    { introduced = "0" },
]

[database_specific]
vid = "3c234220-685e-11f0-a12d-b42e991fc52e"
discovery = "2025-07-22T00:00:00Z"
