schema_version = "1.7.0"
modified = "2025-04-04T00:00:00Z"
published = "2025-04-04T00:00:00Z"
summary = "Mozilla -- privilege escalation attack"
details = """
security@mozilla.org reports:

> The WebChannel API, which is used to transport various
> information across processes, did not check the sending
> principal but rather accepted the principal being sent.
> This could have led to privilege escalation attacks."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0237" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-0237" },
]
id = "FBSD-2025-0176"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "librewolf"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "134.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.6.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.6" },
    { introduced = "0" },
]

[database_specific]
vid = "ea51e89a-116c-11f0-8b2c-b42e991fc52e"
discovery = "2025-01-07T00:00:00Z"
