schema_version = "1.7.0"
modified = "2024-08-29T00:00:00Z"
published = "2024-08-29T00:00:00Z"
summary = "Configobj -- Regular Expression Denial of Service attack"
details = """
report@snyk.io reports:

> All versions of the package configobj are vulnerable to Regular
> Expression Denial of Service (ReDoS) via the validate function,
> using (.+?)\\((.\\*)\\).\\*\\*Note:\\*\\* This is only exploitable in the case
> of a developer putting the offending value in a server side
> configuration file."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2023-26112" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2023-26112" },
]
id = "FBSD-2024-0131"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py39-configobj"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { last_affected = "5.0.8" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py310-configobj"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { last_affected = "5.0.8" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py311-configobj"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { last_affected = "5.0.8" },
]

[database_specific]
vid = "46419e8c-65d9-11ef-ac06-b0416f0c4c67"
discovery = "2023-04-03T00:00:00Z"
