schema_version = "1.7.0"
modified = "2024-12-24T00:00:00Z"
published = "2024-12-24T00:00:00Z"
summary = "kanboard -- Insufficient session invalidation"
details = """
security-advisories@github.com reports:

> Kanboard is project management software that focuses on the Kanban
> methodology. In affected versions sessions are still usable even
> though their lifetime has exceeded. Kanboard implements a cutom
> session handler (`app/Core/Session/SessionHandler.php`), to store
> the session data in a database. Therefore, when a `session\\_id` is
> given, kanboard queries the data from the `sessions` sql table. At
> this point, it does not correctly verify, if a given `session\\_id`
> has already exceeded its lifetime (`expires\\_at`). Thus, a session
> which's lifetime is already `> time()`, is still queried
> from the database and hence a valid login. The implemented
> \\*\\*SessionHandlerInterface::gc\\*\\* function, that does remove invalid
> sessions, is called only \\*\\*with a certain probability\\*\\* (\\_Cleans
> up expired sessions. Called by `session\\_start()`, based on
> `session.gc\\_divisor`, `session.gc\\_probability` and `session.gc\\_maxlifetime`
> settings\\_) accordingly to the php documentation. In the official
> Kanboard docker image these values default to: session.gc\\_probability=1,
> session.gc\\_divisor=1000. Thus, an expired session is only terminated
> with probability 1/1000. There are no known workarounds for
> this vulnerability."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-55603" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-55603" },
]
affected = []
id = "FBSD-2024-0002"

[database_specific]
vid = "94b2d58a-c1e9-11ef-aa3f-dcfe074bd614"
discovery = "2024-12-19T00:00:00Z"
