schema_version = "1.7.0"
modified = "2024-01-26T00:00:00Z"
published = "2024-01-26T00:00:00Z"
summary = "Gitlab -- vulnerabilities"
details = """
Gitlab reports:

> Arbitrary file write while creating workspace
>
> ReDoS in Cargo.toml blob viewer
>
> Arbitrary API PUT requests via HTML injection in user's name
>
> Disclosure of the public email in Tags RSS Feed
>
> Non-Member can update MR Assignees of owned MRs"""
affected = []
id = "FBSD-2024-0315"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-0402"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-6159"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-5933"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-5612"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-0456"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2024/01/25/critical-security-release-gitlab-16-8-1-released/"

[database_specific]
vid = "61fe903b-bc2e-11ee-b06e-001b217b3468"
discovery = "2024-01-25T00:00:00Z"
