schema_version = "1.7.0"
modified = "2025-06-17T00:00:00Z"
published = "2025-06-17T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 2 security fixes:
>
> * [$8000][420150619] High CVE-2025-5958: Use after free in Media. Reported by Huang Xilin of Ant Group Light-Year Security Lab on 2025-05-25
> * [NA][422313191] High CVE-2025-5959: Type Confusion in V8. Reported by Seunghyun Lee as part of TyphoonPWN 2025 on 2025-06-04"""
id = "FBSD-2025-0082"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-5958"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-5959"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2025/06/stable-channel-update-for-desktop_10.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "137.0.7151.103" },
    { introduced = "0" },
]

[database_specific]
vid = "e3d6d485-c93c-4ada-90b3-09f1c454fb8a"
discovery = "2025-06-10T00:00:00Z"
