schema_version = "1.7.0"
modified = "2024-04-16T00:00:00Z"
published = "2024-04-16T00:00:00Z"
summary = "php -- Multiple vulnerabilities"
details = """
This update includes 3 security fixes:

> * High CVE-2024-1874: Command injection via array-ish $command parameter of proc\\_open even if bypass\\_shell option enabled on Windows
> * High CVE-2024-1874: Command injection via array-ish $command parameter of proc\\_open even if bypass\\_shell option enabled on Windows
> * Medium CVE-2024-2756: \\_\\_Host-/\\_\\_Secure- cookie bypass due to partial CVE-2022-31629 fix
> * High CVE-2024-2757: mb\\_encode\\_mimeheader runs endlessly for some inputs"""
id = "FBSD-2024-0240"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-1874"

[[references]]
type = "WEB"
url = "https://github.com/php/php-src/security/advisories/GHSA-pc52-254m-w9w7"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2756"

[[references]]
type = "WEB"
url = "https://github.com/php/php-src/security/advisories/GHSA-wpj3-hf5j-x4v4"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-3096"

[[references]]
type = "WEB"
url = "https://github.com/php/php-src/security/advisories/GHSA-h746-cjrr-wfmr"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2757"

[[references]]
type = "WEB"
url = "https://github.com/php/php-src/security/advisories/GHSA-fjp9-9hwx-59fq"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "php82"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "8.2.18" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "php83"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "8.3.6" },
    { introduced = "0" },
]

[database_specific]
vid = "6d82c5e9-fc24-11ee-a689-04421a1baf97"
discovery = "2024-04-11T00:00:00Z"
