schema_version = "1.7.0"
modified = "2024-11-13T00:00:00Z"
published = "2024-11-13T00:00:00Z"
summary = "FreeBSD -- Unbounded allocation in ctl(4) CAM Target Layer"
details = """
Problem Description:
====================

The command ctl\\_persistent\\_reserve\\_out allows the caller to
specify an arbitrary size which will be passed to the kernel's
memory allocator.

Impact:
=======

A malicious guest could cause a Denial of Service (DoS) on the
host."""
affected = []
id = "FBSD-2024-0047"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-39281"

[[references]]
type = "ADVISORY"
url = "https://www.freebsd.org/security/advisories/FreeBSD-SA-24:18.ctl.asc"

[database_specific]
vid = "8caa5d60-a174-11ef-9a62-002590c1f29c"
discovery = "2024-10-29T00:00:00Z"
