schema_version = "1.7.0"
modified = "2025-05-04T00:00:00Z"
published = "2025-05-04T00:00:00Z"
summary = "fcgi -- Heap-based buffer overflow via crafted nameLen/valueLen in ReadParams"
details = """
cve@mitre.org reports:

> FastCGI fcgi2 (aka fcgi) 2.x through 2.4.4 has an integer
> overflow (and resultant heap-based buffer overflow) via
> crafted nameLen or valueLen values in data to the IPC socket.
> This occurs in ReadParams in fcgiapp.c."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-23016" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-23016" },
    { type = "WEB", url = "https://github.com/FastCGI-Archives/fcgi2/issues/67" },
]
affected = []
id = "FBSD-2025-0141"

[database_specific]
vid = "5f868a5f-2943-11f0-bb22-f02f7432cf97"
discovery = "2025-01-10T00:00:00Z"
