schema_version = "1.7.0"
modified = "2025-06-01T00:00:00Z"
published = "2025-06-01T00:00:00Z"
summary = "curl -- Multiple vulnerabilities"
details = """
curl security team reports:

> CVE-2025-5025: No QUIC certificate pinning with wolfSSL
>
> CVE-2025-4947: QUIC certificate check skip with wolfSSL"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-5025" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-5025" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-4947" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-4947" },
]
affected = []
id = "FBSD-2025-0101"

[database_specific]
vid = "533b4470-3f25-11f0-b440-f02f7432cf97"
discovery = "2025-05-28T00:00:00Z"
