schema_version = "1.7.0"
modified = "2025-07-08T00:00:00Z"
published = "2025-07-08T00:00:00Z"
summary = "MongoDB -- may be susceptible to DoS due to Accumulated Memory Allocation"
details = """
cna@mongodb.com reports:

> MongoDB Server may be susceptible to disruption caused by
> high memory usage, potentially leading to server crash. This
> condition is linked to inefficiencies in memory management
> related to internal operations. In scenarios where certain
> internal processes persist longer than anticipated, memory
> consumption can increase, potentially impacting server
> stability and availability."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-6712" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-6712" },
]
affected = []
id = "FBSD-2025-0049"

[database_specific]
vid = "764204eb-5bc5-11f0-834f-b42e991fc52e"
discovery = "2025-07-07T00:00:00Z"
