schema_version = "1.7.0"
modified = "2024-12-15T00:00:00Z"
published = "2024-12-15T00:00:00Z"
summary = "py-matrix-synapse -- multiple vulnerabilities in versions prior to 1.120.1"
details = """
element-hq/synapse developers report:

> [The 1.120.1] release fixes multiple security
> vulnerabilities, some affecting all prior versions of
> Synapse. Server administrators are encouraged to
> update Synapse as soon as possible. We are not aware
> of these vulnerabilities being exploited in the
> wild.
>
> Administrators who are unable to update Synapse may
> use the workarounds described in the linked GitHub
> Security Advisory below."""
id = "FBSD-2024-0012"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-52805"

[[references]]
type = "WEB"
url = "https://github.com/element-hq/synapse/security/advisories/GHSA-rfq8-j7rh-8hf2"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-52815"

[[references]]
type = "WEB"
url = "https://github.com/element-hq/synapse/security/advisories/GHSA-f3r3-h2mq-hx2h"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-53863"

[[references]]
type = "WEB"
url = "https://github.com/element-hq/synapse/security/advisories/GHSA-vp6v-whfm-rv3g"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-53867"

[[references]]
type = "WEB"
url = "https://github.com/element-hq/synapse/security/advisories/GHSA-56w4-5538-8v8h"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-37302"

[[references]]
type = "WEB"
url = "https://github.com/element-hq/synapse/security/advisories/GHSA-4mhg-xv73-xq2x"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-37303"

[[references]]
type = "WEB"
url = "https://github.com/element-hq/synapse/security/advisories/GHSA-gjgr-7834-rhxr"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py39-matrix-synapse"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.120.1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py310-matrix-synapse"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.120.1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py311-matrix-synapse"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.120.1" },
    { introduced = "0" },
]

[database_specific]
vid = "71f3e9f0-bafc-11ef-885d-901b0e934d69"
discovery = "2024-12-03T00:00:00Z"
