schema_version = "1.7.0"
modified = "2025-04-22T00:00:00Z"
published = "2025-04-22T00:00:00Z"
summary = "Navidrome -- Authentication bypass in Subsonic API"
details = """
Deluan reports:

> In certain Subsonic API endpoints, authentication can be
> bypassed by using a non-existent username combined with an
> empty (salted) password hash. This allows read-only access to
> the server’s resources, though attempts at write operations
> fail with a “permission denied” error."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-27112" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-27112" },
]
affected = []
id = "FBSD-2025-0152"

[database_specific]
vid = "5ca2cafa-1f24-11f0-ab07-f8f21e52f724"
discovery = "2025-02-25T00:00:00Z"
