schema_version = "1.7.0"
modified = "2024-11-23T00:00:00Z"
published = "2024-11-23T00:00:00Z"
summary = "qt6-webengine -- Multiple vulnerabilities"
details = """
Qt qtwebengine-chromium repo reports:

> Backports for 16 security bugs in Chromium:
>
> * CVE-2024-9120: Use after free in Dawn
> * CVE-2024-9122: Type Confusion in V8
> * CVE-2024-9123: Integer overflow in Skia
> * CVE-2024-9369: Insufficient data validation in Mojo
> * CVE-2024-9602: Type confusion in V8
> * CVE-2024-9603: Type confusion in V8
> * CVE-2024-9965: Insufficient data validation in DevTools
> * CVE-2024-9966: Inappropriate implementation in Navigations
> * CVE-2024-10229: Inappropriate implementation in Extensions
> * CVE-2024-10230: Type confusion in V8
> * CVE-2024-10231: Type confusion in V8
> * CVE-2024-10487: Out of bounds write in Dawn
> * CVE-2024-10827: Use after free in Serial
> * CVE-2024-45490: Negative length in libexpat
> * CVE-2024-45491: Integer overflow in libexpat
> * CVE-2024-45492: Integer overflow in libexpat"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9120" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9122" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9123" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9369" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9602" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9603" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9965" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9966" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-10229" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-10230" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-10231" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-10487" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-10827" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-45490" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-45491" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-45492" },
    { type = "WEB", url = "https://code.qt.io/cgit/qt/qtwebengine-chromium.git/log/?h=118-based" },
]
affected = []
id = "FBSD-2024-0032"

[database_specific]
vid = "889eddee-a964-11ef-b680-4ccc6adda413"
discovery = "2024-09-26T00:00:00Z"
