schema_version = "1.7.0"
modified = "2024-08-16T00:00:00Z"
published = "2024-08-16T00:00:00Z"
summary = "Dovecot -- DoS"
details = """
Dovecot reports:

> A DoS is possible with a large number of address headers or abnormally large email headers."""
affected = []
id = "FBSD-2024-0142"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-23184"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-23185"

[[references]]
type = "WEB"
url = "https://dovecot.org/mailman3/hyperkitty/list/dovecot-news@dovecot.org/thread/2CSVL56LFPAXVLWMGXEIWZL736PSYHP5/"

[database_specific]
vid = "6a6ad6cb-5c6c-11ef-b456-001e676bf734"
discovery = "2024-08-14T00:00:00Z"
