schema_version = "1.7.0"
modified = "2024-05-13T00:00:00Z"
published = "2024-05-13T00:00:00Z"
summary = "go -- net: malformed DNS message can cause infinite loop"
details = """
The Go project reports:

> net: malformed DNS message can cause infinite loop
>
> A malformed DNS message in response to a query can cause
> the Lookup functions to get stuck in an infinite loop."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-24788" },
    { type = "WEB", url = "https://go.dev/issue/66754" },
]
id = "FBSD-2024-0215"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "go121"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.21.10" },
    { introduced = "0" },
]

[database_specific]
vid = "d3847eba-114b-11ef-9c21-901b0e9408dc"
discovery = "2024-04-25T00:00:00Z"
