schema_version = "1.7.0"
modified = "2025-02-25T00:00:00Z"
published = "2025-02-24T00:00:00Z"
summary = "Emacs -- Arbitrary code execution vulnerability"
details = """
Problem Description
===================

A shell injection vulnerability exists in GNU Emacs due to improper
handling of custom man URI schemes.

Impact
======

Initially considered low severity, as it required user interaction with
local files, it was later discovered that an attacker could exploit this
vulnerability by tricking a user into visiting a specially crafted
website or an HTTP URL with a redirect, leading to arbitrary shell
command execution without further user action."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-1244" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-1244" },
]
id = "FBSD-2025-0217"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-canna"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "30.1,3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-nox"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "30.1,3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-wayland"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "30.1,3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-devel"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "30.0.50.20240115,3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-devel-nox"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "30.0.50.20240115,3" },
    { introduced = "0" },
]

[database_specific]
vid = "e60e538f-e795-4a00-b475-cc85a7546e00"
discovery = "2025-02-11T00:00:00Z"
