schema_version = "1.7.0"
modified = "2025-07-03T00:00:00Z"
published = "2025-07-03T00:00:00Z"
summary = "Mozilla -- exploitable crash"
details = """
security@mozilla.org reports:

> A use-after-free in FontFaceSet resulted in a potentially
> exploitable crash."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-6424" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-6424" },
]
id = "FBSD-2025-0061"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "115.25.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "140.0" },
    { introduced = "0" },
]

[database_specific]
vid = "bab7386a-582f-11f0-97d0-b42e991fc52e"
discovery = "2025-06-24T00:00:00Z"
