schema_version = "1.7.0"
modified = "2024-05-25T00:00:00Z"
published = "2024-05-25T00:00:00Z"
summary = "electron29 -- use after free in Dawn"
details = """
Electron developers report:

> This update fixes the following vulnerability:
>
> * Security: backported fix for CVE-2024-4948."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-4948" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-xvp9-87cv-m4fv" },
]
affected = []
id = "FBSD-2024-0199"

[database_specific]
vid = "04e78f32-04b2-4c23-bfae-72600842d317"
discovery = "2024-05-22T00:00:00Z"
