schema_version = "1.7.0"
modified = "2024-12-20T00:00:00Z"
published = "2024-12-20T00:00:00Z"
summary = "Vaultwarden -- Admin organization permissions"
details = """
The Vaultwarden project reports:

> Admins from any organization were able to modify or delete groups in any other organization if they know the group's uuid."""
references = [
    { type = "WEB", url = "https://github.com/dani-garcia/vaultwarden/pull/5291" },
]
affected = []
id = "FBSD-2024-0003"

[database_specific]
vid = "0a8dbc7f-bedc-11ef-b5a1-000ec6d40964"
discovery = "2024-12-20T00:00:00Z"
