schema_version = "1.7.0"
modified = "2024-03-26T00:00:00Z"
published = "2024-03-26T00:00:00Z"
summary = "emacs -- multiple vulnerabilities"
details = """
GNU Emacs developers report:

> Emacs 29.3 is an emergency bugfix release intended to fix several security vulnerabilities.
>
> * Arbitrary Lisp code is no longer evaluated as part of turning on Org mode. This is for security reasons, to avoid evaluating malicious Lisp code.
> * New buffer-local variable 'untrusted-content'. When this is non-nil, Lisp programs should treat buffer contents with extra caution.
> * Gnus now treats inline MIME contents as untrusted. To get back previous insecure behavior, 'untrusted-content' should be reset to nil in the buffer.
> * LaTeX preview is now by default disabled for email attachments. To get back previous insecure behavior, set the variable 'org--latex-preview-when-risky' to a non-nil value.
> * Org mode now considers contents of remote files to be untrusted. Remote files are recognized by calling 'file-remote-p'."""
id = "FBSD-2024-0260"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-30202"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-30203"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-30204"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-30205"

[[references]]
type = "WEB"
url = "https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/NEWS?h=emacs-29.3"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-canna"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "29.3,3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-nox"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "29.3,3" },
    { introduced = "0" },
]

[database_specific]
vid = "f661184a-eb90-11ee-92fc-1c697a616631"
discovery = "2024-03-24T00:00:00Z"
