schema_version = "1.7.0"
modified = "2025-04-04T00:00:00Z"
published = "2025-04-04T00:00:00Z"
summary = "Mozilla -- use-after-free while parsing JSON"
details = """
security@mozilla.org reports:

> Parsing a JavaScript module as JSON could, under some
> circumstances, cause cross-compartment access, which may
> result in a use-after-free."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0240" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-0240" },
]
id = "FBSD-2025-0173"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "librewolf"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "134.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.6.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "134.0" },
    { introduced = "0" },
]

[database_specific]
vid = "f1f92cd3-116c-11f0-8b2c-b42e991fc52e"
discovery = "2025-01-07T00:00:00Z"
