schema_version = "1.7.0"
modified = "2024-09-20T00:00:00Z"
published = "2024-09-20T00:00:00Z"
summary = "FreeBSD -- bhyve(8) out-of-bounds read access via XHCI emulation"
details = """
Problem Description:
====================

bhyve can be configured to emulate devices on a virtual USB
controller (XHCI), such as USB tablet devices. An insufficient
boundary validation in the USB code could lead to an out-of-bounds read
on the heap, which could potentially lead to an arbitrary write and
remote code execution.

Impact:
=======

A malicious, privileged software running in a guest VM can exploit
the vulnerability to crash the hypervisor process or potentially achieve
code execution on the host in the bhyve userspace process, which
typically runs as root. Note that bhyve runs in a Capsicum sandbox, so
malicious code is constrained by the capabilities available to the bhyve
process."""
affected = []
id = "FBSD-2024-0102"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-41721"

[[references]]
type = "ADVISORY"
url = "https://www.freebsd.org/security/advisories/FreeBSD-SA-24:15.bhyve.asc"

[database_specific]
vid = "1febd09b-7716-11ef-9a62-002590c1f29c"
discovery = "2024-09-19T00:00:00Z"
