schema_version = "1.7.0"
modified = "2025-07-24T00:00:00Z"
published = "2025-07-24T00:00:00Z"
summary = "Mozilla -- CORS circumvention"
details = """
security@mozilla.org reports:

> Thunderbird cached CORS preflight responses across IP
> address changes. This allowed circumventing CORS with DNS
> rebinding."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-8036" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-8036" },
]
id = "FBSD-2025-0021"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "140.1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "141.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "140.1" },
    { introduced = "0" },
]

[database_specific]
vid = "58027367-685e-11f0-a12d-b42e991fc52e"
discovery = "2025-07-22T00:00:00Z"
