schema_version = "1.7.0"
modified = "2025-02-07T00:00:00Z"
published = "2025-02-07T00:00:00Z"
summary = "libcaca -- Multiple vulnerabilities"
details = """
Sam Hocevar reports:

> Multiple memory leaks and invalid memory accesses:
>
> * CVE-2018-20545: Illegal WRITE memory access at common-image.c
> * CVE-2018-20546: Illegal READ memory access at caca/dither.c
> * CVE-2018-20547: Illegal READ memory access at caca/dither.c
> * CVE-2018-20548: Illegal WRITE memory access at common-image.c
> * CVE-2018-20549: Illegal WRITE memory access at caca/file.c
> * CVE-2021-3410: Buffer overflow in libcaca/caca/canvas.c in function caca\\_resize
> * CVE-2021-30498: Heap buffer overflow in export.c in function export\\_tga
> * CVE-2021-30499: Buffer overflow in export.c in function export\\_troff"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2018-20545" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2018-20546" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2018-20547" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2018-20548" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2018-20549" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2021-3410" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2021-30498" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2021-30499" },
    { type = "WEB", url = "https://github.com/cacalabs/libcaca/releases/tag/v0.99.beta20" },
]
affected = []
id = "FBSD-2025-0235"

[database_specific]
vid = "c10b639c-e51c-11ef-9e76-4ccc6adda413"
discovery = "2021-10-19T00:00:00Z"
