schema_version = "1.7.0"
modified = "2025-04-16T00:00:00Z"
published = "2025-04-16T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 2 security fixes:
>
> * [409619251] Critical CVE-2025-3619: Heap buffer overflow in Codecs. Reported by Elias Hohl on 2025-04-09
> * [405292639] High CVE-2025-3620: Use after free in USB. Reported by @retsew0x01 on 2025-03-21"""
id = "FBSD-2025-0155"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-3619"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-3620"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2025/04/stable-channel-update-for-desktop_15.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "135.0.7049.95" },
    { introduced = "0" },
]

[database_specific]
vid = "bf5d29ea-1a93-11f0-8cb5-a8a1599412c6"
discovery = "2025-04-15T00:00:00Z"
