schema_version = "1.7.0"
modified = "2025-08-14T00:00:00Z"
published = "2025-08-14T00:00:00Z"
summary = "Gitlab -- vulnerabilities"
details = """
Gitlab reports:

> Cross-site scripting issue in blob viewer impacts GitLab CE/EE
>
> Cross-site scripting issue in labels impacts GitLab CE/EE
>
> Cross-site scripting issue in Workitem impacts GitLab CE/EE
>
> Improper Handling of Permissions issue in project API impacts GitLab CE/EE
>
> Incorrect Privilege Assignment issue in delete issues operation impacts GitLab CE/EE
>
> Allocation of Resources Without Limits issue in release name creation impacts GitLab CE/EE
>
> Incorrect Authorization issue in jobs API impacts GitLab CE/EE
>
> Authorization issue in Merge request approval policy impacts GitLab EE
>
> Inefficient Regular Expression Complexity issue in wiki impacts GitLab CE/EE
>
> Allocation of Resources Without Limits issue in Mattermost integration impacts GitLab CE/EE
>
> Incorrect Permission Assignment issue in ID token impacts GitLab CE/EE
>
> Insufficient Access Control issue in IP Restriction impacts GitLab EE"""
id = "FBSD-2025-0004"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-7734"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-7739"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-6186"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-8094"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-12303"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-2614"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-10219"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-8770"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-2937"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-1477"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-5819"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-2498"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2025/08/13/patch-release-gitlab-18-2-2-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "18.2.0" },
    { fixed = "18.2.2" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "18.1.0" },
    { fixed = "18.1.4" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "8.14.0" },
    { fixed = "18.0.6" },
]

[database_specific]
vid = "7bfe6f39-78be-11f0-9d03-2cf05da270f3"
discovery = "2025-08-13T00:00:00Z"
