schema_version = "1.7.0"
modified = "2025-03-13T00:00:00Z"
published = "2025-03-13T00:00:00Z"
summary = "Gitlab -- Vulnerabilities"
details = """
Gitlab reports:

> CVE-2025-25291 and CVE-2025-25292 (third party gem ruby-saml)
>
> CVE-2025-27407 (third party gem graphql)
>
> Denial of Service Due to Inefficient Processing of Untrusted Input
>
> Credentials disclosed when repository mirroring fails
>
> Denial of Service Vulnerability in GitLab Approval Rules due to Unbounded Field
>
> Internal Notes in Merge Requests Are Emailed to Non-Members Upon Review Submission
>
> Maintainer can inject shell code in Google integrations
>
> Guest with custom Admin group member permissions can approve the users invitation despite user caps"""
id = "FBSD-2025-0198"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-25291"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-25292"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-27407"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-13054"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-12380"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-1257"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-0652"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8402"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-7296"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2025/03/12/patch-release-gitlab-17-9-2-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.9.0" },
    { fixed = "17.9.2" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.8.0" },
    { fixed = "17.8.5" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "11.5" },
    { fixed = "17.7.7" },
]

[database_specific]
vid = "a435609c-ffd5-11ef-b4e4-2cf05da270f3"
discovery = "2025-03-12T00:00:00Z"
