schema_version = "1.7.0"
modified = "2025-01-20T00:00:00Z"
published = "2025-01-20T00:00:00Z"
summary = "electron31 -- multiple vulnerabilities"
details = """
Electron developers report:

> This update fixes the following vulnerabilities:
>
> * Security: backported fix for CVE-2024-12053.
> * Security: backported fix for CVE-2024-12693.
> * Security: backported fix for CVE-2024-12694."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-12053" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-wvx7-72hc-rp32" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-12693" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-m84q-p89f-6cc5" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-12694" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-cgc6-4xgf-5q5x" },
]
affected = []
id = "FBSD-2025-0255"

[database_specific]
vid = "3161429b-3897-4593-84a0-b41ffbbfa36b"
discovery = "2025-01-14T00:00:00Z"
