schema_version = "1.7.0"
modified = "2025-06-15T00:00:00Z"
published = "2025-06-15T00:00:00Z"
summary = "Mozilla -- control access bypass"
details = """
security@mozilla.org reports:

> Thunderbird's update mechanism allowed a medium-integrity user
> process to interfere with the SYSTEM-level updater by manipulating
> the file-locking behavior. By injecting code into the user-privileged
> process, an attacker could bypass intended access controls, allowing
> SYSTEM-level file operations on paths controlled by a non-privileged
> user and enabling privilege escalation. This vulnerability affects
> Firefox < 138, Firefox ESR < 128.10, Firefox ESR < 115.23,
> Thunderbird < 138, and Thunderbird < 128.10."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-2817" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-2817" },
]
id = "FBSD-2025-0084"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.10" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.0" },
    { introduced = "0" },
]

[database_specific]
vid = "201cccc1-4a01-11f0-b0f8-b42e991fc52e"
discovery = "2025-04-29T00:00:00Z"
