schema_version = "1.7.0"
modified = "2024-02-12T00:00:00Z"
published = "2024-02-12T00:00:00Z"
summary = "openexr -- Heap Overflow in Scanline Deep Data Parsing"
details = """
Austin Hackers Anonymous report:

> Due to a failure in validating the number of scanline samples of a OpenEXR file containing deep scanline data, Academy Software Foundation OpenEXR image parsing library version 3.2.1 and prior is susceptible to a heap-based buffer overflow vulnerability.

> [...] it is in a routine that is predominantly used for development and
> testing. It is not likely to appear in production code."""
affected = []
id = "FBSD-2024-0296"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-5841"

[[references]]
type = "WEB"
url = "https://takeonme.org/cves/CVE-2023-5841.html"

[[references]]
type = "WEB"
url = "https://github.com/AcademySoftwareFoundation/openexr/releases/tag/v3.2.2"

[database_specific]
vid = "f161a5ad-c9bd-11ee-b7a7-353f1e043d9a"
discovery = "2023-10-26T00:00:00Z"
