schema_version = "1.7.0"
modified = "2024-11-27T00:00:00Z"
published = "2024-11-27T00:00:00Z"
summary = "Gitlab -- vulnerabilities"
details = """
Gitlab reports:

> Privilege Escalation via LFS Tokens
>
> DoS through uncontrolled resource consumption when viewing a maliciously crafted cargo.toml file
>
> Unintended Access to Usage Data via Scoped Tokens
>
> Gitlab DOS via Harbor registry integration
>
> Resource exhaustion and denial of service with test\\_report API calls
>
> Streaming endpoint did not invalidate tokens after revocation"""
id = "FBSD-2024-0030"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8114"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8237"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-11669"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8177"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-11828"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-11668"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2024/11/26/patch-release-gitlab-17-6-1-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.6.0" },
    { fixed = "17.6.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.5.0" },
    { fixed = "17.5.3" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "8.12.0" },
    { fixed = "17.4.5" },
]

[database_specific]
vid = "2263ea04-ac81-11ef-998c-2cf05da270f3"
discovery = "2024-11-26T00:00:00Z"
