schema_version = "1.7.0"
modified = "2025-05-31T00:00:00Z"
published = "2025-05-31T00:00:00Z"
summary = "libxml2 -- Out-of-bounds memory access"
details = """
cve@mitre.org reports:

> In libxml2 before 2.13.8 and 2.14.x before 2.14.2, out-of-bounds
> memory access can occur in the Python API (Python bindings) because
> of an incorrect return value. This occurs in xmlPythonFileRead and
> xmlPythonFileReadRaw because of a difference between bytes and
> characters."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-32414" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-32414" },
]
id = "FBSD-2025-0102"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py310-libxml2"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "2.11.9_3" },
    { introduced = "0" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "2.12.0" },
    { fixed = "2.13.8" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "2.14.0" },
    { fixed = "2.14.2" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py311-libxml2"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "2.11.9_3" },
    { introduced = "0" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "2.12.0" },
    { fixed = "2.13.8" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "2.14.0" },
    { fixed = "2.14.2" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py312-libxml2"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "2.11.9_3" },
    { introduced = "0" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "2.12.0" },
    { fixed = "2.13.8" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "2.14.0" },
    { fixed = "2.14.2" },
]

[database_specific]
vid = "2926c487-3e53-11f0-95d4-00a098b42aeb"
discovery = "2025-04-08T00:00:00Z"
