schema_version = "1.7.0"
modified = "2024-04-22T00:00:00Z"
published = "2024-04-22T00:00:00Z"
summary = "sdl2_sound -- multiple vulnerabilities"
details = """
GitHub Security Lab reports:

> stb\\_image.h and stb\\_vorbis libraries contain several memory access violations of different severity
>
> 1. Wild address read in stbi\\_\\_gif\\_load\\_next (GHSL-2023-145).
> 2. Multi-byte read heap buffer overflow in stbi\\_\\_vertical\\_flip (GHSL-2023-146).
> 3. Disclosure of uninitialized memory in stbi\\_\\_tga\\_load (GHSL-2023-147).
> 4. Double-free in stbi\\_\\_load\\_gif\\_main\\_outofmem (GHSL-2023-148).
> 5. Null pointer dereference in stbi\\_\\_convert\\_format (GHSL-2023-149).
> 6. Possible double-free or memory leak in stbi\\_\\_load\\_gif\\_main (GHSL-2023-150).
> 7. Null pointer dereference because of an uninitialized variable (GHSL-2023-151).
> 8. 0 byte write heap buffer overflow in start\\_decoder (GHSL-2023-165)
> 9. Multi-byte write heap buffer overflow in start\\_decoder (GHSL-2023-166)
> 10. Heap buffer out of bounds write in start\\_decoder (GHSL-2023-167)
> 11. Off-by-one heap buffer write in start\\_decoder (GHSL-2023-168)
> 12. Attempt to free an uninitialized memory pointer in vorbis\\_deinit (GHSL-2023-169)
> 13. Null pointer dereference in vorbis\\_deinit (GHSL-2023-170)
> 14. Out of bounds heap buffer write (GHSL-2023-171)
> 15. Wild address read in vorbis\\_decode\\_packet\\_rest (GHSL-2023-172)"""
affected = []
id = "FBSD-2024-0235"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-45676"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-45677"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-45680"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-45681"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-45682"

[[references]]
type = "WEB"
url = "https://securitylab.github.com/advisories/GHSL-2023-145_GHSL-2023-151_stb_image_h/"

[database_specific]
vid = "304d92c3-00c5-11ef-bd52-080027bff743"
discovery = "2023-10-20T00:00:00Z"
