schema_version = "1.7.0"
modified = "2024-08-06T00:00:00Z"
published = "2024-08-06T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 5 security fixes:
>
> * [350528343] Critical CVE-2024-7532: Out of bounds memory access in ANGLE. Reported by wgslfuzz on 2024-07-02
> * [353552540] High CVE-2024-7533: Use after free in Sharing. Reported by lime(@limeSec\\_) from TIANGONG Team of Legendsec at QI-ANXIN Group on 2024-07-17
> * [355256380] High CVE-2024-7550: Type Confusion in V8. Reported by Zhenghang Xiao (@Kipreyyy) on 2024-07-25
> * [352467338] High CVE-2024-7534: Heap buffer overflow in Layout. Reported by Tashita Software Security on 2024-07-11
> * [352690885] High CVE-2024-7535: Inappropriate implementation in V8. Reported by Tashita Software Security on 2024-07-12
> * [354847246] High CVE-2024-7536: Use after free in WebAudio. Reported by Cassidy Kim(@cassidy6564) on 2024-07-23"""
id = "FBSD-2024-0155"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-7532"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-7550"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-7534"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-7535"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-7536"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2024/08/stable-channel-update-for-desktop.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "127.0.6533.99" },
    { introduced = "0" },
]

[database_specific]
vid = "05cd9f82-5426-11ef-8a0f-a8a1599412c6"
discovery = "2024-08-06T00:00:00Z"
