schema_version = "1.7.0"
modified = "2025-03-05T00:00:00Z"
published = "2025-03-05T00:00:00Z"
summary = "Spotipy -- Spotipy's cache file, containing spotify auth token, is created with overly broad permissions"
details = """
security-advisories@github.com reports:

> Spotipy is a lightweight Python library for the Spotify Web API.
> The `CacheHandler` class creates a cache file to store the auth
> token. Prior to version 2.25.1, the file created has `rw-r--r--`
> (644) permissions by default, when it could be locked down to
> `rw-------` (600) permissions. This leads to overly broad exposure
> of the spotify auth token. If this token can be read by an attacker
> (another user on the machine, or a process running as another user),
> it can be used to perform administrative actions on the Spotify
> account, depending on the scope granted to the token. Version
> 2.25.1 tightens the cache file permissions."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-27154" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-27154" },
]
id = "FBSD-2025-0209"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py39-spotipy"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "2.25.1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py310-spotipy"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "2.25.1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py311-spotipy"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "2.25.1" },
    { introduced = "0" },
]

[database_specific]
vid = "475d1968-f99d-11ef-b382-b0416f0c4c67"
discovery = "2025-02-27T00:00:00Z"
