schema_version = "1.7.0"
modified = "2024-01-02T00:00:00Z"
published = "2024-01-02T00:00:00Z"
summary = "FreeBSD -- Prefix Truncation Attack in the SSH protocol"
details = """
Problem Description:
====================

The SSH protocol executes an initial handshake between the
server and the client. This protocol handshake includes the
possibility of several extensions allowing different options to be
selected. Validation of the packets in the handshake is done through
sequence numbers.

Impact:
=======

A man in the middle attacker can silently manipulate handshake
messages to truncate extension negotiation messages potentially
leading to less secure client authentication algorithms or deactivating
keystroke timing attack countermeasures."""
affected = []
id = "FBSD-2024-0332"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-48795"

[[references]]
type = "ADVISORY"
url = "https://www.freebsd.org/security/advisories/FreeBSD-SA-23:19.openssh.asc"

[database_specific]
vid = "13d83980-9f18-11ee-8e38-002590c1f29c"
discovery = "2023-12-19T00:00:00Z"
