schema_version = "1.7.0"
modified = "2024-03-26T00:00:00Z"
published = "2024-03-26T00:00:00Z"
summary = "phpmyfaq -- multiple vulnerabilities"
details = """
phpMyFAQ team reports:

> The phpMyFAQ Team has learned of multiple security issues that'd
> been discovered in phpMyFAQ 3.2.5 and earlier. phpMyFAQ contains
> cross-site scripting (XSS), SQL injection and bypass
> vulnerabilities."""
id = "FBSD-2024-0259"

[[references]]
type = "WEB"
url = "https://github.com/thorsten/phpMyFAQ/security/advisories/GHSA-mmh6-5cpf-2c72"

[[references]]
type = "WEB"
url = "https://github.com/thorsten/phpMyFAQ/security/advisories/GHSA-hm8r-95g3-5hj9"

[[references]]
type = "WEB"
url = "https://github.com/thorsten/phpMyFAQ/security/advisories/GHSA-48vw-jpf8-hwqh"

[[references]]
type = "WEB"
url = "https://github.com/thorsten/phpMyFAQ/security/advisories/GHSA-2grw-mc9r-822r"

[[references]]
type = "WEB"
url = "https://github.com/thorsten/phpMyFAQ/security/advisories/GHSA-6p68-36m6-392r"

[[references]]
type = "WEB"
url = "https://github.com/thorsten/phpMyFAQ/security/advisories/GHSA-pwh2-fpfr-x5gf"

[[references]]
type = "WEB"
url = "https://github.com/thorsten/phpMyFAQ/security/advisories/GHSA-q7g6-xfh2-vhpx"

[[references]]
type = "WEB"
url = "https://github.com/thorsten/phpMyFAQ/security/advisories/GHSA-qgxx-4xv5-6hcw"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "phpmyfaq-php82"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.2.6" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "phpmyfaq-php83"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.2.6" },
    { introduced = "0" },
]

[database_specific]
vid = "8b3be705-eba7-11ee-99b3-589cfc0f81b0"
discovery = "2024-03-25T00:00:00Z"
