schema_version = "1.7.0"
modified = "2025-02-24T00:00:00Z"
published = "2025-02-24T00:00:00Z"
summary = "Emacs -- Shell injection vulnerability"
details = """
Problem Description:
====================

An Emacs user who chooses to invoke elisp-completion-at-point (for
code completion) on untrusted Emacs Lisp source code can trigger unsafe
Lisp macro expansion that allows attackers to execute arbitrary code.
This unsafe expansion also occurs if a user chooses to enable on-the-fly
diagnosis that byte compiles untrusted Emacs Lisp source code."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-53920" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-53920" },
]
id = "FBSD-2025-0218"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-canna"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "30.1,3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-nox"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "30.1,3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-wayland"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "30.1,3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-devel"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "31.0.50.20250101,3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-devel-nox"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "31.0.50.20250101,3" },
    { introduced = "0" },
]

[database_specific]
vid = "7ba6c085-1590-491a-98ce-5452646b196f"
discovery = "2024-11-27T00:00:00Z"
