schema_version = "1.7.0"
modified = "2024-05-14T00:00:00Z"
published = "2024-05-14T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 1 security fix:
>
> * [339458194] High CVE-2024-4761: Out of bounds write in V8. Reported by Anonymous on 2024-05-09"""
id = "FBSD-2024-0214"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4761"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_13.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "124.0.6367.207" },
    { introduced = "0" },
]

[database_specific]
vid = "8e0e8b56-11c6-11ef-9f97-a8a1599412c6"
discovery = "2024-05-13T00:00:00Z"
