schema_version = "1.7.0"
modified = "2024-11-16T00:00:00Z"
published = "2024-11-16T00:00:00Z"
summary = "Vaultwarden -- Multiple vulnerabilities"
details = """
The Vaultwarden project reports:

> This release has fixed some CVE Reports reported by a third party
> security auditor and we recommend everybody to update to the
> latest version as soon as possible."""
references = [
    { type = "WEB", url = "https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.4" },
]
affected = []
id = "FBSD-2024-0037"

[database_specific]
vid = "aba28514-a414-11ef-98e7-84a93843eb75"
discovery = "2024-11-10T00:00:00Z"
