schema_version = "1.7.0"
modified = "2025-01-23T00:00:00Z"
published = "2025-01-23T00:00:00Z"
summary = "clamav -- Possbile denial-of-service vulnerability"
details = """
The ClamAV project reports:

> A possible buffer overflow read bug is found in the OLE2
> file parser that could cause a denial-of-service (DoS)
> condition."""
id = "FBSD-2025-0252"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-20128"

[[references]]
type = "WEB"
url = "https://blog.clamav.net/2025/01/clamav-142-and-108-security-patch.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "clamav-lts"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "1.0.0,1" },
    { fixed = "1.0.8,1" },
]

[database_specific]
vid = "1e109b60-d92e-11ef-a661-08002784c58d"
discovery = "2025-01-22T00:00:00Z"
