schema_version = "1.7.0"
modified = "2025-03-28T00:00:00Z"
published = "2025-03-28T00:00:00Z"
summary = "electron{33,34} -- Incorrect handle provided in unspecified circumstances in Mojo"
details = """
Electron developers report:

> This update fixes the following vulnerability:
>
> * Security: backported fix for CVE-2025-2783."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-2783" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-hfqm-jfc6-rh2f" },
]
id = "FBSD-2025-0190"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "electron34"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "34.4.1" },
    { introduced = "0" },
]

[database_specific]
vid = "01a7e1e1-d249-4dd8-9a4a-ef95b5747afb"
discovery = "2025-03-27T00:00:00Z"
