schema_version = "1.7.0"
modified = "2024-07-04T00:00:00Z"
published = "2024-07-04T00:00:00Z"
summary = "Request Tracker -- information exposure vulnerability"
details = """
Request Tracker reports:

CVE-2024-3262 describes previously viewed pages being stored in the
browser cache, which is the typical default behavior of most browsers to
enable the \"back\" button. Someone who gains access to a host computer could
potentially view ticket data using the back button, even after logging out
of RT. The CVE specifically references RT version 4.4.1, but this behavior
is present in most browsers viewing all versions of RT before 5.0.6."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-3262" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-6426-p644-ffcf" },
]
affected = []
id = "FBSD-2024-0171"

[database_specific]
vid = "51498ee4-39a1-11ef-b609-002590c1f29c"
discovery = "2024-04-04T00:00:00Z"
