schema_version = "1.7.0"
modified = "2025-01-14T00:00:00Z"
published = "2025-01-14T00:00:00Z"
summary = "rsync -- Multiple security fixes"
details = """
rsync reports:

> This update includes multiple security fixes:
>
> * CVE-2024-12084: Heap Buffer Overflow in Checksum Parsing
> * CVE-2024-12085: Info Leak via uninitialized Stack contents defeats ASLR
> * CVE-2024-12086: Server leaks arbitrary client files
> * CVE-2024-12087: Server can make client write files outside of destination directory using symbolic links
> * CVE-2024-12088: --safe-links Bypass
> * CVE-2024-12747: symlink race condition"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-12084" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-12085" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-12086" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-12087" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-12088" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-12747" },
]
affected = []
id = "FBSD-2025-0258"

[database_specific]
vid = "163edccf-d2ba-11ef-b10e-589cfc10a551"
discovery = "2025-01-14T00:00:00Z"
