schema_version = "1.7.0"
modified = "2024-08-30T00:00:00Z"
published = "2024-08-30T00:00:00Z"
summary = "forgejo -- The scope of application tokens was not verified when writing containers or Conan packages."
details = """
The forgejo team reports:

> The scope of application tokens was not verified when writing
> containers or Conan packages. This is of no consequence when the
> user associated with the application token does not have write
> access to packages. If the user has write access to packages, such
> a token can be used to write containers and Conan packages. An
> application token that was used to write containers or Conan
> packages without the package:write scope will now fail with an
> unauthorized error. It must be re-created to include the
> package:write scope."""
references = [
    { type = "WEB", url = "https://codeberg.org/forgejo/forgejo/pulls/5149" },
]
affected = []
id = "FBSD-2024-0127"

[database_specific]
vid = "eb437e17-66a1-11ef-ac08-75165d18d8d2"
discovery = "2024-08-26T00:00:00Z"
