schema_version = "1.7.0"
modified = "2024-06-20T00:00:00Z"
published = "2024-06-20T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 6 security fixes:
>
> * [344608204] High CVE-2024-6100: Type Confusion in V8. Reported by Seunghyun Lee (@0x10n) participating in SSD Secure Disclosure's TyphoonPWN 2024 on 2024-06-04
> * [343748812] High CVE-2024-6101: Inappropriate implementation in WebAssembly. Reported by @ginggilBesel on 2024-05-31
> * [339169163] High CVE-2024-6102: Out of bounds memory access in Dawn. Reported by wgslfuzz on 2024-05-07
> * [344639860] High CVE-2024-6103: Use after free in Dawn. Reported by wgslfuzz on 2024-06-04"""
id = "FBSD-2024-0185"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-6100"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-6101"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-6102"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-6103"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2024/06/stable-channel-update-for-desktop_18.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "126.0.6478.114" },
    { introduced = "0" },
]

[database_specific]
vid = "007e7e77-2f06-11ef-8a0f-a8a1599412c6"
discovery = "2024-06-18T00:00:00Z"
