schema_version = "1.7.0"
modified = "2024-11-14T00:00:00Z"
published = "2024-11-14T00:00:00Z"
summary = "PostgreSQL -- PL/Perl environment variable changes execute arbitrary code"
details = """
PostgreSQL project reports:

> Incorrect control of environment variables in PostgreSQL
> PL/Perl allows an unprivileged database user to change
> sensitive process environment variables (e.g. PATH).
> That often suffices to enable arbitrary code execution,
> even if the attacker lacks a database server operating
> system user."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-10979" },
    { type = "WEB", url = "https://www.postgresql.org/support/security/CVE-2024-10979/" },
]
id = "FBSD-2024-0040"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql16-plperl"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "16.5" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql15-plperl"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "15.9" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql14-plperl"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "14.14" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql13-plperl"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "13.17" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql12-plperl"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "12.21" },
    { introduced = "0" },
]

[database_specific]
vid = "a03636f4-a29f-11ef-af48-6cc21735f730"
discovery = "2024-11-14T00:00:00Z"
