schema_version = "1.7.0"
modified = "2024-01-12T00:00:00Z"
published = "2024-01-12T00:00:00Z"
summary = "Gitlab -- vulnerabilities"
details = """
Gitlab reports:

> Account Takeover via Password Reset without user interactions
>
> Attacker can abuse Slack/Mattermost integrations to execute slash commands as another user
>
> Bypass CODEOWNERS approval removal
>
> Workspaces able to be created under different root namespace
>
> Commit signature validation ignores headers after signature"""
affected = []
id = "FBSD-2024-0324"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-7028"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-5356"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-4812"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-6955"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-2030"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2024/01/11/critical-security-release-gitlab-16-7-2-released/"

[database_specific]
vid = "4c8c2218-b120-11ee-90ec-001b217b3468"
discovery = "2024-01-11T00:00:00Z"
