schema_version = "1.7.0"
modified = "2024-03-31T00:00:00Z"
published = "2024-03-31T00:00:00Z"
summary = "mediawiki -- multiple vulnerabilities"
details = """
Mediawiki reports:

> (T355538, CVE-2024-PENDING) SECURITY: XSS in edit summary parser.
>
> (T357760, CVE-2024-PENDING) SECURITY: Denial of service vector via GET
> request to Special:MovePage on pages with thousands of subpages."""
id = "FBSD-2024-0255"

[[references]]
type = "WEB"
url = "https://lists.wikimedia.org/hyperkitty/list/mediawiki-announce@lists.wikimedia.org/message/V3WXEPXV2DU6WTVEKK4XHW4QXD5OFKD7/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "mediawiki140"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.40.3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "mediawiki141"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.41.1" },
    { introduced = "0" },
]

[database_specific]
vid = "d58726ff-ef5e-11ee-8d8e-080027a5b8e9"
discovery = "2024-03-15T00:00:00Z"
