schema_version = "1.7.0"
modified = "2024-04-10T00:00:00Z"
published = "2024-04-10T00:00:00Z"
summary = "wordpress -- XSS"
details = """
The Wordpress team reports:

> A cross-site scripting (XSS) vulnerability affecting the Avatar block type"""
references = [
    { type = "WEB", url = "https://wordpress.org/documentation/wordpress-version/version-6-4-4/" },
]
id = "FBSD-2024-0249"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "fr-wordpress-fr_FR"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "6.5.0,1" },
    { fixed = "6.5.1,1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "6.4.4,1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ru-wordpress-ru_RU"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "6.5.0" },
    { fixed = "6.5.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "6.4.4" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ja-wordpress-ja"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "6.5.0" },
    { fixed = "6.5.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "6.4.4" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "zh-wordpress-zh_CN"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "6.5.0" },
    { fixed = "6.5.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "6.4.4" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "zh-wordpress-zh_TW"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "6.5.0" },
    { fixed = "6.5.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "6.4.4" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "de-wordpress-de_DE"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "6.5.0" },
    { fixed = "6.5.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "6.4.4" },
    { introduced = "0" },
]

[database_specific]
vid = "ea4a2dfc-f761-11ee-af2c-589cfc0f81b0"
discovery = "2024-04-09T00:00:00Z"
