schema_version = "1.7.0"
modified = "2024-09-05T00:00:00Z"
published = "2024-09-05T00:00:00Z"
summary = "FreeBSD -- umtx Kernel panic or Use-After-Free"
details = """
Problem Description:
====================

Concurrent removals of such a mapping by using the UMTX\\_SHM\\_DESTROY
sub-request of UMTX\\_OP\\_SHM can lead to decreasing the reference
count of the object representing the mapping too many times, causing
it to be freed too early.

Impact:
=======

A malicious code exercizing the UMTX\\_SHM\\_DESTROY sub-request
in parallel can panic the kernel or enable further Use-After-Free
attacks, potentially including code execution or Capsicum sandbox
escape."""
affected = []
id = "FBSD-2024-0120"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-43102"

[[references]]
type = "ADVISORY"
url = "https://www.freebsd.org/security/advisories/FreeBSD-SA-24:14.umtx.asc"

[database_specific]
vid = "7e079ce2-6b51-11ef-9a62-002590c1f29c"
discovery = "2024-09-04T00:00:00Z"
