schema_version = "1.7.0"
modified = "2024-09-10T00:00:00Z"
published = "2024-09-10T00:00:00Z"
summary = "Intel CPUs -- multiple vulnerabilities"
details = """
Intel reports:

> A potential security vulnerability in some 4th and 5th Generation
> Intel Xeon Processors may allow denial of service. Intel released
> microcode updates to mitigate this potential vulnerability.

> Potential security vulnerabilities in some Intel Xeon processors using
> Intel Software Guard Extensions (Intel SGX) may allow escalation of
> privilege. Intel released firmware updates to mitigate these
> potential vulnerabilities."""
affected = []
id = "FBSD-2024-0052"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-21853"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-23918"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-21820"

[[references]]
type = "WEB"
url = "https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20241112"

[database_specific]
vid = "33236f80-a11d-11ef-a964-1c697a616631"
discovery = "2024-09-10T00:00:00Z"
