schema_version = "1.7.0"
modified = "2024-02-12T00:00:00Z"
published = "2024-02-12T00:00:00Z"
summary = "readstat -- Heap buffer overflow in readstat_convert"
details = """
Google reports:

> A heap buffer overflow exists in readstat\\_convert."""
references = [
    { type = "WEB", url = "https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33991" },
    { type = "WEB", url = "https://osv.dev/vulnerability/OSV-2021-732" },
    { type = "WEB", url = "https://github.com/WizardMac/ReadStat/issues/285" },
]
affected = []
id = "FBSD-2024-0297"

[database_specific]
vid = "388eefc0-c93f-11ee-92ce-4ccc6adda413"
discovery = "2021-05-05T00:00:00Z"
