schema_version = "1.7.0"
modified = "2025-08-02T00:00:00Z"
published = "2025-08-02T00:00:00Z"
summary = "sqlite -- integer overflow"
details = """
cve-coordination@google.com reports:

> An integer overflow can be triggered in SQLites `concat\\_ws()`
> function. The resulting, truncated integer is then used to allocate
> a buffer. When SQLite then writes the resulting string to the
> buffer, it uses the original, untruncated size and thus a wild Heap
> Buffer overflow of size ~4GB can be triggered. This can result in
> arbitrary code execution."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-3277" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-3277" },
]
id = "FBSD-2025-0010"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "linux-c7-sqlite"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.49.1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "linux_base-rl9"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.49.1" },
    { introduced = "0" },
]

[database_specific]
vid = "b945ce3f-6f9b-11f0-bd96-b42e991fc52e"
discovery = "2025-04-14T00:00:00Z"
