schema_version = "1.7.0"
modified = "2025-03-12T00:00:00Z"
published = "2025-03-12T00:00:00Z"
summary = "vim -- potential data loss with zip.vim and specially crafted zip files"
details = """
Vim reports:

> See https://github.com/vim/vim/security/advisories/GHSA-693p-m996-3rmf"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-29768" },
    { type = "WEB", url = "https://github.com/vim/vim/security/advisories/GHSA-693p-m996-3rmf" },
]
affected = []
id = "FBSD-2025-0199"

[database_specific]
vid = "9cf03c96-ffa5-11ef-bb15-002590af0794"
discovery = "2025-03-12T00:00:00Z"
