schema_version = "1.7.0"
modified = "2024-08-13T00:00:00Z"
published = "2024-08-13T00:00:00Z"
summary = "firefox -- multiple vulnerabilities"
details = """
security@mozilla.org reports:

> * CVE-2024-7531: Calling `PK11\\_Encrypt()` in NSS using
>   CKM\\_CHACHA20 and the same buffer for input and output can
>   result in plaintext on an Intel Sandy Bridge processor. In
>   Firefox this only affects the QUIC header protection
>   feature when the connection is using the ChaCha20-Poly1305
>   cipher suite. The most likely outcome is connection
>   failure, but if the connection persists despite the high
>   packet loss it could be possible for a network observer to
>   identify packets as coming from the same source despite a
>   network path change. This vulnerability affects Firefox
>   < 129, Firefox ESR < 115.14, and Firefox ESR <
>   128.1.
> * CVE-2024-7529: The date picker could partially obscure
>   security prompts. This could be used by a malicious site
>   to trick a user into granting permissions. This
>   vulnerability affects Firefox < 129, Firefox ESR <
>   115.14, Firefox ESR < 128.1, Thunderbird < 128.1,
>   and Thunderbird < 115.14.
> * CVE-2024-7525: It was possible for a web extension with
>   minimal permissions to create a `StreamFilter` which could
>   be used to read and modify the response body of requests
>   on any site. This vulnerability affects Firefox < 129,
>   Firefox ESR < 115.14, Firefox ESR < 128.1,
>   Thunderbird < 128.1, and Thunderbird < 115.14.
> * CVE-2024-7522: Editor code failed to check an attribute
>   value. This could have led to an out-of-bounds read. This
>   vulnerability affects Firefox < 129, Firefox ESR <
>   115.14, Firefox ESR < 128.1, Thunderbird < 128.1, and
>   Thunderbird < 115.14.
> * CVE-2024-7520: A type confusion bug in WebAssembly could
>   be leveraged by an attacker to potentially achieve code
>   execution. This vulnerability affects Firefox < 129,
>   Firefox ESR < 128.1, and Thunderbird < 128.1.
> * CVE-2024-7521: Incomplete WebAssembly exception handing
>   could have led to a use-after-free. This vulnerability
>   affects Firefox < 129, Firefox ESR < 115.14,
>   Firefox ESR < 128.1, Thunderbird < 128.1, and
>   Thunderbird < 115.14.
> * CVE-2024-7530: Incorrect garbage collection interaction
>   could have led to a use-after-free. This vulnerability
>   affects Firefox < 129.
> * CVE-2024-7528: Incorrect garbage collection interaction in
>   IndexedDB could have led to a use-after-free. This
>   vulnerability affects Firefox < 129,
>   Firefox ESR < 128.1, and Thunderbird < 128.1.
> * CVE-2024-7527: Unexpected marking work at the start of
>   sweeping could have led to a use-after-free. This
>   vulnerability affects Firefox < 129,
>   Firefox ESR < 115.14, Firefox ESR < 128.1,
>   Thunderbird < 128.1, and Thunderbird < 115.14."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-7531" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-7531" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-7529" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-7529" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-7525" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-7525" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-7522" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-7522" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-7520" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-7520" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-7521" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-7521" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-7530" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-7530" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-7528" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-7528" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-7527" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-7527" },
]
affected = []
id = "FBSD-2024-0144"

[database_specific]
vid = "5d7939f6-5989-11ef-9793-b42e991fc52e"
discovery = "2024-08-06T00:00:00Z"
