schema_version = "1.7.0"
modified = "2024-08-10T00:00:00Z"
published = "2024-08-10T00:00:00Z"
summary = "mozilla firefox -- protocol information guessing"
details = """
security@mozilla.org reports:

> By monitoring the time certain operations take, an attacker could
> have guessed which external protocol handlers were functional on a
> user's system. This vulnerability affects Firefox < 127,
> Firefox ESR < 115.12, and Thunderbird < 115.12."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-5690" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-5690" },
]
affected = []
id = "FBSD-2024-0149"

[database_specific]
vid = "aa1c7af9-570e-11ef-a43e-b42e991fc52e"
discovery = "2024-06-11T00:00:00Z"
