schema_version = "1.7.0"
modified = "2024-09-03T00:00:00Z"
published = "2024-09-03T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 4 security fixes:
>
> * [357391257] High CVE-2024-8362: Use after free in WebAudio. Reported by Cassidy Kim(@cassidy6564) on 2024-08-05
> * [358485426] High CVE-2024-7970: Out of bounds write in V8. Reported by Cassidy Kim(@cassidy6564) on 2024-08-09"""
id = "FBSD-2024-0126"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8362"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-7970"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2024/09/stable-channel-update-for-desktop.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.0.6613.119" },
    { introduced = "0" },
]

[database_specific]
vid = "26125e09-69ca-11ef-8a0f-a8a1599412c6"
discovery = "2024-09-02T00:00:00Z"
