schema_version = "1.7.0"
modified = "2024-03-17T00:00:00Z"
published = "2024-03-17T00:00:00Z"
summary = "amavisd-new -- multipart boundary confusion"
details = """
The Amavis project reports:

> Emails which consist of multiple parts (`Content-Type: multipart/\\*`)
> incorporate boundary information stating at which point one part ends and the
> next part begins.
>
> A boundary is announced by an Content-Type header's `boundary` parameter. To
> our current knowledge, RFC2046 and RFC2045 do not explicitly specify how a
> parser should handle multiple boundary parameters that contain conflicting
> values. As a result, there is no canonical choice which of the values should or
> should not be used for mime part decomposition."""
affected = []
id = "FBSD-2024-0266"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-28054"

[[references]]
type = "WEB"
url = "https://gitlab.com/amavis/amavis/-/raw/v2.12.3/README_FILES/README.CVE-2024-28054"

[database_specific]
vid = "0a48e552-e470-11ee-99b3-589cfc0f81b0"
discovery = "2024-03-14T00:00:00Z"
