schema_version = "1.7.0"
modified = "2025-07-02T00:00:00Z"
published = "2025-07-02T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 11 security fixes:
>
> * [407328533] Medium CVE-2025-6555: Use after free in Animation. Reported by Lyra Rebane (rebane2001) on 2025-03-30
> * [40062462] Low CVE-2025-6556: Insufficient policy enforcement in Loader. Reported by Shaheen Fazim on 2023-01-02
> * [406631048] Low CVE-2025-6557: Insufficient data validation in DevTools. Reported by Ameen Basha M K on 2025-03-27"""
id = "FBSD-2025-0063"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-6555"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-6556"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-6557"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2025/06/stable-channel-update-for-desktop_24.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "138.0.7204.49" },
    { introduced = "0" },
]

[database_specific]
vid = "9c91e1f8-f255-4b57-babe-2e385558f1dc"
discovery = "2025-06-24T00:00:00Z"
