schema_version = "1.7.0"
modified = "2024-06-10T00:00:00Z"
published = "2024-06-10T00:00:00Z"
summary = "Composer -- Multiple command injections via malicious git/hg branch names"
details = """
Composer project reports:

> The status, reinstall and remove commands with packages
> installed from source via git containing specially crafted
> branch names in the repository can be used to execute
> code.

> The composer install command running inside a git/hg
> repository which has specially crafted branch names can
> lead to command injection. So this requires cloning
> untrusted repositories."""
id = "FBSD-2024-0192"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-35241"

[[references]]
type = "WEB"
url = "https://github.com/composer/composer/security/advisories/GHSA-47f6-5gq3-vx9c"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-35242"

[[references]]
type = "WEB"
url = "https://github.com/composer/composer/security/advisories/GHSA-v9qv-c7wm-wgmf"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "php82-composer"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "2.7.7" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "php83-composer"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "2.7.7" },
    { introduced = "0" },
]

[database_specific]
vid = "5f608c68-276c-11ef-8caa-0897988a1c07"
discovery = "2024-06-10T00:00:00Z"
