schema_version = "1.7.0"
modified = "2024-01-22T00:00:00Z"
published = "2024-01-22T00:00:00Z"
summary = "zeek -- potential DoS vulnerability"
details = """
Tim Wojtulewicz of Corelight reports:

> A specially-crafted series of packets containing nested
> MIME entities can cause Zeek to spend large amounts of
> time parsing the entities."""
references = [
    { type = "WEB", url = "https://github.com/zeek/zeek/releases/tag/v6.0.3" },
]
affected = []
id = "FBSD-2024-0318"

[database_specific]
vid = "fedf7e71-61bd-49ec-aaf0-6da14bdbb319"
discovery = "2024-01-22T00:00:00Z"
