schema_version = "1.7.0"
modified = "2024-09-30T00:00:00Z"
published = "2024-09-30T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 5 security fixes:
>
> * [365254285] High CVE-2024-9120: Use after free in Dawn. Reported by Anonymous on 2024-09-08
> * [363538434] High CVE-2024-9121: Inappropriate implementation in V8. Reported by Tashita Software Security on 2024-09-01
> * [365802567] High CVE-2024-9122: Type Confusion in V8. Reported by Seunghyun Lee (@0x10n) on 2024-09-10
> * [365884464] High CVE-2024-9123: Integer overflow in Skia. Reported by raven at KunLun lab on 2024-09-11"""
id = "FBSD-2024-0091"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9120"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9121"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9122"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9123"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2024/09/stable-channel-update-for-desktop_24.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "129.0.6668.70" },
    { introduced = "0" },
]

[database_specific]
vid = "2f82696c-adad-447b-9938-c99441805fa3"
discovery = "2024-09-24T00:00:00Z"
