schema_version = "1.7.0"
modified = "2024-11-08T00:00:00Z"
published = "2024-11-08T00:00:00Z"
summary = "electron32 -- multiple vulnerabilities"
details = """
Electron developers report:

> This update fixes the following vulnerabilities:
>
> * Security: backported fix for CVE-2024-10230.
> * Security: backported fix for CVE-2024-10231.
> * Security: backported fix for CVE-2024-10229.
> * Security: backported fix for CVE-2024-10487."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-10230" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-g4gj-m346-585c" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-10231" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-3wfx-mj93-vf8v" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-10229" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-3hjp-j522-245f" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-10487" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-h72p-7xmw-gpp8" },
]
affected = []
id = "FBSD-2024-0057"

[database_specific]
vid = "96266fc9-1200-43b5-8393-4c51f54bb7bc"
discovery = "2024-11-08T00:00:00Z"
