schema_version = "1.7.0"
modified = "2025-05-11T00:00:00Z"
published = "2025-05-11T00:00:00Z"
summary = "Mozilla -- Cross-Site Request Forgery"
details = """
security@mozilla.org reports:

> A security vulnerability in Thunderbird allowed malicious
> sites to use redirects to send credentialed requests to
> arbitrary endpoints on any site that had invoked the Storage
> Access API. This enabled potential Cross-Site Request
> Forgery attacks across origins."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-4088" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-4088" },
]
id = "FBSD-2025-0133"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "138.0" },
    { introduced = "0" },
]

[database_specific]
vid = "a4422500-2e85-11f0-a989-b42e991fc52e"
discovery = "2025-04-29T00:00:00Z"
