schema_version = "1.7.0"
modified = "2024-03-28T00:00:00Z"
published = "2024-03-28T00:00:00Z"
summary = "Gitlab -- vulnerabilities"
details = """
Gitlab reports:

> Stored-XSS injected in Wiki page via Banzai pipeline
>
> DOS using crafted emojis"""
affected = []
id = "FBSD-2024-0257"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-6371"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2818"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2024/03/27/security-release-gitlab-16-10-1-released/"

[database_specific]
vid = "d2992bc2-ed18-11ee-96dc-001b217b3468"
discovery = "2024-03-27T00:00:00Z"
