schema_version = "1.7.0"
modified = "2025-03-20T00:00:00Z"
published = "2025-03-20T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 2 security fixes:
>
> * [401029609] Critical CVE-2025-2476: Use after free in Lens. Reported by SungKwon Lee of Enki Whitehat on 2025-03-05"""
id = "FBSD-2025-0195"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-2476"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2025/03/stable-channel-update-for-desktop_19.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "134.0.6998.117" },
    { introduced = "0" },
]

[database_specific]
vid = "9456d4e9-055f-11f0-85f3-a8a1599412c6"
discovery = "2025-03-19T00:00:00Z"
