schema_version = "1.7.0"
modified = "2024-09-26T00:00:00Z"
published = "2024-09-26T00:00:00Z"
summary = "Gitlab -- vulnerabilities"
details = """
Gitlab reports:

> Maintainer can leak Dependency Proxy password by changing Dependency Proxy URL via crafted POST request
>
> AI feature reads unsanitized content, allowing for attacker to hide prompt injection
>
> Project reference can be exposed in system notes"""
id = "FBSD-2024-0095"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4278"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4099"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8974"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2024/09/25/patch-release-gitlab-17-4-1-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.4.0" },
    { fixed = "17.4.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.3.0" },
    { fixed = "17.3.4" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "15.6.0" },
    { fixed = "17.2.8" },
]

[database_specific]
vid = "4b7ed61f-7bbf-11ef-9369-2cf05da270f3"
discovery = "2024-09-25T00:00:00Z"
