schema_version = "1.7.0"
modified = "2025-05-11T00:00:00Z"
published = "2025-05-11T00:00:00Z"
summary = "Mozilla -- XPath parsing undefined behavior"
details = """
security@mozilla.org reports:

> A vulnerability was identified in Thunderbird where XPath
> parsing could trigger undefined behavior due to missing null
> checks during attribute access. This could lead to
> out-of-bounds read access and potentially, memory
> corruption."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-4087" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-4087" },
]
id = "FBSD-2025-0134"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.10,1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "138" },
    { introduced = "0" },
]

[database_specific]
vid = "a2d5bd7b-2e85-11f0-a989-b42e991fc52e"
discovery = "2025-04-29T00:00:00Z"
