schema_version = "1.7.0"
modified = "2024-06-30T00:00:00Z"
published = "2024-06-30T00:00:00Z"
summary = "netatalk3 -- Multiple vulnerabilities"
details = """
cve@mitre.org reports:

> This entry documents the following three vulnerabilities:
>
> * Netatalk before 3.2.1 has an off-by-one error and resultant heap-based
>   buffer overflow because of setting ibuf[len] to '\\0' in
>   FPMapName in afp\\_mapname in etc/afpd/directory.c. 2.4.1 and 3.1.19
>   are also fixed versions.
> * Netatalk before 3.2.1 has an off-by-one error, and resultant
>   heap-based buffer overflow and segmentation violation, because of
>   incorrectly using FPLoginExt in BN\\_bin2bn in etc/uams/uams\\_dhx\\_pam.c.
>   The original issue 1097 report stated: 'The latest version of
>   Netatalk (v3.2.0) contains a security vulnerability. This vulnerability
>   arises due to a lack of validation for the length field after parsing
>   user-provided data, leading to an out-of-bounds heap write of one
>   byte (\\0). Under specific configurations, this can result in reading
>   metadata of the next heap block, potentially causing a Denial of
>   Service (DoS) under certain heap layouts or with ASAN enabled. ...
> * Netatalk before 3.2.1 has an off-by-one error and resultant heap-based
>   buffer overflow because of setting ibuf[PASSWDLEN] to '\\0'
>   in FPLoginExt in login in etc/uams/uams\\_pam.c. 2.4.1 and 3.1.19
>   are also fixed versions."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-38440" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-38440" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-38441" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-38441" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-38439" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-38439" },
]
affected = []
id = "FBSD-2024-0175"

[database_specific]
vid = "c742dbe8-3704-11ef-9e6e-b42e991fc52e"
discovery = "2024-06-16T00:00:00Z"
