schema_version = "1.7.0"
modified = "2024-07-26T00:00:00Z"
published = "2024-07-26T00:00:00Z"
summary = "Mailpit -- Content Security Policy XSS"
details = """
Mailpit developer reports:

> A vulnerability was discovered which allowed a bad
> actor with SMTP access to Mailpit to bypass the Content
> Security Policy headers using a series of crafted HTML
> messages which could result in a stored XSS attack via
> the web UI."""
references = [
    { type = "WEB", url = "https://github.com/axllent/mailpit/releases/tag/v1.19.3" },
]
affected = []
id = "FBSD-2024-0159"

[database_specific]
vid = "3e917407-4b3f-11ef-8e49-001999f8d30b"
discovery = "2024-07-26T00:00:00Z"
