schema_version = "1.7.0"
modified = "2024-06-15T00:00:00Z"
published = "2024-06-15T00:00:00Z"
summary = "go -- multiple vulnerabilities"
details = """
The Go project reports:

> archive/zip: mishandling of corrupt central directory record
>
> The archive/zip package's handling of certain types of
> invalid zip files differed from the behavior of most zip
> implementations. This misalignment could be exploited to
> create an zip file with contents that vary depending on the
> implementation reading the file. The archive/zip package now
> rejects files containing these errors.

> net/netip: unexpected behavior from Is methods for
> IPv4-mapped IPv6 addresses
>
> The various Is methods (IsPrivate, IsLoopback, etc) did
> not work as expected for IPv4-mapped IPv6 addresses,
> returning false for addresses which would return true in
> their traditional IPv4 forms."""
id = "FBSD-2024-0189"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-24789"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-24790"

[[references]]
type = "WEB"
url = "https://groups.google.com/g/golang-announce/c/XbxouI9gY7k/m/TuoGEhxIEwAJ"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "go121"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.21.11" },
    { introduced = "0" },
]

[database_specific]
vid = "a5c64f6f-2af3-11ef-a77e-901b0e9408dc"
discovery = "2024-06-04T00:00:00Z"
