schema_version = "1.7.0"
modified = "2024-02-11T00:00:00Z"
published = "2024-02-11T00:00:00Z"
summary = "phpmyfaq -- multiple vulnerabilities"
details = """
phpMyFAQ team reports:

> phpMyFAQ doesn't implement sufficient checks to avoid XSS when
> storing on attachments filenames. The 'sharing FAQ' functionality
> allows any unauthenticated actor to misuse the phpMyFAQ application
> to send arbitrary emails to a large range of targets. phpMyFAQ's
> user removal page allows an attacker to spoof another user's
> detail, and in turn make a compelling phishing case for removing
> another user's account."""
id = "FBSD-2024-0295"

[[references]]
type = "WEB"
url = "https://github.com/thorsten/phpMyFAQ/security/advisories/GHSA-7m8g-fprr-47fx"

[[references]]
type = "WEB"
url = "https://github.com/thorsten/phpMyFAQ/security/advisories/GHSA-9hhf-xmcw-r3xg"

[[references]]
type = "WEB"
url = "https://github.com/thorsten/phpMyFAQ/security/advisories/GHSA-6648-6g96-mg35"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "phpmyfaq-php82"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.2.5" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "phpmyfaq-php83"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.2.5" },
    { introduced = "0" },
]

[database_specific]
vid = "cbfc1591-c8c0-11ee-b45a-589cfc0f81b0"
discovery = "2024-02-05T00:00:00Z"
