schema_version = "1.7.0"
modified = "2024-03-09T00:00:00Z"
published = "2024-03-09T00:00:00Z"
summary = "Unbound -- Denial-of-Service vulnerability"
details = """
NLNet Labs reports:

> Unbound 1.18.0 introduced a feature that removes EDE records from
> responses with size higher than the client's advertised buffer size.
> Before removing all the EDE records however, it would try to see if
> trimming the extra text fields on those records would result in an
> acceptable size while still retaining the EDE codes. Due to an
> unchecked condition, the code that trims the text of the EDE records
> could loop indefinitely. This happens when Unbound would reply with
> attached EDE information on a positive reply and the client's buffer
> size is smaller than the needed space to include EDE records.
> The vulnerability can only be triggered when the 'ede: yes' option
> is used; non default configuration."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-1931" },
    { type = "WEB", url = "https://www.nlnetlabs.nl/downloads/unbound/CVE-2024-1931.txt" },
]
affected = []
id = "FBSD-2024-0271"

[database_specific]
vid = "c2ad8700-de25-11ee-9190-84a93843eb75"
discovery = "2024-03-07T00:00:00Z"
