schema_version = "1.7.0"
modified = "2024-09-20T00:00:00Z"
published = "2024-09-15T00:00:00Z"
summary = "OpenSSH -- Pre-authentication async signal safety issue"
details = """
The FreeBSD Project reports:

> A signal handler in sshd(8) may call a logging function that is not async-
> signal-safe. The signal handler is invoked when a client does not
> authenticate within the LoginGraceTime seconds (120 by default).
> This signal handler executes in the context of the sshd(8)'s privileged
> code, which is not sandboxed and runs with full root privileges.
>
> This issue is another instance of the problem in CVE-2024-6387 addressed by
> FreeBSD-SA-24:04.openssh. The faulty code in this case is from the
> integration of blacklistd in OpenSSH in FreeBSD."""
id = "FBSD-2024-0104"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-7589"

[[references]]
type = "ADVISORY"
url = "https://nvd.nist.gov/vuln/detail/CVE-2024-7589"

[[references]]
type = "ADVISORY"
url = "https://www.freebsd.org/security/advisories/FreeBSD-SA-24:08.openssh.asc"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "FreeBSD"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "14.1" },
    { fixed = "14.1_3" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "14.0" },
    { fixed = "14.0_9" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "13.3" },
    { fixed = "13.3_5" },
]

[database_specific]
vid = "58750d49-7302-11ef-8c95-195d300202b3"
discovery = "2024-08-06T00:00:00Z"
