schema_version = "1.7.0"
modified = "2024-10-19T00:00:00Z"
published = "2024-10-19T00:00:00Z"
summary = "OpenSSL -- OOB memory access vulnerability"
details = """
The OpenSSL project reports:

> Low-level invalid GF(2^m) parameters lead to OOB memory access
> (CVE-2024-9143) (Low)
>
> Use of the low-level GF(2^m) elliptic curve APIs with untrusted
> explicit values for the field polynomial can lead to out-of-bounds
> memory reads or writes."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9143" },
    { type = "WEB", url = "https://openssl-library.org/news/secadv/20241016.txt" },
]
id = "FBSD-2024-0074"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "openssl31"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.1.7_1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "openssl32"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.2.3_1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "openssl33"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.3.2_1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "openssl-quictls"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.0.15_1,1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "openssl31-quictls"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.1.7_1" },
    { introduced = "0" },
]

[database_specific]
vid = "c6f4177c-8e29-11ef-98e7-84a93843eb75"
discovery = "2024-10-16T00:00:00Z"
