schema_version = "1.7.0"
modified = "2025-08-14T00:00:00Z"
published = "2025-08-14T00:00:00Z"
summary = "PostgreSQL -- vulnerabilities"
details = """
PostgreSQL project reports:

> Tighten security checks in planner estimation functions.
>
> Prevent pg\\_dump scripts from being used to attack the user running the restore.
>
> Convert newlines to spaces in names included in comments in pg\\_dump output."""
id = "FBSD-2025-0003"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-8713"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-8714"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-8715"

[[references]]
type = "WEB"
url = "https://www.postgresql.org/about/news/postgresql-176-1610-1514-1419-1322-and-18-beta-3-released-3118/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql16-server"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "16.10" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql15-server"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "14.14" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql14-server"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "14.19" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "postgresql13-server"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "13.22" },
    { introduced = "0" },
]

[database_specific]
vid = "fc048b51-7909-11f0-90a2-6cc21735f730"
discovery = "2025-08-11T00:00:00Z"
