schema_version = "1.7.0"
modified = "2025-04-03T00:00:00Z"
published = "2025-04-03T00:00:00Z"
summary = "mozilla -- memory corruption"
details = """
security@mozilla.org reports:

> Memory safety bugs present in Firefox 135 and Thunderbird
> 135. Some of these bugs showed evidence of memory corruption
> and we presume that with enough effort some of these could
> have been exploited to run arbitrary code."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-1943" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-1943" },
]
id = "FBSD-2025-0177"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "librewolf"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "136.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "136.0" },
    { introduced = "0" },
]

[database_specific]
vid = "37c368f1-10a2-11f0-8195-b42e991fc52e"
discovery = "2025-03-04T00:00:00Z"
