schema_version = "1.7.0"
modified = "2024-05-21T00:00:00Z"
published = "2024-05-21T00:00:00Z"
summary = "Roundcube -- Cross-site scripting vulnerabilities"
details = """
The Roundcube project reports:

> cross-site scripting (XSS) vulnerability in handling SVG
> animate attributes.
>
> cross-site scripting (XSS) vulnerability in handling list
> columns from user preferences."""
affected = []
id = "FBSD-2024-0205"

[[references]]
type = "WEB"
url = "https://roundcube.net/news/2024/05/19/security-updates-1.6.7-and-1.5.7"

[database_specific]
vid = "e020b0fd-1751-11ef-a490-84a93843eb75"
discovery = "2024-05-19T00:00:00Z"
