schema_version = "1.7.0"
modified = "2025-04-04T00:00:00Z"
published = "2025-04-04T00:00:00Z"
summary = "firefox -- authentication bypass"
details = """
security@mozilla.org reports:

> Under certain circumstances, a user opt-in setting that
> Focus should require authentication before use could have
> been be bypassed."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0245" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-0245" },
]
id = "FBSD-2025-0170"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "librewolf"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "134.0" },
    { introduced = "0" },
]

[database_specific]
vid = "f7d80111-116c-11f0-8b2c-b42e991fc52e"
discovery = "2025-01-07T00:00:00Z"
