schema_version = "1.7.0"
modified = "2025-01-08T00:00:00Z"
published = "2025-01-08T00:00:00Z"
summary = "Gitlab -- Vulnerabilities"
details = """
Gitlab reports:

> Possible access token exposure in GitLab logs
>
> Cyclic reference of epics leads resource exhaustion
>
> Unauthorized user can manipulate status of issues in public projects
>
> Instance SAML does not respect external\\_provider configuration"""
id = "FBSD-2025-0264"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-0194"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-6324"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-12431"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-13041"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2025/01/08/patch-release-gitlab-17-7-1-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.7.0" },
    { fixed = "17.7.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.6.0" },
    { fixed = "17.6.3" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "11.0.0" },
    { fixed = "17.5.5" },
]

[database_specific]
vid = "2bfde261-cdf2-11ef-b6b2-2cf05da270f3"
discovery = "2025-01-08T00:00:00Z"
