schema_version = "1.7.0"
modified = "2025-03-10T00:00:00Z"
published = "2025-03-10T00:00:00Z"
summary = "vim -- Improper Input Validation in Vim"
details = """
security-advisories@github.com reports:

> Vim is distributed with the tar.vim plugin, that allows
> easy editing and viewing of (compressed or uncompressed) tar
> files. Starting with 9.1.0858, the tar.vim plugin uses the
> \":read\" ex command line to append below the
> cursor position, however the is not sanitized and is taken
> literally from the tar archive. This allows to execute
> shellcommands via special crafted tar archives. Whether
> this really happens, depends on the shell being used
> ('shell' option, which is set using $SHELL)."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-27423" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-27423" },
]
id = "FBSD-2025-0202"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "vim-gtk2"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "9.1.1164" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "vim-gtk3"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "9.1.1164" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "vim-motif"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "9.1.1164" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "vim-tiny"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "9.1.1164" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "vim-x11"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "9.1.1164" },
    { introduced = "0" },
]

[database_specific]
vid = "2ec7816d-fdb7-11ef-91ff-b42e991fc52e"
discovery = "2025-03-03T00:00:00Z"
