schema_version = "1.7.0"
modified = "2024-11-12T00:00:00Z"
published = "2024-09-10T00:00:00Z"
summary = "Intel CPUs -- multiple vulnerabilities"
details = """
Intel reports:

> A potential security vulnerability in the Running Average Power Limit
> (RAPL) interface for some Intel Processors may allow information
> disclosure. Intel has released firmware updates to mitigate this
> potential vulnerability.

> A potential security vulnerability in some Intel Processors may allow
> denial of service. Intel has released firmware updates to mitigate
> this potential vulnerability."""
affected = []
id = "FBSD-2024-0108"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-23984"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-24968"

[[references]]
type = "WEB"
url = "https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20240910"

[database_specific]
vid = "d5026193-6fa2-11ef-99bc-1c697a616631"
discovery = "2024-09-10T00:00:00Z"
