schema_version = "1.7.0"
modified = "2025-02-13T00:00:00Z"
published = "2025-02-13T00:00:00Z"
summary = "Gitlab -- Vulnerabilities"
details = """
Gitlab reports:

> A CSP-bypass XSS in merge-request page
>
> Denial of Service due to Unbounded Symbol Creation
>
> Exfiltrate content from private issues using Prompt Injection
>
> A custom permission may allow overriding Repository settings
>
> Internal HTTP header leak via route confusion in workhorse
>
> SSRF via workspaces
>
> Unauthorized Incident Closure and Deletion by Planner Role in GitLab
>
> ActionCable does not invalidate tokens after revocation"""
id = "FBSD-2025-0227"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-0376"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-12379"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-3303"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-1042"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-1212"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9870"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-0516"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-1198"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2025/02/12/patch-release-gitlab-17-8-2-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.8.0" },
    { fixed = "17.8.2" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.7.0" },
    { fixed = "17.7.4" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "8.3.0" },
    { fixed = "17.6.5" },
]

[database_specific]
vid = "1a8c5720-e9cf-11ef-9e96-2cf05da270f3"
discovery = "2025-02-12T00:00:00Z"
