schema_version = "1.7.0"
modified = "2025-04-03T00:00:00Z"
published = "2025-04-03T00:00:00Z"
summary = "mozilla -- Memory safety bugs"
details = """
security@mozilla.org reports:

> Memory safety bugs present in Firefox 135, Thunderbird 135,
> Firefox ESR 115.20, Firefox ESR 128.7, and Thunderbird 128.7.
> Some of these bugs showed evidence of memory corruption and
> we presume that with enough effort some of these could have
> been exploited to run arbitrary code."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-1937" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-1937" },
]
id = "FBSD-2025-0179"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "librewolf"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "136.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "115.21,1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "136.0" },
    { introduced = "0" },
]

[database_specific]
vid = "aeb2ca87-109d-11f0-8195-b42e991fc52e"
discovery = "2025-03-04T00:00:00Z"
