schema_version = "1.7.0"
modified = "2025-07-18T00:00:00Z"
published = "2025-07-18T00:00:00Z"
summary = "unbound -- Cache poisoning via the ECS-enabled Rebirthday Attack"
details = """
sep@nlnetlabs.nl reports:

> A multi-vendor cache poisoning vulnerability named 'Rebirthday
> Attack' has been discovered in caching resolvers that support
> EDNS Client Subnet (ECS). Unbound is also vulnerable when compiled
> with ECS support, i.e., '--enable-subnet', AND configured
> to send ECS information along with queries to upstream name servers,
> i.e., at least one of the 'send-client-subnet',
> 'client-subnet-zone' or 'client-subnet-always-forward'
> options is used. Resolvers supporting ECS need to segregate outgoing
> queries to accommodate for different outgoing ECS information. This
> re-opens up resolvers to a birthday paradox attack (Rebirthday
> Attack) that tries to match the DNS transaction ID in order to cache
> non-ECS poisonous replies."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-5994" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-5994" },
]
affected = []
id = "FBSD-2025-0037"

[database_specific]
vid = "e27ee4fc-cdc9-45a1-8242-09898cdbdc91"
discovery = "2025-07-16T00:00:00Z"
