schema_version = "1.7.0"
modified = "2025-07-06T00:00:00Z"
published = "2025-07-06T00:00:00Z"
summary = "gstreamer1-plugins-bad -- stack buffer overflow in H.266 video parser"
details = """
GStreamer Security Center reports:

> It is possible for a malicious third party to trigger a buffer overflow that can
> result in a crash of the application and possibly also allow code execution through
> stack manipulation."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-6663" },
    { type = "WEB", url = "https://gstreamer.freedesktop.org/security/sa-2025-0007.html" },
]
affected = []
id = "FBSD-2025-0056"

[database_specific]
vid = "69bfe2a4-5a39-11f0-8792-4ccc6adda413"
discovery = "2025-06-26T00:00:00Z"
