schema_version = "1.7.0"
modified = "2024-10-26T00:00:00Z"
published = "2024-10-26T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 17 security fixes:
>
> * [367755363] High CVE-2024-9954: Use after free in AI. Reported by DarkNavy on 2024-09-18
> * [370133761] Medium CVE-2024-9955: Use after free in Web Authentication. Reported by anonymous on 2024-09-29
> * [370482421] Medium CVE-2024-9956: Inappropriate implementation in Web Authentication. Reported by mastersplinter on 2024-09-30
> * [358151317] Medium CVE-2024-9957: Use after free in UI. Reported by lime(@limeSec\\_) and fmyy(@binary\\_fmyy) From TIANGONG Team of Legendsec at QI-ANXIN Group on 2024-08-08
> * [40076120] Medium CVE-2024-9958: Inappropriate implementation in PictureInPicture. Reported by Lyra Rebane (rebane2001) on 2023-11-02
> * [368672129] Medium CVE-2024-9959: Use after free in DevTools. Reported by Sakana.S on 2024-09-21
> * [354748063] Medium CVE-2024-9960: Use after free in Dawn. Reported by Anonymous on 2024-07-23
> * [357776197] Medium CVE-2024-9961: Use after free in Parcel Tracking. Reported by lime(@limeSec\\_) and fmyy(@binary\\_fmyy) From TIANGONG Team of Legendsec at QI-ANXIN Group on 2024-08-06
> * [364508693] Medium CVE-2024-9962: Inappropriate implementation in Permissions. Reported by Shaheen Fazim on 2024-09-04
> * [328278718] Medium CVE-2024-9963: Insufficient data validation in Downloads. Reported by Anonymous on 2024-03-06
> * [361711121] Low CVE-2024-9964: Inappropriate implementation in Payments. Reported by Hafiizh on 2024-08-23
> * [352651673] Low CVE-2024-9965: Insufficient data validation in DevTools. Reported by Shaheen Fazim on 2024-07-12
> * [364773822] Low CVE-2024-9966: Inappropriate implementation in Navigations. Reported by Harry Chen on 2024-09-05"""
id = "FBSD-2024-0068"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9954"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9955"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9956"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9957"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9958"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9959"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9960"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9961"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9962"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9963"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9964"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9965"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9966"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2024/10/stable-channel-update-for-desktop_15.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "130.0.6723.58" },
    { introduced = "0" },
]

[database_specific]
vid = "1e71e366-080b-4e8f-a9e6-150bf698186b"
discovery = "2024-10-15T00:00:00Z"
