schema_version = "1.7.0"
modified = "2024-09-06T00:00:00Z"
published = "2024-09-06T00:00:00Z"
summary = "forgejo -- multiple vulnerabilities"
details = """
Problem Description:
====================

* Replace v-html with v-text in search inputbox
* Upgrade webpack to v5.94.0 as a precaution to mitigate
  CVE-2024-43788, although we were not yet able to confirm that this
  can be exploited in Forgejo."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-43788" },
    { type = "WEB", url = "https://codeberg.org/forgejo/forgejo/milestone/8231" },
]
id = "FBSD-2024-0115"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "forgejo7"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "7.0.9" },
    { introduced = "0" },
]

[database_specific]
vid = "a5e13973-6c75-11ef-858b-23eeba13701a"
discovery = "2024-09-03T00:00:00Z"
