schema_version = "1.7.0"
modified = "2025-06-20T00:00:00Z"
published = "2025-06-20T00:00:00Z"
summary = "clamav -- ClamAV UDF File Parsing Out-Of-Bounds Read Information Disclosure Vulnerability"
details = """
Cisco reports:

> A vulnerability in Universal Disk Format (UDF) processing of ClamAV
> could allow an unauthenticated, remote attacker to cause a denial
> of service (DoS) condition on an affected device.
> This vulnerability is due to a memory overread during UDF file
> scanning. An attacker could exploit this vulnerability by submitting
> a crafted file containing UDF content to be scanned by ClamAV on
> an affected device. A successful exploit could allow the attacker
> to terminate the ClamAV scanning process, resulting in a DoS condition
> on the affected software. For a description of this vulnerability,
> see the ."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-20234" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-20234" },
]
affected = []
id = "FBSD-2025-0075"

[database_specific]
vid = "6c6c1507-4da5-11f0-afcc-f02f7432cf97"
discovery = "2025-06-18T00:00:00Z"
