schema_version = "1.7.0"
modified = "2024-04-11T00:00:00Z"
published = "2024-04-11T00:00:00Z"
summary = "forgejo -- multiple issues"
details = """
The forgejo team reports:

> [CVE-2024-24789](https://pkg.go.dev/vuln/GO-2024-2888):
> The archive/zip package's handling of certain types of invalid
> zip files differs from the behavior of most zip implementations.
> This misalignment could be exploited to create an zip file with
> contents that vary depending on the implementation reading the
> file.
>
> The OAuth2 implementation does not always require authentication
> for public clients, a requirement of RFC 6749 Section 10.2. A
> malicious client can impersonate another client and obtain access
> to protected resources if the impersonated client fails to, or is
> unable to, keep its client credentials confidential."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-24789" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-24789" },
]
affected = []
id = "FBSD-2024-0187"

[database_specific]
vid = "f0ba7008-2bbd-11ef-b4ca-814a3d504243"
discovery = "2024-04-04T00:00:00Z"
