schema_version = "1.7.0"
modified = "2024-03-06T00:00:00Z"
published = "2024-03-06T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 3 security fixes:
>
> * [325893559] High CVE-2024-2173: Out of bounds memory access in V8. Reported by 5fceb6172bbf7e2c5a948183b53565b9 on 2024-02-19
> * [325866363] High CVE-2024-2174: Inappropriate implementation in V8. Reported by 5f46f4ee2e17957ba7b39897fb376be8 on 2024-02-19
> * [325936438] High CVE-2024-2176: Use after free in FedCM. Reported by Anonymous on 2024-02-20"""
id = "FBSD-2024-0275"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2173"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2174"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2176"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2024/03/stable-channel-update-for-desktop.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "122.0.6261.111" },
    { introduced = "0" },
]

[database_specific]
vid = "fd3401a1-b6df-4577-917a-2c22fee99d34"
discovery = "2024-03-05T00:00:00Z"
