schema_version = "1.7.0"
modified = "2025-05-22T00:00:00Z"
published = "2025-05-22T00:00:00Z"
summary = "Firefox -- memory corruption due to race condition"
details = """
security@mozilla.org reports:

> A race condition existed in nsHttpTransaction that could
> have been exploited to cause memory corruption, potentially
> leading to an exploitable condition."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-3608" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-3608" },
]
affected = []
id = "FBSD-2025-0120"

[database_specific]
vid = "6529e5e7-36d5-11f0-8f57-b42e991fc52e"
discovery = "2025-04-15T00:00:00Z"
