schema_version = "1.7.0"
modified = "2025-03-06T00:00:00Z"
published = "2025-03-06T00:00:00Z"
summary = "Jinja2 -- Sandbox breakout through attr filter selecting format method"
details = """
security-advisories@github.com reports:

> Jinja is an extensible templating engine. Prior to 3.1.6, an
> oversight in how the Jinja sandboxed environment interacts with the
> |attr filter allows an attacker that controls the content of a
> template to execute arbitrary Python code. To exploit the
> vulnerability, an attacker needs to control the content of a template.
> Whether that is the case depends on the type of application using
> Jinja. This vulnerability impacts users of applications which
> execute untrusted templates. Jinja's sandbox does catch calls
> to str.format and ensures they don't escape the sandbox.
> However, it's possible to use the |attr filter to get a reference
> to a string's plain format method, bypassing the sandbox.
> After the fix, the |attr filter no longer bypasses the environment's
> attribute lookup. This vulnerability is fixed in 3.1.6."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-27516" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-27516" },
]
id = "FBSD-2025-0205"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py39-Jinja2"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.1.6" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py310-Jinja2"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.1.6" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py311-Jinja2"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.1.6" },
    { introduced = "0" },
]

[database_specific]
vid = "3299cbfd-fa6e-11ef-929d-b0416f0c4c67"
discovery = "2025-03-05T00:00:00Z"
