schema_version = "1.7.0"
modified = "2024-09-05T00:00:00Z"
published = "2024-09-05T00:00:00Z"
summary = "gitea -- multiple issues"
details = """
Problem Description:
====================

* Replace v-html with v-text in search inputbox
* Fix nuget/conan/container packages upload bugs"""
references = [
    { type = "WEB", url = "https://github.com/go-gitea/gitea/releases/tag/v1.22.2" },
]
affected = []
id = "FBSD-2024-0117"

[database_specific]
vid = "f5d0cfe7-6ba6-11ef-858b-23eeba13701a"
discovery = "2024-09-03T00:00:00Z"
