schema_version = "1.7.0"
modified = "2024-09-07T00:00:00Z"
published = "2024-09-07T00:00:00Z"
summary = "firefox -- Potential memory corruption and exploitable crash"
details = """
security@mozilla.org reports:

> An error in the ECMA-262 specification relating to Async Generators
> could have resulted in a type confusion, potentially leading to
> memory corruption and an exploitable crash."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-7652" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-7652" },
]
affected = []
id = "FBSD-2024-0113"

[database_specific]
vid = "7ade3c38-6d1f-11ef-ae11-b42e991fc52e"
discovery = "2024-09-06T00:00:00Z"
