schema_version = "1.7.0"
modified = "2025-06-05T00:00:00Z"
published = "2025-06-05T00:00:00Z"
summary = "Mozilla -- clickjacking vulnerability"
details = """
security@mozilla.org reports:

> A clickjacking vulnerability could have been used to trick a user
> into leaking saved payment card details to a malicious page."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-5267" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-5267" },
]
id = "FBSD-2025-0092"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "139.0,2" },
    { introduced = "0" },
]

[database_specific]
vid = "63268efe-4222-11f0-976e-b42e991fc52e"
discovery = "2025-05-27T00:00:00Z"
