schema_version = "1.7.0"
modified = "2025-06-17T00:00:00Z"
published = "2025-06-17T00:00:00Z"
summary = "Firefox -- Multiple vulnerabilities"
details = """
security@mozilla.org reports:

> CVE-2025-49709: Certain canvas operations could have lead
> to memory corruption.
>
> CVE-2025-49710: An integer overflow was present in
> `OrderedHashTable` used by the JavaScript engine."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-49709" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-49709" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-49710" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-49710" },
]
affected = []
id = "FBSD-2025-0081"

[database_specific]
vid = "b704d4b8-4b87-11f0-9605-b42e991fc52e"
discovery = "2025-06-11T00:00:00Z"
