schema_version = "1.7.0"
modified = "2025-04-07T00:00:00Z"
published = "2025-04-07T00:00:00Z"
summary = "Mozilla -- use-after-free error"
details = """
security@mozilla.org reports:

> JavaScript code running while transforming a document
> with the XSLTProcessor could lead to a use-after-free."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-3028" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-3028" },
]
id = "FBSD-2025-0166"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "115.22" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "librewolf"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "137.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "137.0" },
    { introduced = "0" },
]

[database_specific]
vid = "28e5f7be-13c8-11f0-a5bd-b42e991fc52e"
discovery = "2025-04-01T00:00:00Z"
