schema_version = "1.7.0"
modified = "2024-02-15T00:00:00Z"
published = "2024-02-15T00:00:00Z"
summary = "nginx-devel -- Multiple Vulnerabilities in HTTP/3"
details = """
The nginx development team reports:

> When using HTTP/3 a segmentation fault might occur in a
> worker process while processing a specially crafted QUIC session."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-24989" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-24990" },
]
affected = []
id = "FBSD-2024-0290"

[database_specific]
vid = "c97a4ecf-cc25-11ee-b0ee-0050569f0b83"
discovery = "2024-02-14T00:00:00Z"
