schema_version = "1.7.0"
modified = "2025-01-23T00:00:00Z"
published = "2025-01-23T00:00:00Z"
summary = "Gitlab -- Vulnerabilities"
details = """
Gitlab reports:

> Stored XSS via Asciidoctor render
>
> Developer could exfiltrate protected CI/CD variables via CI lint
>
> Cyclic reference of epics leads resource exhaustion"""
id = "FBSD-2025-0251"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-0314"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-11931"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-6324"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2025/01/22/patch-release-gitlab-17-8-1-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.8.0" },
    { fixed = "17.8.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.7.0" },
    { fixed = "17.7.3" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "15.7.0" },
    { fixed = "17.6.4" },
]

[database_specific]
vid = "24c93a28-d95b-11ef-b6b2-2cf05da270f3"
discovery = "2025-01-22T00:00:00Z"
