schema_version = "1.7.0"
modified = "2025-07-07T00:00:00Z"
published = "2025-07-07T00:00:00Z"
summary = "redis,valkey -- Out of bounds write in hyperloglog commands leads to RCE"
details = """
Seunghyun Lee reports:

> An authenticated user may use a specially crafted string
> to trigger a stack/heap out of bounds write on hyperloglog
> operations, potentially leading to remote code execution."""
id = "FBSD-2025-0053"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-32023"

[[references]]
type = "WEB"
url = "https://github.com/redis/redis/security/advisories/GHSA-rp2m-q4j6-gr43"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "redis74"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "7.4.0" },
    { fixed = "7.4.5" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "redis72"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "7.2.0" },
    { fixed = "7.2.10" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "redis62"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "6.2.0" },
    { fixed = "6.2.19" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "valkey"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "8.1.3" },
    { introduced = "0" },
]

[database_specific]
vid = "f11d0a69-5b2d-11f0-b507-000c295725e4"
discovery = "2025-07-06T00:00:00Z"
