schema_version = "1.7.0"
modified = "2025-04-07T00:00:00Z"
published = "2025-04-07T00:00:00Z"
summary = "Mozilla -- stack memory read"
details = """
security@mozilla.org reports:

> An attacker could read 32 bits of values spilled onto the stack in
> a JIT compiled function."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-3031" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-3031" },
]
id = "FBSD-2025-0163"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "librewolf"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "137.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "137.0" },
    { introduced = "0" },
]

[database_specific]
vid = "2fc74cae-13c8-11f0-a5bd-b42e991fc52e"
discovery = "2025-04-01T00:00:00Z"
