schema_version = "1.7.0"
modified = "2024-08-12T00:00:00Z"
published = "2024-08-12T00:00:00Z"
summary = "Vaultwarden -- Multiple vulnerabilities"
details = """
SO-AND-SO reports:

> This release has several CVE Reports fixed and we recommend
> everybody to update to the latest version as soon as possible."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-39924" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-39925" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-39926" },
    { type = "WEB", url = "https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.0" },
]
affected = []
id = "FBSD-2024-0146"

[database_specific]
vid = "d2723b0f-58d9-11ef-b611-84a93843eb75"
discovery = "2024-08-11T00:00:00Z"
