schema_version = "1.7.0"
modified = "2024-01-04T00:00:00Z"
published = "2024-01-04T00:00:00Z"
summary = "electron26 -- multiple vulnerabilities"
details = """
Electron developers report:

> This update fixes the following vulnerabilities:
>
> * Security: backported fix for CVE-2023-6704.
> * Security: backported fix for CVE-2023-6705.
> * Security: backported fix for CVE-2023-6703.
> * Security: backported fix for CVE-2023-6702."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2023-6704" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-587x-fmc5-99p9" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2023-6705" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-h27f-fw5q-c2gh" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2023-6703" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-9v72-359m-2vx4" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2023-6702" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-7hjc-c62g-4w73" },
]
affected = []
id = "FBSD-2024-0331"

[database_specific]
vid = "0cee4f9c-5efb-4770-b917-f4e4569e8bec"
discovery = "2024-01-04T00:00:00Z"
