schema_version = "1.7.0"
modified = "2024-01-12T00:00:00Z"
published = "2024-01-12T00:00:00Z"
summary = "electron{26,27} -- multiple vulnerabilities"
details = """
Electron developers report:

> This update fixes the following vulnerabilities:
>
> * Security: backported fix for CVE-2024-0224.
> * Security: backported fix for CVE-2024-0225.
> * Security: backported fix for CVE-2024-0223.
> * Security: backported fix for CVE-2024-0222."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-0224" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-83wx-v283-85g9" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-0225" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-gqr9-4fcc-c9jq" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-0223" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-w8x8-g534-x4rp" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-0222" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-c87c-56pw-mwgh" },
]
id = "FBSD-2024-0323"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "electron27"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "27.2.2" },
    { introduced = "0" },
]

[database_specific]
vid = "28b42ef5-80cd-440c-904b-b7fbca74c73d"
discovery = "2024-01-10T00:00:00Z"
