schema_version = "1.7.0"
modified = "2024-02-14T00:00:00Z"
published = "2024-02-08T00:00:00Z"
summary = "Libgit2 -- multiple vulnerabilities"
details = """
Git community reports:

> A bug in git\\_revparse\\_single is fixed that could have caused the function to enter an infinite loop given well-crafted inputs, potentially causing a Denial of Service attack in the calling application
>
> A bug in git\\_revparse\\_single is fixed that could have caused the function to enter an infinite loop given well-crafted inputs, potentially causing a Denial of Service attack in the calling application
>
> A bug in the smart transport negotiation could have caused an out-of-bounds read when a remote server did not advertise capabilities"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-24577" },
    { type = "WEB", url = "https://github.com/libgit2/libgit2/releases/tag/v1.7.2" },
]
id = "FBSD-2024-0302"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "libgit2"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "1.7.0" },
    { fixed = "1.7.2" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.6.5" },
    { introduced = "0" },
]

[database_specific]
vid = "43768ff3-c683-11ee-97d0-001b217b3468"
discovery = "2024-02-06T00:00:00Z"
