schema_version = "1.7.0"
modified = "2025-07-14T00:00:00Z"
published = "2025-07-14T00:00:00Z"
summary = "GnuTLS -- multiple vulnerabilities"
details = """
Daiki Ueno reports:

> * libgnutls: Fix heap read buffer overrun in parsing X.509 SCTS timestamps
>   Spotted by oss-fuzz and reported by OpenAI Security Research Team,
>   and fix developed by Andrew Hamilton. [GNUTLS-SA-2025-07-07-1,
>   CVSS: medium] [CVE-2025-32989]
> * libgnutls: Fix double-free upon error when exporting otherName in SAN
>   Reported by OpenAI Security Research Team. [GNUTLS-SA-2025-07-07-2,
>   CVSS: low] [CVE-2025-32988]
> * certtool: Fix 1-byte write buffer overrun when parsing template
>   Reported by David Aitel. [GNUTLS-SA-2025-07-07-3,
>   CVSS: low] [CVE-2025-32990]
> * libgnutls: Fix NULL pointer dereference when 2nd Client Hello omits PSK
>   Reported by Stefan Bühler. [GNUTLS-SA-2025-07-07-4, CVSS: medium]
>   [CVE-2025-6395]"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-32989" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-32988" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-32990" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-6395" },
    { type = "WEB", url = "https://lists.gnupg.org/pipermail/gnutls-help/2025-July/004883.html" },
]
affected = []
id = "FBSD-2025-0039"

[database_specific]
vid = "c3e1df74-5e73-11f0-95e5-74563cf9e4e9"
discovery = "2025-07-09T00:00:00Z"
