schema_version = "1.7.0"
modified = "2024-05-08T00:00:00Z"
published = "2024-05-08T00:00:00Z"
summary = "electron29 -- multiple vulnerabilities"
details = """
Electron developers report:

> This update fixes the following vulnerabilities:
>
> * Security: backported fix for CVE-2024-4060.
> * Security: backported fix for CVE-2024-4058."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-4060" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-4qw6-vwc8-mh38" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-4058" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-23rw-79p3-xgcm" },
]
affected = []
id = "FBSD-2024-0221"

[database_specific]
vid = "059a99a9-45e0-492b-b9f9-5a79573c8eb6"
discovery = "2024-05-03T00:00:00Z"
