schema_version = "1.7.0"
modified = "2024-11-12T00:00:00Z"
published = "2024-11-12T00:00:00Z"
summary = "icinga2 -- TLS Certificate Validation Bypass"
details = """
The Icinga project reports:

> Icinga is a monitoring system which checks the availability of
> network resources, notifies users of outages, and generates performance
> data for reporting. The TLS certificate validation in all Icinga
> 2 versions starting from 2.4.0 was flawed, allowing an attacker to
> impersonate both trusted cluster nodes as well as any API users
> that use TLS client certificates for authentication (ApiUser objects
> with the client\\_cn attribute set). This vulnerability has been
> fixed in v2.14.3, v2.13.10, v2.12.11, and v2.11.12."""
affected = []
id = "FBSD-2024-0051"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-49369"

[[references]]
type = "WEB"
url = "https://icinga.com/blog/2024/11/12/critical-icinga-2-security-releases-2-14-3/"

[[references]]
type = "ADVISORY"
url = "https://nvd.nist.gov/vuln/detail/CVE-2024-49369"

[database_specific]
vid = "0a82bc4d-a129-11ef-8351-589cfc0f81b0"
discovery = "2024-11-12T00:00:00Z"
