schema_version = "1.7.0"
modified = "2025-07-08T00:00:00Z"
published = "2025-07-08T00:00:00Z"
summary = "MongoDB -- Incorrect Handling of incomplete data may prevent mongoS from Accepting New Connections"
details = """
cna@mongodb.com reports:

> MongoDB Server's mongos component can become
> unresponsive to new connections due to incorrect handling of
> incomplete data. This affects MongoDB when configured with
> load balancer support.
> Required Configuration:
> This affects MongoDB sharded clusters when configured with load
> balancer support for mongos using HAProxy on specified ports."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-6714" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-6714" },
]
id = "FBSD-2025-0047"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "mongodb70"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "7.0.20" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "mongodb80"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "8.0.9" },
    { introduced = "0" },
]

[database_specific]
vid = "79251dc8-5bc5-11f0-834f-b42e991fc52e"
discovery = "2025-07-07T00:00:00Z"
