schema_version = "1.7.0"
modified = "2025-07-24T00:00:00Z"
published = "2025-07-24T00:00:00Z"
summary = "gdk-pixbuf2 -- a heap buffer overflow"
details = """
cve@mitre.org reports:

> A flaw exists in gdk-pixbuf within the gdk\\_pixbuf\\_\\_jpeg\\_image\\_load\\_increment
> function (io-jpeg.c) and in glib’s g\\_base64\\_encode\\_step (glib/gbase64.c).
> When processing maliciously crafted JPEG images, a heap buffer overflow can occur
> during Base64 encoding, allowing out-of-bounds reads from heap memory, potentially
> causing application crashes or arbitrary code execution."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-7345" },
    { type = "WEB", url = "https://www.cve.org/CVERecord?id=CVE-2025-7345" },
]
affected = []
id = "FBSD-2025-0031"

[database_specific]
vid = "3d4393b2-68a5-11f0-b2b4-589cfc10832a"
discovery = "2025-07-24T00:00:00Z"
