schema_version = "1.7.0"
modified = "2024-12-06T00:00:00Z"
published = "2024-12-06T00:00:00Z"
summary = "gstreamer1-plugins-jpeg -- NULL-pointer dereferences in JPEG decoder"
details = """
The GStreamer Security Center reports:

> Insufficient error handling in the JPEG decoder that can lead to
> NULL-pointer dereferences, and that can cause crashes for certain
> input files."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-47599" },
    { type = "WEB", url = "https://gstreamer.freedesktop.org/security/sa-2024-0016.html" },
]
affected = []
id = "FBSD-2024-0022"

[database_specific]
vid = "7945c543-b3e8-11ef-b680-4ccc6adda413"
discovery = "2024-12-03T00:00:00Z"
