schema_version = "1.7.0"
modified = "2025-02-27T00:00:00Z"
published = "2025-02-27T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 1 security fix."""
id = "FBSD-2025-0215"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2025/02/stable-channel-update-for-desktop_25.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "133.0.6943.141" },
    { introduced = "0" },
]

[database_specific]
vid = "a4cb7f9b-f506-11ef-85f3-a8a1599412c6"
discovery = "2025-02-25T00:00:00Z"
