schema_version = "1.7.0"
modified = "2024-09-24T00:00:00Z"
published = "2024-09-24T00:00:00Z"
summary = "zeek -- potential DoS vulnerability"
details = """
Tim Wojtulewicz of Corelight reports:

> The POP3 parser has been hardened to avoid unbounded
> state growth in the face of one-sided traffic capture or
> when enabled for non-POP3 traffic."""
references = [
    { type = "WEB", url = "https://github.com/zeek/zeek/releases/tag/v7.0.2" },
]
affected = []
id = "FBSD-2024-0097"

[database_specific]
vid = "d47b7ae7-fe1d-4f7f-919a-480ca8035f00"
discovery = "2024-09-24T00:00:00Z"
