schema_version = "1.7.0"
modified = "2025-02-13T00:00:00Z"
published = "2025-02-13T00:00:00Z"
summary = "vscode -- multiple vulnerabilities"
details = """
VSCode developers report:

> The update addresses these issues, including a fix for a security vulnerability.
>
> * Scope node\\_module binary resolution in js-debug
> * Elevation of Privilege Vulnerability with VS Code server for web UI"""
affected = []
id = "FBSD-2025-0224"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-24042"

[[references]]
type = "WEB"
url = "https://github.com/microsoft/vscode/security/advisories/GHSA-f85p-3684-2g3j"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-24039"

[[references]]
type = "WEB"
url = "https://github.com/microsoft/vscode/security/advisories/GHSA-532g-4pv9-25f2"

[database_specific]
vid = "cbf5d976-656b-4bb6-805f-3af038e2de3e"
discovery = "2025-02-11T00:00:00Z"
