schema_version = "1.7.0"
modified = "2025-06-18T00:00:00Z"
published = "2025-06-18T00:00:00Z"
summary = "Navidrome -- SQL Injection via role parameter"
details = """
Deluan reports:

> This vulnerability arises due to improper input validation on the role parameter within the API endpoint /api/artist. Attackers can exploit this flaw to inject arbitrary SQL queries, potentially gaining unauthorized access to the backend database and compromising sensitive user information."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-48949" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-48949" },
]
affected = []
id = "FBSD-2025-0078"

[database_specific]
vid = "fc2d2fb8-4c83-11f0-8deb-f8f21e52f724"
discovery = "2025-05-29T00:00:00Z"
