schema_version = "1.7.0"
modified = "2025-07-08T00:00:00Z"
published = "2025-07-08T00:00:00Z"
summary = "ModSecurity -- empty XML tag causes segmentation fault"
details = """
security-advisories@github.com reports:

> ModSecurity is an open source, cross platform web application
> firewall (WAF) engine for Apache, IIS and Nginx. In versions 2.9.8
> to before 2.9.11, an empty XML tag can cause a segmentation fault.
> If SecParseXmlIntoArgs is set to On or OnlyArgs, and the request
> type is application/xml, and at least one XML tag is empty (eg
> <foo></foo>), then a segmentation fault occurs. This
> issue has been patched in version 2.9.11. A workaround involves
> setting SecParseXmlIntoArgs to Off."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-52891" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-52891" },
]
affected = []
id = "FBSD-2025-0051"

[database_specific]
vid = "c0f3f54c-5bc4-11f0-834f-b42e991fc52e"
discovery = "2025-07-02T00:00:00Z"
