schema_version = "1.7.0"
modified = "2025-07-02T00:00:00Z"
published = "2025-07-02T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 1 security fix:
>
> * [427663123] High CVE-2025-6554: Type Confusion in V8."""
id = "FBSD-2025-0062"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-6554"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2025/06/stable-channel-update-for-desktop_30.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "138.0.7204.96" },
    { introduced = "0" },
]

[database_specific]
vid = "5c777f88-40ff-4e1e-884b-ad63dfb9bb15"
discovery = "2025-06-30T00:00:00Z"
