schema_version = "1.7.0"
modified = "2024-07-07T00:00:00Z"
published = "2024-07-07T00:00:00Z"
summary = "traefik -- Bypassing IP allow-lists via HTTP/3 early data requests"
details = """
The traefik authors report:

> There is a vulnerability in Traefik that allows bypassing IP allow-lists via HTTP/3 early
> data requests in QUIC 0-RTT handshakes sent with spoofed IP addresses."""
affected = []
id = "FBSD-2024-0169"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-39321"

[[references]]
type = "WEB"
url = "https://github.com/traefik/traefik/security/advisories/GHSA-gxrv-wf35-62w9"

[database_specific]
vid = "767dfb2d-3c9e-11ef-a829-5404a68ad561"
discovery = "2024-07-02T00:00:00Z"
