schema_version = "1.7.0"
modified = "2025-07-25T00:00:00Z"
published = "2025-07-25T00:00:00Z"
summary = "viewvc -- Arbitrary server filesystem content"
details = """
cmpilato reports:

> The ViewVC standalone web server (standalone.py) is a script provided in the ViewVC
> distribution for the purposes of quickly testing a ViewVC configuration. This script
> can in particular configurations expose the contents of the host server's filesystem
> though a directory traversal-style attack."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-54141" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-54141" },
]
id = "FBSD-2025-0014"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "viewvc"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "1.2.0" },
    { last_affected = "1.2.3" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "viewvc-devel"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.3.0.20250316_1" },
    { introduced = "0" },
]

[database_specific]
vid = "c37f29ba-6ae3-11f0-b4bf-ecf4bbefc954"
discovery = "2025-07-22T00:00:00Z"
