schema_version = "1.7.0"
modified = "2024-02-24T00:00:00Z"
published = "2024-02-24T00:00:00Z"
summary = "gitea -- Fix XSS vulnerabilities"
details = """
Problem Description:
====================

* The Wiki page did not sanitize author name
* the reviewer name on a \"dismiss review\" comment is also affected
* the migration page has some spots"""
references = [
    { type = "WEB", url = "https://blog.gitea.com/release-of-1.21.6/" },
]
affected = []
id = "FBSD-2024-0282"

[database_specific]
vid = "5ecfb588-d2f4-11ee-ad82-dbdfaa8acfc2"
discovery = "2024-02-23T00:00:00Z"
