schema_version = "1.7.0"
modified = "2024-12-02T00:00:00Z"
published = "2024-12-02T00:00:00Z"
summary = "electron33 -- Inappropriate implementation in Extensions"
details = """
Electron developers report:

> This update fixes the following vulnerability:
>
> * Security: backported fix for CVE-2024-11110."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-11110" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-4mww-gp9h-h59m" },
]
affected = []
id = "FBSD-2024-0027"

[database_specific]
vid = "8b6e97a9-804e-4366-9f75-d102b22a716d"
discovery = "2024-11-27T00:00:00Z"
