schema_version = "1.7.0"
modified = "2024-08-22T00:00:00Z"
published = "2024-08-22T00:00:00Z"
summary = "nginx -- Vulnerability in the ngx_http_mp4_module"
details = """
The nginx development team reports:

> This update fixes the buffer overread vulnerability in the
> ngx\\_http\\_mp4\\_module."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-7347" },
]
id = "FBSD-2024-0137"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "nginx"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "1.6.0,3" },
    { fixed = "1.26.2,3" },
]

[database_specific]
vid = "addc71b8-6024-11ef-86a1-8c164567ca3c"
discovery = "2024-08-14T00:00:00Z"
