schema_version = "1.7.0"
modified = "2025-07-20T00:00:00Z"
published = "2025-07-20T00:00:00Z"
summary = "libwasmtime -- host panic with fd_renumber WASIp1 function"
details = """
WasmTime development team reports:

> A bug in Wasmtime's implementation of the WASIp1 set of import
> functions can lead to a WebAssembly guest inducing a panic in the
> host (embedder)."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-53901" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-53901" },
]
affected = []
id = "FBSD-2025-0036"

[database_specific]
vid = "605a9d1e-6521-11f0-beb2-ac5afc632ba3"
discovery = "2025-07-18T00:00:00Z"
