schema_version = "1.7.0"
modified = "2025-01-30T00:00:00Z"
published = "2025-01-30T00:00:00Z"
summary = "oauth2-proxy -- Non-linear parsing of case-insensitive content"
details = """
Golang reports:

> This update include security fixes:
>
> * CVE-2024-45338: Non-linear parsing of case-insensitive content"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-45338" },
]
affected = []
id = "FBSD-2025-0245"

[database_specific]
vid = "258a58a9-6583-4808-986b-e785c27b0a18"
discovery = "2025-01-14T00:00:00Z"
