schema_version = "1.7.0"
modified = "2024-04-25T00:00:00Z"
published = "2024-04-25T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 4 security fixes:
>
> * [332546345] Critical CVE-2024-4058: Type Confusion in ANGLE. Reported by Toan (suto) Pham and Bao (zx) Pham of Qrious Secure on 2024-04-02
> * [333182464] High CVE-2024-4059: Out of bounds read in V8 API. Reported by Eirik on 2024-04-08
> * [333420620] High CVE-2024-4060: Use after free in Dawn. Reported by wgslfuzz on 2024-04-09"""
id = "FBSD-2024-0227"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4058"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4059"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4060"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2024/04/stable-channel-update-for-desktop_24.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "124.0.6367.78" },
    { introduced = "0" },
]

[database_specific]
vid = "7a42852d-0347-11ef-9f97-a8a1599412c6"
discovery = "2024-04-24T00:00:00Z"
