schema_version = "1.7.0"
modified = "2024-12-17T00:00:00Z"
published = "2024-12-17T00:00:00Z"
summary = "gitea -- multiple vulnerabilities"
details = """
Problem Description:
====================

* Fix basic auth with webauthn
* Refactor internal routers (partial backport, auth token const time comparing)"""
references = [
    { type = "WEB", url = "https://github.com/go-gitea/gitea/pull/32531" },
    { type = "WEB", url = "https://github.com/go-gitea/gitea/pull/32473" },
]
affected = []
id = "FBSD-2024-0008"

[database_specific]
vid = "6ea20f0c-bca3-11ef-8926-9b4f2d14eb53"
discovery = "2024-11-16T00:00:00Z"
