schema_version = "1.7.0"
modified = "2024-02-08T00:00:00Z"
published = "2024-02-08T00:00:00Z"
summary = "Composer -- Code execution and possible privilege escalation"
details = """
Copmposer reports:

> Code execution and possible privilege escalation via
> compromised InstalledVersions.php or installed.php.
>
> Several files within the local working directory are
> included during the invocation of Composer and in the
> context of the executing user.
>
> As such, under certain conditions arbitrary code
> execution may lead to local privilege escalation, provide
> lateral user movement or malicious code execution when
> Composer is invoked within a directory with tampered
> files.
>
> All Composer CLI commands are affected, including
> composer.phar's self-update."""
id = "FBSD-2024-0301"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-24821"

[[references]]
type = "WEB"
url = "https://github.com/composer/composer/security/advisories/GHSA-7c6p-848j-wh5h"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "php82-composer"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "2.7.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "php83-composer"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "2.7.0" },
    { introduced = "0" },
]

[database_specific]
vid = "33ba2241-c68e-11ee-9ef3-001999f8d30b"
discovery = "2024-02-08T00:00:00Z"
