schema_version = "1.7.0"
modified = "2024-04-15T00:00:00Z"
published = "2024-04-15T00:00:00Z"
summary = "go -- http2: close connections when receiving too many headers"
details = """
The Go project reports:

> http2: close connections when receiving too many headers
>
> Maintaining HPACK state requires that we parse and
> process all HEADERS and CONTINUATION frames on a
> connection. When a request's headers exceed MaxHeaderBytes,
> we don't allocate memory to store the excess headers but we
> do parse them. This permits an attacker to cause an HTTP/2
> endpoint to read arbitrary amounts of header data, all
> associated with a request which is going to be
> rejected. These headers can include Huffman-encoded data
> which is significantly more expensive for the receiver to
> decode than for an attacker to send."""
id = "FBSD-2024-0241"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-45288"

[[references]]
type = "WEB"
url = "https://groups.google.com/g/golang-announce/c/YgW0sx8mN3M/m/khALNYGdAAAJ"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "go121"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.21.9" },
    { introduced = "0" },
]

[database_specific]
vid = "cdb5e0e3-fafc-11ee-9c21-901b0e9408dc"
discovery = "2024-04-03T00:00:00Z"
