schema_version = "1.7.0"
modified = "2025-07-14T00:00:00Z"
published = "2025-07-14T00:00:00Z"
summary = "liboqs -- Secret-dependent branching in HQC"
details = """
The OpenQuantumSafe project reports:

> Secret-dependent branching in HQC reference implementation when compiled with Clang 17-20 for optimizations above -O0"""
affected = []
id = "FBSD-2025-0038"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-52473"

[[references]]
type = "WEB"
url = "https://github.com/open-quantum-safe/liboqs/security/advisories/GHSA-qq3m-rq9v-jfgm"

[database_specific]
vid = "aeac223e-60e1-11f0-8baa-8447094a420f"
discovery = "2025-07-10T00:00:00Z"
