schema_version = "1.7.0"
modified = "2024-08-23T00:00:00Z"
published = "2024-08-23T00:00:00Z"
summary = "firefox -- Multiple vulnerabilities"
details = """
security@mozilla.org reports:

> * CVE-2024-5697: A website was able to detect when a
>   user took a screenshot of a page using the built-in
>   Screenshot functionality in Firefox.
> * CVE-2024-5698: By manipulating the fullscreen
>   feature while opening a data-list, an attacker could
>   have overlaid a text box over the address bar. This
>   could have led to user confusion and possible spoofing
>   attacks."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-5697" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-5697" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-5698" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-5698" },
]
affected = []
id = "FBSD-2024-0133"

[database_specific]
vid = "7e6e932f-617b-11ef-8a7d-b42e991fc52e"
discovery = "2024-06-11T00:00:00Z"
