schema_version = "1.7.0"
modified = "2025-04-20T00:00:00Z"
published = "2025-04-20T00:00:00Z"
summary = "Erlang -- Erlang/OTP SSH Vulnerable to Pre-Authentication RCE"
details = """
security-advisories@github.com reports:

> Erlang/OTP is a set of libraries for the Erlang
> programming language. Prior to versions OTP-27.3.3,
> OTP-26.2.5.11, and OTP-25.3.2.20, a SSH server may allow
> an attacker to perform unauthenticated remote code
> execution (RCE). By exploiting a flaw in SSH protocol
> message handling, a malicious actor could gain
> unauthorized access to affected systems and execute
> arbitrary commands without valid credentials. This issue
> is patched in versions OTP-27.3.3, OTP-26.2.5.11, and
> OTP-25.3.2.20. A temporary workaround involves disabling
> the SSH server or to prevent access via firewall rules."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-32433" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-32433" },
]
id = "FBSD-2025-0153"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "erlang-runtime21"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "25.3.2.20" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "erlang-runtime22"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "25.3.2.20" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "erlang-runtime23"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "25.3.2.20" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "erlang-runtime24"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "25.3.2.20" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "erlang-runtime25"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "25.3.2.20" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "erlang-runtime26"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "26.2.5.11" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "erlang-runtime27"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "27.3.3" },
    { introduced = "0" },
]

[database_specific]
vid = "06269ae8-1e0d-11f0-ad0b-b42e991fc52e"
discovery = "2025-04-16T00:00:00Z"
