schema_version = "1.7.0"
modified = "2024-11-19T00:00:00Z"
published = "2024-11-19T00:00:00Z"
summary = "xorg server -- _XkbSetCompatMap vulnerability"
details = """
The X.Org project reports:

> * CVE-2024-9632: Heap buffer Heap-based buffer overflow
>   privilege escalation in \\_XkbSetCompatMap
>
>   The \\_XkbSetCompatMap() function attempts to resize
>   the `sym\\_interpret` buffer.
>   However, It didn't update its size properly.
>   It updated `num\\_si` only, without updating `size\\_si`.
>   This may lead to local privilege escalation if the
>   server is run as root or remote code execution
>   (e.g. x11 over ssh)."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9632" },
    { type = "WEB", url = "https://lists.x.org/archives/xorg-announce/2024-October/003545.html" },
]
id = "FBSD-2024-0034"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "xwayland"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "24.1.4,1" },
    { introduced = "0" },
]

[database_specific]
vid = "141f2a22-a6a7-11ef-b282-0c9d92850f7a"
discovery = "2024-10-29T00:00:00Z"
