schema_version = "1.7.0"
modified = "2024-05-09T00:00:00Z"
published = "2024-05-09T00:00:00Z"
summary = "PostgreSQL server -- Potentially allowing authenicated database users to see data that they shouldn't."
details = """
PostgreSQL project reports:

> A security vulnerability was found in the system views pg\\_stats\\_ext
> and pg\\_stats\\_ext\\_exprs, potentially allowing authenticated database
> users to see data they shouldn't. If this is of concern in your
> installation, run the SQL script /usr/local/share/postgresql/fix-CVE-2024-4317.sql
> for each of your databases. See the link for details."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-4317" },
    { type = "WEB", url = "https://www.postgresql.org/support/security/CVE-2024-4317/" },
]
affected = []
id = "FBSD-2024-0217"

[database_specific]
vid = "d53c30c1-0d7b-11ef-ba02-6cc21735f730"
discovery = "2024-05-09T00:00:00Z"
