schema_version = "1.7.0"
modified = "2024-06-23T00:00:00Z"
published = "2024-06-23T00:00:00Z"
summary = "emacs -- Arbitrary shell code evaluation vulnerability"
details = """
GNU Emacs developers report:

> Emacs 29.4 is an emergency bugfix release intended to fix a security vulnerability. Arbitrary shell commands are no longer run when turning on Org mode in order to avoid running malicious code."""
references = [
    { type = "WEB", url = "https://seclists.org/oss-sec/2024/q2/296" },
]
id = "FBSD-2024-0180"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-canna"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "29.3_3,3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-nox"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "29.3_3,3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-wayland"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "29.3_3,3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-devel"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "30.0.50.20240615_1,3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "emacs-devel-nox"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "30.0.50.20240615_1,3" },
    { introduced = "0" },
]

[database_specific]
vid = "4f6c4c07-3179-11ef-9da5-1c697a616631"
discovery = "2024-06-22T00:00:00Z"
