schema_version = "1.7.0"
modified = "2025-07-24T00:00:00Z"
published = "2025-07-24T00:00:00Z"
summary = "Mozilla -- Multiple vulnerabilities"
details = """
security@mozilla.org reports:

> Memory safety bugs present in Firefox 140 and
> Thunderbird 140. Some of these bugs showed evidence of
> memory corruption and we presume that with enough effort
> some of these could have been exploited to run arbitrary
> code.
>
> Focus incorrectly truncated URLs towards the beginning instead of
> around the origin."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-8044" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-8044" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-8043" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-8043" },
]
id = "FBSD-2025-0016"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "141.0" },
    { introduced = "0" },
]

[database_specific]
vid = "67c6461f-685e-11f0-a12d-b42e991fc52e"
discovery = "2025-07-22T00:00:00Z"
