schema_version = "1.7.0"
modified = "2025-02-24T00:00:00Z"
published = "2025-02-24T00:00:00Z"
summary = "exim -- SQL injection"
details = """
cve@mitre.org reports:

> Exim 4.98 before 4.98.1, when SQLite hints and ETRN serialization
> are used, allows remote SQL injection."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-26794" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-26794" },
]
affected = []
id = "FBSD-2025-0219"

[database_specific]
vid = "07c34df5-f299-11ef-a441-b42e991fc52e"
discovery = "2025-02-21T00:00:00Z"
