schema_version = "1.7.0"
modified = "2024-09-06T00:00:00Z"
published = "2024-09-06T00:00:00Z"
summary = "binutils -- Multiple vulnerabilities"
details = """
alster@vinterdalen.se reports PR/281070:

> A new version of devel/binutils has been released fixing
> CVE-2023-1972, CVE-2023-25585, CVE-2023-25586, and
> CVE-2023-25588."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2023-1972" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2023-25585" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2023-25586" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2023-25588" },
]
affected = []
id = "FBSD-2024-0116"

[database_specific]
vid = "943f8915-6c5d-11ef-810a-f8b46a88f42c"
discovery = "2024-08-25T00:00:00Z"
