schema_version = "1.7.0"
modified = "2024-07-28T00:00:00Z"
published = "2024-07-28T00:00:00Z"
summary = "znc -- remote code execution vulnerability"
details = """
Mitre reports:

> In ZNC before 1.9.1, remote code execution can occur in modtcl via a KICK."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-39844" },
    { type = "WEB", url = "https://wiki.znc.in/ChangeLog/1.9.1" },
    { type = "WEB", url = "https://www.openwall.com/lists/oss-security/2024/07/03/9" },
]
affected = []
id = "FBSD-2024-0158"

[database_specific]
vid = "8057d198-4d26-11ef-8e64-641c67a117d8"
discovery = "2024-07-03T00:00:00Z"
