schema_version = "1.7.0"
modified = "2024-07-10T00:00:00Z"
published = "2024-07-10T00:00:00Z"
summary = "Django -- multiple vulnerabilities"
details = """
Django reports:

> CVE-2024-38875: Potential denial-of-service in django.utils.html.urlize().
>
> CVE-2024-39329: Username enumeration through timing difference for users with unusable passwords.
>
> CVE-2024-39330: Potential directory-traversal in django.core.files.storage.Storage.save().
>
> CVE-2024-39614: Potential denial-of-service in django.utils.translation.get\\_supported\\_language\\_variant()."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-38875" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-39329" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-39330" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-39614" },
    { type = "WEB", url = "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/" },
]
id = "FBSD-2024-0168"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py310-django42"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "4.2.14" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py311-django42"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "4.2.14" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py310-django50"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "5.0.7" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py311-django50"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "5.0.7" },
    { introduced = "0" },
]

[database_specific]
vid = "171afa61-3eba-11ef-a58f-080027836e8b"
discovery = "2024-07-01T00:00:00Z"
