schema_version = "1.7.0"
modified = "2025-07-04T00:00:00Z"
published = "2025-07-04T00:00:00Z"
summary = "Mozilla -- persistent UUID that identifies browser"
details = """
security@mozilla.org reports:

> An attacker who enumerated resources from the WebCompat extension
> could have obtained a persistent UUID that identified the browser,
> and persisted between containers and normal/private browsing mode,
> but not profiles. This vulnerability affects Firefox < 140,
> Firefox ESR < 115.25, Firefox ESR < 128.12, Thunderbird <
> 140, and Thunderbird < 128.12."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-6425" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-6425" },
]
id = "FBSD-2025-0059"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "115.25.0" },
    { introduced = "0" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.12" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "140.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.12" },
    { introduced = "0" },
]

[database_specific]
vid = "9320590b-58cf-11f0-b4ad-b42e991fc52e"
discovery = "2025-06-24T00:00:00Z"
