schema_version = "1.7.0"
modified = "2025-05-11T00:00:00Z"
published = "2025-05-11T00:00:00Z"
summary = "Mozilla -- Information leak"
details = """
security@mozilla.org reports:

> An attacker with control over a content process could
> potentially leverage the privileged UITour actor to leak
> sensitive information or escalate privileges."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-4085" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-4085" },
]
id = "FBSD-2025-0135"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "138.0" },
    { introduced = "0" },
]

[database_specific]
vid = "9fa8c4a2-2e85-11f0-a989-b42e991fc52e"
discovery = "2025-04-29T00:00:00Z"
