schema_version = "1.7.0"
modified = "2024-01-04T00:00:00Z"
published = "2024-01-04T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 6 security fixes:
>
> * [1501798] High CVE-2024-0222: Use after free in ANGLE. Reported by Toan (suto) Pham of Qrious Secure on 2023-11-13
> * [1505009] High CVE-2024-0223: Heap buffer overflow in ANGLE. Reported by Toan (suto) Pham and Tri Dang of Qrious Secure on 2023-11-24
> * [1505086] High CVE-2024-0224: Use after free in WebAudio. Reported by Huang Xilin of Ant Group Light-Year Security Lab on 2023-11-25
> * [1506923] High CVE-2024-0225: Use after free in WebGPU. Reported by Anonymous on 2023-12-01"""
id = "FBSD-2024-0329"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-0222"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-0223"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-0224"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-0225"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2024/01/stable-channel-update-for-desktop.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "120.0.6099.199" },
    { introduced = "0" },
]

[database_specific]
vid = "3ee577a9-aad4-11ee-86bb-a8a1599412c6"
discovery = "2024-01-03T00:00:00Z"
