schema_version = "1.7.0"
modified = "2024-10-03T00:00:00Z"
published = "2024-10-03T00:00:00Z"
summary = "firefox -- multiple vulnerabilities"
details = """
security@mozilla.org reports:

> * CVE-2024-9392: A compromised content process could have
>   allowed for the arbitrary loading of cross-origin pages.
> * CVE-2024-9396: It is currently unknown if this issue is
>   exploitable but a condition may arise where the structured
>   clone of certain objects could lead to memory corruption.
> * CVE-2024-9400: A potential memory corruption vulnerability
>   could be triggered if an attacker had the ability to trigger
>   an OOM at a specific moment during JIT compilation.
> * CVE-2024-9401: Memory safety bugs present in Firefox 130,
>   Firefox ESR 115.15, Firefox ESR 128.2, and Thunderbird 128.2.
>   Some of these bugs showed evidence of memory corruption and we
>   presume that with enough effort some of these could have been
>   exploited to run arbitrary code.
> * CVE-2024-9402: Memory safety bugs present in Firefox 130,
>   Firefox ESR 128.2, and Thunderbird 128.2. Some of these bugs
>   showed evidence of memory corruption and we presume that with
>   enough effort some of these could have been exploited to run
>   arbitrary code.
> * CVE-2024-9403: Memory safety bugs present in Firefox 130.
>   Some of these bugs showed evidence of memory corruption and we
>   presume that with enough effort some of these could have been
>   exploited to run arbitrary code."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9392" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-9392" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9396" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-9396" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9400" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-9400" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9401" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-9401" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9402" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-9402" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9403" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-9403" },
]
id = "FBSD-2024-0086"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.3.0,1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.3.0" },
    { introduced = "0" },
]

[database_specific]
vid = "0417d41a-8175-11ef-a5dc-b42e991fc52e"
discovery = "2024-10-01T00:00:00Z"
