schema_version = "1.7.0"
modified = "2025-06-20T00:00:00Z"
published = "2025-06-20T00:00:00Z"
summary = "clamav -- ClamAV PDF Scanning Buffer Overflow Vulnerability"
details = """
Cisco reports:

> A vulnerability in the PDF scanning processes of ClamAV could allow
> an unauthenticated, remote attacker to cause a buffer overflow
> condition, cause a denial of service (DoS) condition, or execute
> arbitrary code on an affected device.
> This vulnerability exists because memory buffers are allocated
> incorrectly when PDF files are processed. An attacker could exploit
> this vulnerability by submitting a crafted PDF file to be scanned
> by ClamAV on an affected device. A successful exploit could allow
> the attacker to trigger a buffer overflow, likely resulting in the
> termination of the ClamAV scanning process and a DoS condition on
> the affected software. Although unproven, there is also a possibility
> that an attacker could leverage the buffer overflow to execute
> arbitrary code with the privileges of the ClamAV process."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-20260" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-20260" },
]
affected = []
id = "FBSD-2025-0076"

[database_specific]
vid = "3dcc0812-4da5-11f0-afcc-f02f7432cf97"
discovery = "2025-06-18T00:00:00Z"
