schema_version = "1.7.0"
modified = "2025-03-26T00:00:00Z"
published = "2025-03-26T00:00:00Z"
summary = "Gitlab -- Vulnerabilities"
details = """
Gitlab reports:

> Cross-site Scripting (XSS) through merge-request error messages
>
> Cross-site Scripting (XSS) through improper rendering of certain file types
>
> Admin Privileges Persists After Role is Revoked
>
> External user can access internal projects
>
> Prompt injection in Amazon Q integration may allow unauthorized actions
>
> Uncontrolled Resource Consumption via a maliciously crafted terraform file in merge request
>
> Maintainer can inject shell code in Harbor project name configuration when using helper scripts"""
id = "FBSD-2025-0191"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-2255"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-0811"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-2242"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-12619"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-10307"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9773"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2025/03/26/patch-release-gitlab-17-10-1-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.10.0" },
    { fixed = "17.10.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.9.0" },
    { fixed = "17.9.3" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "12.10.0" },
    { fixed = "17.8.6" },
]

[database_specific]
vid = "1daa2814-0a6c-11f0-b4e4-2cf05da270f3"
discovery = "2025-03-26T00:00:00Z"
