schema_version = "1.7.0"
modified = "2024-04-24T00:00:00Z"
published = "2024-04-24T00:00:00Z"
summary = "Gitlab -- vulnerabilities"
details = """
Gitlab reports:

> GitLab account takeover, under certain conditions, when using Bitbucket as an OAuth provider
>
> Path Traversal leads to DoS and Restricted File Read
>
> Unauthenticated ReDoS in FileFinder when using wildcard filters in project file search
>
> Personal Access Token scopes not honoured by GraphQL subscriptions
>
> Domain based restrictions bypass using a crafted email address"""
id = "FBSD-2024-0229"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4024"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2434"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2829"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4006"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-1347"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2024/04/24/patch-release-gitlab-16-11-1-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "16.11.0" },
    { fixed = "16.11.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "16.10.0" },
    { fixed = "16.10.4" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "7.8.0" },
    { fixed = "16.9.6" },
]

[database_specific]
vid = "b857606c-0266-11ef-8681-001b217b3468"
discovery = "2024-04-24T00:00:00Z"
