schema_version = "1.7.0"
modified = "2025-06-02T00:00:00Z"
published = "2025-06-02T00:00:00Z"
summary = "Gimp -- GIMP XWD File Parsing Integer Overflow Remote Code Execution Vulnerability"
details = """
zdi-disclosures@trendmicro.com reports:

> GIMP XWD File Parsing Integer Overflow Remote Code Execution
> Vulnerability. This vulnerability allows remote attackers to execute
> arbitrary code on affected installations of GIMP. User interaction
> is required to exploit this vulnerability in that the target must
> visit a malicious page or open a malicious file.
> The specific flaw exists within the parsing of XWD files. The issue
> results from the lack of proper validation of user-supplied data,
> which can result in an integer overflow before allocating a buffer.
> An attacker can leverage this vulnerability to execute code in the
> context of the current process. Was ZDI-CAN-25082."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-2760" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-2760" },
]
affected = []
id = "FBSD-2025-0100"

[database_specific]
vid = "da0a4374-3fc9-11f0-a39d-b42e991fc52e"
discovery = "2025-04-23T00:00:00Z"
