schema_version = "1.7.0"
modified = "2025-05-30T00:00:00Z"
published = "2025-05-30T00:00:00Z"
summary = "Mozilla -- memory corruption"
details = """
security@mozilla.org reports:

> Memory safety bug present in Firefox ESR 128.10, and
> Thunderbird 128.10.
> This bug showed evidence of memory corruption and we presume
> that with enough effort this could have been exploited to run
> arbitrary code."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-5269" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-5269" },
]
id = "FBSD-2025-0107"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.11.0" },
    { introduced = "0" },
]

[database_specific]
vid = "a6e1b7ee-3d7c-11f0-9a55-b42e991fc52e"
discovery = "2025-05-27T00:00:00Z"
