schema_version = "1.7.0"
modified = "2025-05-31T00:00:00Z"
published = "2025-05-31T00:00:00Z"
summary = "libxml2 -- Stack-based Buffer Overflow"
details = """
cve@mitre.org reports:

> libxml2 before 2.12.10 and 2.13.x before 2.13.6 has a stack-based
> buffer overflow in xmlSnprintfElements in valid.c. To exploit this,
> DTD validation must occur for an untrusted document or untrusted
> DTD. NOTE: this is similar to CVE-2017-9047."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-24928" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-24928" },
]
affected = []
id = "FBSD-2025-0103"

[database_specific]
vid = "fdd02be0-3e50-11f0-95d4-00a098b42aeb"
discovery = "2025-02-18T00:00:00Z"
