schema_version = "1.7.0"
modified = "2025-05-07T00:00:00Z"
published = "2025-05-07T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 2 security fixes:
>
> * [412057896] Medium CVE-2025-4372: Use after free in WebAudio. Reported by Huang Xilin of Ant Group Light-Year Security Lab on 2025-04-20"""
id = "FBSD-2025-0139"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-4372"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2025/05/stable-channel-update-for-desktop.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "136.0.7103.92" },
    { introduced = "0" },
]

[database_specific]
vid = "db221414-2b0d-11f0-8cb5-a8a1599412c6"
discovery = "2025-05-06T00:00:00Z"
