schema_version = "1.7.0"
modified = "2024-03-14T00:00:00Z"
published = "2024-03-14T00:00:00Z"
summary = "electron{27,28} -- Out of bounds memory access in V8"
details = """
Electron developers report:

> This update fixes the following vulnerability:
>
> * Security: backported fix for CVE-2024-2173."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-2173" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-6hhg-hj7x-7qv8" },
]
id = "FBSD-2024-0268"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "electron28"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "28.2.7" },
    { introduced = "0" },
]

[database_specific]
vid = "49dd9362-4473-48ae-8fac-e1b69db2dedf"
discovery = "2024-03-13T00:00:00Z"
