schema_version = "1.7.0"
modified = "2025-04-10T00:00:00Z"
published = "2025-04-10T00:00:00Z"
summary = "Gitlab -- Vulnerabilities"
details = """
Gitlab reports:

> Denial of service via CI pipelines
>
> Unintentionally authorizing sensitive actions on users behalf
>
> IP Restriction Bypass through GraphQL Subscription
>
> Unauthorized users can list the number of confidential issues
>
> Debugging Information Disclosed"""
id = "FBSD-2025-0159"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-1677"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-0362"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-2408"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-11129"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-2469"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2025/04/09/patch-release-gitlab-17-10-4-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.10.0" },
    { fixed = "17.10.4" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.9.0" },
    { fixed = "17.9.6" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "7.7.0" },
    { fixed = "17.8.7" },
]

[database_specific]
vid = "ed602f8b-15c2-11f0-b4e4-2cf05da270f3"
discovery = "2025-04-09T00:00:00Z"
