schema_version = "1.7.0"
modified = "2024-05-09T00:00:00Z"
published = "2024-05-09T00:00:00Z"
summary = "Gitlab -- vulnerabilities"
details = """
Gitlab reports:

> ReDoS in branch search when using wildcards
>
> ReDoS in markdown render pipeline
>
> Redos on Discord integrations
>
> Redos on Google Chat Integration
>
> Denial of Service Attack via Pin Menu
>
> DoS by filtering tags and branches via the API
>
> MR approval via CSRF in SAML SSO
>
> Banned user from groups can read issues updates via the api
>
> Require confirmation before linking JWT identity
>
> View confidential issues title and description of any public project via export
>
> SSRF via Github importer"""
id = "FBSD-2024-0220"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2878"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2651"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-6682"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-6688"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2454"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4539"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4597"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-1539"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-1211"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-3976"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-6195"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2024/05/08/patch-release-gitlab-16-11-2-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "16.11.0" },
    { fixed = "16.11.2" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "16.10.0" },
    { fixed = "16.10.5" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "10.6.0" },
    { fixed = "16.9.7" },
]

[database_specific]
vid = "fbc2c629-0dc5-11ef-9850-001b217b3468"
discovery = "2024-05-08T00:00:00Z"
