schema_version = "1.7.0"
modified = "2024-10-09T00:00:00Z"
published = "2024-10-09T00:00:00Z"
summary = "powerdns-recursor -- denial of service"
details = """
PowerDNS Team reports:

> PowerDNS Security Advisory 2024-04: Crafted responses can lead to
> a denial of service due to cache inefficiencies in the Recursor"""
affected = []
id = "FBSD-2024-0081"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-25590"

[[references]]
type = "WEB"
url = "https://doc.powerdns.com/recursor/security-advisories/powerdns-advisory-2024-04.html"

[database_specific]
vid = "8727b513-855b-11ef-9e50-6805ca2fa271"
discovery = "2024-10-03T00:00:00Z"
