schema_version = "1.7.0"
modified = "2024-08-23T00:00:00Z"
published = "2024-08-23T00:00:00Z"
summary = "md4c -- DoS attack"
details = """
cve@mitre.org reports:

> md\\_analyze\\_line in md4c.c in md4c 0.4.7 allows attackers
> to trigger use of uninitialized memory, and cause a denial
> of service via a malformed Markdown document."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2021-30027" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2021-30027" },
]
affected = []
id = "FBSD-2024-0135"

[database_specific]
vid = "f2b1da2e-6178-11ef-8a7d-b42e991fc52e"
discovery = "2021-04-29T00:00:00Z"
