schema_version = "1.7.0"
modified = "2024-02-07T00:00:00Z"
published = "2024-02-07T00:00:00Z"
summary = "Django -- multiple vulnerabilities"
details = """
Django reports:

> CVE-2024-24680:Potential denial-of-service in intcomma template filter."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-24680" },
    { type = "WEB", url = "https://www.djangoproject.com/weblog/2024/feb/06/security-releases/" },
]
id = "FBSD-2024-0305"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py310-django32"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.2.24" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py311-django32"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "3.2.24" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py39-django42"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "4.2.8" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py310-django42"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "4.2.8" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py311-django42"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "4.2.8" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py311-django50"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "5.0.2" },
    { introduced = "0" },
]

[database_specific]
vid = "e0f6215b-c59e-11ee-a6db-080027a5b8e9"
discovery = "2024-01-09T00:00:00Z"
