schema_version = "1.7.0"
modified = "2024-10-10T00:00:00Z"
published = "2024-10-10T00:00:00Z"
summary = "Gitlab -- vulnerabilities"
details = """
Gitlab reports:

> Run pipelines on arbitrary branches
>
> An attacker can impersonate arbitrary user
>
> SSRF in Analytics Dashboard
>
> Viewing diffs of MR with conflicts can be slow
>
> HTMLi in OAuth page
>
> Deploy Keys can push changes to an archived repository
>
> Guests can disclose project templates
>
> GitLab instance version disclosed to unauthorized users"""
id = "FBSD-2024-0079"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9164"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8970"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8977"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9631"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-6530"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9623"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-5005"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-9596"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2024/10/09/patch-release-gitlab-17-4-2-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.4.0" },
    { fixed = "17.4.2" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.3.0" },
    { fixed = "17.3.5" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "8.16" },
    { fixed = "17.2.9" },
]

[database_specific]
vid = "cc1ac01e-86b0-11ef-9369-2cf05da270f3"
discovery = "2024-10-09T00:00:00Z"
