schema_version = "1.7.0"
modified = "2024-04-11T00:00:00Z"
published = "2024-04-11T00:00:00Z"
summary = "Gitlab -- Patch Release: 16.10.2, 16.9.4, 16.8.6"
details = """
Gitlab reports:

> Stored XSS injected in diff viewer
>
> Stored XSS via autocomplete results
>
> Redos on Integrations Chat Messages
>
> Redos During Parse Junit Test Report"""
affected = []
id = "FBSD-2024-0248"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-3092"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2279"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-6489"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-6678"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2024/04/10/patch-release-gitlab-16-10-2-released/"

[database_specific]
vid = "dad6294c-f7c1-11ee-bb77-001b217b3468"
discovery = "2024-04-10T00:00:00Z"
