schema_version = "1.7.0"
modified = "2025-05-11T00:00:00Z"
published = "2025-05-11T00:00:00Z"
summary = "Mozilla -- javascript content execution"
details = """
security@mozilla.org reports:

> A process isolation vulnerability in Thunderbird stemmed
> from improper handling of javascript: URIs, which could
> allow content to execute in the top-level document's
> process instead of the intended frame, potentially enabling
> a sandbox escape."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-4083" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-4083" },
]
id = "FBSD-2025-0136"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.10,1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "138.0" },
    { introduced = "0" },
]

[database_specific]
vid = "9c37a02e-2e85-11f0-a989-b42e991fc52e"
discovery = "2025-04-29T00:00:00Z"
