schema_version = "1.7.0"
modified = "2024-02-15T00:00:00Z"
published = "2024-02-15T00:00:00Z"
summary = "gitea -- Prevent anonymous container access"
details = """
Problem Description:
====================

Even with RequireSignInView enabled, anonymous users can use docker pull
to fetch public images."""
references = [
    { type = "WEB", url = "https://blog.gitea.com/release-of-1.21.5/" },
]
affected = []
id = "FBSD-2024-0333"

[database_specific]
vid = "bd7592a1-cbfd-11ee-a42a-5404a6f3ca32"
discovery = "2024-01-24T00:00:00Z"
