schema_version = "1.7.0"
modified = "2025-01-25T00:00:00Z"
published = "2025-01-25T00:00:00Z"
summary = "electron32 -- multiple vulnerabilities"
details = """
Electron developers report:

> This update fixes the following vulnerabilities:
>
> * Security: backported fix for CVE-2024-12693.
> * Security: backported fix for CVE-2024-12694.
> * Security: backported fix for CVE-2024-12695.
> * Security: backported fix for CVE-2025-0434.
> * Security: backported fix for CVE-2025-0436.
> * Security: backported fix for CVE-2025-0437."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-12693" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-m84q-p89f-6cc5" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-12694" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-cgc6-4xgf-5q5x" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-12695" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-6895-2frg-pq5j" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0434" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-fpmx-pfpg-92xg" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0436" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-ww3g-8h77-wr7v" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0437" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-4353-vp82-4qq4" },
]
affected = []
id = "FBSD-2025-0249"

[database_specific]
vid = "ef303b6a-7d9e-4e28-b92e-21f39d519d9e"
discovery = "2025-01-23T00:00:00Z"
