schema_version = "1.7.0"
modified = "2025-04-04T00:00:00Z"
published = "2025-04-04T00:00:00Z"
summary = "Mozilla -- Memory corruption bug"
details = """
security@mozilla.org reports:

> Memory safety bugs present in Firefox 133, Thunderbird 133,
> Firefox ESR 128.5, and Thunderbird 128.5. Some of these
> bugs showed evidence of memory corruption and we presume
> that with enough effort some of these could have been
> exploited to run arbitrary code."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0243" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-0243" },
]
id = "FBSD-2025-0168"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "librewolf"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "134.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.6.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "134.0" },
    { introduced = "0" },
]

[database_specific]
vid = "1205eccf-116d-11f0-8b2c-b42e991fc52e"
discovery = "2025-01-07T00:00:00Z"
