schema_version = "1.7.0"
modified = "2024-04-24T00:00:00Z"
published = "2024-04-24T00:00:00Z"
summary = "powerdns-recursor -- denial of service"
details = """
PowerDNS Team reports:

> PowerDNS Security Advisory 2024-02: if recursive forwarding is configured,
> crafted responses can lead to a denial of service in Recursor"""
affected = []
id = "FBSD-2024-0230"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-25583"

[[references]]
type = "WEB"
url = "https://docs.powerdns.com/recursor/security-advisories/powerdns-advisory-2024-02.html"

[database_specific]
vid = "1af16f2b-023c-11ef-8791-6805ca2fa271"
discovery = "2024-04-24T00:00:00Z"
