schema_version = "1.7.0"
modified = "2024-04-02T00:00:00Z"
published = "2024-04-02T00:00:00Z"
summary = "jenkins -- HTTP/2 denial of service vulnerability in bundled Jetty"
details = """
Jenkins Security Advisory:

> Description
> ===========
>
> ##### (High) SECURITY-3379 / CVE-2024-22201
>
> HTTP/2 denial of service vulnerability in bundled Jetty"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-22201" },
    { type = "WEB", url = "https://www.jenkins.io/security/advisory/2024-03-20/" },
]
id = "FBSD-2024-0254"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "jenkins-lts"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "2.440.2" },
    { introduced = "0" },
]

[database_specific]
vid = "2e3bea0c-f110-11ee-bc57-00e081b7aa2d"
discovery = "2024-03-20T00:00:00Z"
