schema_version = "1.7.0"
modified = "2024-12-17T00:00:00Z"
published = "2024-12-17T00:00:00Z"
summary = "forgejo -- unauthorized user impersonation"
details = """
Problem Description:
====================

* When Forgejo is configured to run the internal ssh server with
  [server].START\\_SSH\\_SERVER=true, it was possible for a registered user
  to impersonate another user. The rootless container image uses the
  internal ssh server by default and was vulnerable. A Forgejo
  instance running from a binary or from a root container image does
  not use the internal ssh server by default and was not vulnerable.
  The incorrect use of the crypto package is the root cause of the
  vulnerability and was fixed for the internal ssh server.
* Revert \"allow synchronizing user status from OAuth2 login
  providers\""""
references = [
    { type = "WEB", url = "https://codeberg.org/forgejo/forgejo/pulls/6248" },
]
affected = []
id = "FBSD-2024-0010"

[database_specific]
vid = "25a697de-bca1-11ef-8926-9b4f2d14eb53"
discovery = "2024-12-12T00:00:00Z"
