schema_version = "1.7.0"
modified = "2025-02-28T00:00:00Z"
published = "2025-02-28T00:00:00Z"
summary = "Gitlab -- Vulnerabilities"
details = """
Gitlab reports:

> XSS in k8s proxy endpoint
>
> XSS Maven Dependency Proxy
>
> HTML injection leads to XSS on self hosted instances
>
> Improper Authorisation Check Allows Guest User to Read Security Policy
>
> Planner role can read code review analytics in private projects"""
id = "FBSD-2025-0214"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-0475"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-0555"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8186"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-10925"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-0307"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2025/02/26/patch-release-gitlab-17-9-1-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.9.0" },
    { fixed = "17.9.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.8.0" },
    { fixed = "17.8.4" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "15.10.0" },
    { fixed = "17.7.6" },
]

[database_specific]
vid = "8fb9101e-f58a-11ef-b4e4-2cf05da270f3"
discovery = "2025-02-26T00:00:00Z"
