schema_version = "1.7.0"
modified = "2025-01-10T00:00:00Z"
published = "2025-01-10T00:00:00Z"
summary = "redis,valkey -- Denial-of-service valnerability due to malformed ACL selectors"
details = """
Redis core team reports:

> An authenticated with sufficient privileges may create a
> malformed ACL selector which, when accessed, triggers a
> server panic and subsequent denial of service.The problem
> exists in Redis 7.0.0 or newer."""
id = "FBSD-2025-0262"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-51741"

[[references]]
type = "WEB"
url = "https://github.com/redis/redis/security/advisories/GHSA-prpq-rh5h-46g9"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "redis72"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "7.2.7" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "redis-devel"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "7.4.2.20250201" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "valkey"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "8.0.2" },
    { introduced = "0" },
]

[database_specific]
vid = "4d79fd1a-cc93-11ef-abed-08002784c58d"
discovery = "2025-01-06T00:00:00Z"
