schema_version = "1.7.0"
modified = "2025-07-15T00:00:00Z"
published = "2025-07-10T00:00:00Z"
summary = "Apache Tomcat -- Multiple Vulnerabilities"
details = """
security@apache.org reports:

> A race condition on connection close could trigger a JVM crash when using the
> APR/Native connector leading to a DoS. This was particularly noticeable with client
> initiated closes of HTTP/2 connections.

> An uncontrolled resource consumption vulnerability if an HTTP/2 client did not
> acknowledge the initial settings frame that reduces the maximum permitted
> concurrent streams could result in a DoS.

> For some unlikely configurations of multipart upload, an Integer Overflow
> vulnerability could lead to a DoS via bypassing of size limits."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-52434" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-52434" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-52520" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-52520" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-53506" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-53506" },
]
id = "FBSD-2025-0044"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "tomcat101"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "10.1.0" },
    { fixed = "10.1.43" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "tomcat9"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "9.0.0" },
    { fixed = "9.0.107" },
]

[database_specific]
vid = "ef87346f-5dd0-11f0-beb2-ac5afc632ba3"
discovery = "2025-07-10T00:00:00Z"
