schema_version = "1.7.0"
modified = "2024-12-11T00:00:00Z"
published = "2024-12-11T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 4 security fixes:
>
> * [379009132] High CVE-2024-12053: Type Confusion in V8. Reported by gal1ium and chluo on 2024-11-14"""
id = "FBSD-2024-0016"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-12053"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2024/12/stable-channel-update-for-desktop.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "131.0.6778.108" },
    { introduced = "0" },
]

[database_specific]
vid = "3d5b7860-48ad-48c2-aa36-601b8ab9cc43"
discovery = "2024-12-03T00:00:00Z"
