schema_version = "1.7.0"
modified = "2024-09-30T00:00:00Z"
published = "2024-09-30T00:00:00Z"
summary = "php -- Multiple vulnerabilities"
details = """
php.net reports:

> * CVE-2024-8926: CGI: Fixed bug GHSA-9pqp-7h25-4f32 (Bypass of CVE-2024-4577, Parameter Injection Vulnerability).
> * CVE-2024-8927: CGI: Fixed bug GHSA-94p6-54jq-9mwp (cgi.force\\_redirect configuration is bypassable due to the environment variable collision).
> * CVE-2024-9026: FPM: Fixed bug GHSA-865w-9rf3-2wh5 (Logs from childrens may be altered).
> * CVE-2024-8925: SAPI: Fixed bug GHSA-9pqp-7h25-4f32 (Erroneous parsing of multipart form data)."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-8926" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-8927" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-9026" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-8925" },
    { type = "WEB", url = "https://www.php.net/ChangeLog-8.php" },
]
id = "FBSD-2024-0089"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "php82"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "8.2.24" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "php83"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "8.3.12" },
    { introduced = "0" },
]

[database_specific]
vid = "fe5c1e7a-7eed-11ef-9533-f875a43e1796"
discovery = "2024-09-26T00:00:00Z"
