schema_version = "1.7.0"
modified = "2024-12-07T00:00:00Z"
published = "2024-12-07T00:00:00Z"
summary = "qt6-webengine -- Multiple vulnerabilities"
details = """
Qt qtwebengine-chromium repo reports:

> Backports for 5 security bugs in Chromium:
>
> * CVE-2024-11110: Inappropriate implementation in Blink
> * CVE-2024-11112: Use after free in Media
> * CVE-2024-11114: Inappropriate implementation in Views
> * CVE-2024-11116: Inappropriate implementation in Paint
> * CVE-2024-11117: Inappropriate implementation in FileSystem"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-11110" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-11112" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-11114" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-11116" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-11117" },
    { type = "WEB", url = "https://code.qt.io/cgit/qt/qtwebengine-chromium.git/log/?h=118-based" },
]
affected = []
id = "FBSD-2024-0018"

[database_specific]
vid = "c2fd83e4-b450-11ef-b680-4ccc6adda413"
discovery = "2024-11-29T00:00:00Z"
