schema_version = "1.7.0"
modified = "2025-06-03T00:00:00Z"
published = "2025-06-03T00:00:00Z"
summary = "Post-Auth Remote Code Execution found in Roundcube Webmail"
details = """
Roundcube Webmail reports:

> Fix Post-Auth RCE via PHP Object Deserialization reported by firs0v"""
id = "FBSD-2025-0098"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-49113"

[[references]]
type = "WEB"
url = "https://roundcube.net/news/2025/06/01/security-updates-1.6.11-and-1.5.10"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "roundcube-php82"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.6.11" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "roundcube-php83"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.6.11" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "roundcube-php84"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.6.11" },
    { introduced = "0" },
]

[database_specific]
vid = "0d6094a2-4095-11f0-8c92-00d861a0e66d"
discovery = "2025-06-01T00:00:00Z"
