schema_version = "1.7.0"
modified = "2024-06-27T00:00:00Z"
published = "2024-06-27T00:00:00Z"
summary = "Gitlab -- Vulnerabilities"
details = """
Gitlab reports:

> Run pipelines as any user
>
> Stored XSS injected in imported project's commit notes
>
> CSRF on GraphQL API IntrospectionQuery
>
> Remove search results from public projects with unauthorized repos
>
> Cross window forgery in user application OAuth flow
>
> Project maintainers can bypass group's merge request approval policy
>
> ReDoS via custom built markdown page
>
> Private job artifacts can be accessed by any user
>
> Security fixes for banzai pipeline
>
> ReDoS in dependency linker
>
> Denial of service using a crafted OpenAPI file
>
> Merge request title disclosure
>
> Access issues and epics without having an SSO session
>
> Non project member can promote key results to objectives"""
id = "FBSD-2024-0178"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-5655"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4901"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4994"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-6323"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2177"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-5430"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4025"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-3959"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4557"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-1493"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-1816"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2191"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-3115"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4011"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2024/06/26/patch-release-gitlab-17-1-1-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.1.0" },
    { fixed = "17.1.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.0.0" },
    { fixed = "17.0.3" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "1.0.0" },
    { fixed = "16.11.5" },
]

[database_specific]
vid = "589de937-343f-11ef-8a7b-001b217b3468"
discovery = "2024-06-26T00:00:00Z"
