schema_version = "1.7.0"
modified = "2024-03-27T00:00:00Z"
published = "2024-03-27T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 7 security fixes:
>
> * [327807820] Critical CVE-2024-2883: Use after free in ANGLE. Reported by Cassidy Kim(@cassidy6564) on 2024-03-03
> * [328958020] High CVE-2024-2885: Use after free in Dawn. Reported by wgslfuzz on 2024-03-11
> * [330575496] High CVE-2024-2886: Use after free in WebCodecs. Reported by Seunghyun Lee (@0x10n) of KAIST Hacking Lab, via Pwn2Own 2024 on 2024-03-21
> * [330588502] High CVE-2024-2887: Type Confusion in WebAssembly. Reported by Manfred Paul, via Pwn2Own 2024 on 2024-03-21"""
id = "FBSD-2024-0258"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2883"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2885"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2886"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2887"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2024/03/stable-channel-update-for-desktop_26.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "123.0.6312.86" },
    { introduced = "0" },
]

[database_specific]
vid = "814af1be-ec63-11ee-8e76-a8a1599412c6"
discovery = "2024-03-26T00:00:00Z"
