schema_version = "1.7.0"
modified = "2024-01-29T00:00:00Z"
published = "2024-01-29T00:00:00Z"
summary = "qt5-webengine -- Multiple vulnerabilities"
details = """
Qt qtwebengine-chromium repo reports:

> Backports for 8 security bugs in Chromium:
>
> * [1505053] High CVE-2023-6345: Integer overflow in Skia
> * [1501326] High CVE-2023-6702: Type Confusion in V8
> * [1513170] High CVE-2023-7024: Heap buffer overflow in WebRTC
> * [1501798] High CVE-2024-0222: Use after free in ANGLE
> * [1505086] High CVE-2024-0224: Use after free in WebAudio
> * [1513379] High CVE-2024-0333: Insufficient data validation in Extensions
> * [1507412] High CVE-2024-0518: Type Confusion in V8
> * [1517354] High CVE-2024-0519: Out of bounds memory access in V8"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2023-6345" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2023-6702" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2023-7024" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-0222" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-0224" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-0333" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-0518" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-0519" },
    { type = "WEB", url = "https://code.qt.io/cgit/qt/qtwebengine-chromium.git/log/?h=87-based" },
]
affected = []
id = "FBSD-2024-0313"

[database_specific]
vid = "a11e7dd1-bed4-11ee-bdd6-4ccc6adda413"
discovery = "2024-01-08T00:00:00Z"
