schema_version = "1.7.0"
modified = "2024-10-05T00:00:00Z"
published = "2024-10-05T00:00:00Z"
summary = "zeek -- potential DoS vulnerability"
details = """
Tim Wojtulewicz of Corelight reports:

> Adding to the POP3 hardening in 7.0.2, the parser now
> simply discards too many pending commands, rather than
> any attempting to process them. Further, invalid server
> responses do not result in command completion anymore.
> Processing out-of-order commands or finishing commands
> based on invalid server responses could result in
> inconsistent analyzer state, potentially triggering null
> pointer references for crafted traffic."""
references = [
    { type = "WEB", url = "https://github.com/zeek/zeek/releases/tag/v7.0.3" },
]
affected = []
id = "FBSD-2024-0085"

[database_specific]
vid = "fe7031d3-3000-4b43-9fa6-52c2b624b8f9"
discovery = "2024-10-05T00:00:00Z"
