schema_version = "1.7.0"
modified = "2024-05-17T00:00:00Z"
published = "2024-05-17T00:00:00Z"
summary = "electron29 -- setuid() does not affect libuv's internal io_uring"
details = """
Electron developers report:

> This update fixes the following vulnerability:
>
> * Backported fix for CVE-2024-22017."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-22017" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-vr4q-vx84-9g5x" },
]
affected = []
id = "FBSD-2024-0209"

[database_specific]
vid = "a431676c-f86c-4371-b48a-b7d2b0bec3a3"
discovery = "2024-05-15T00:00:00Z"
