schema_version = "1.7.0"
modified = "2024-09-12T00:00:00Z"
published = "2024-09-12T00:00:00Z"
summary = "Gitlab -- vulnerabilities"
details = """
Gitlab reports:

> Execute environment stop actions as the owner of the stop action job
>
> Prevent code injection in Product Analytics funnels YAML
>
> SSRF via Dependency Proxy
>
> Denial of Service via sending a large glm\\_source parameter
>
> CI\\_JOB\\_TOKEN can be used to obtain GitLab session token
>
> Variables from settings are not overwritten by PEP if a template is included
>
> Guests can disclose the full source code of projects using custom group-level templates
>
> IdentitiesController allows linking of arbitrary unclaimed provider identities
>
> Open redirect in repo/tree/:id endpoint can lead to account takeover through broken OAuth flow
>
> Open redirect in release permanent links can lead to account takeover through broken OAuth flow
>
> Guest user with Admin group member permission can edit custom role to gain other permissions
>
> Exposure of protected and masked CI/CD variables by abusing on-demand DAST
>
> Credentials disclosed when repository mirroring fails
>
> Commit information visible through release atom endpoint for guest users
>
> Dependency Proxy Credentials are Logged in Plaintext in graphql Logs
>
> User Application can spoof the redirect url
>
> Group Developers can view group runners information"""
id = "FBSD-2024-0107"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-6678"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8640"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8635"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8124"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8641"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8311"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4660"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4283"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4612"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-8631"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-2743"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-5435"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-6389"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-4472"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-6446"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-6685"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2024/09/11/patch-release-gitlab-17-3-2-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.3.0" },
    { fixed = "17.3.2" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "17.2.0" },
    { fixed = "17.2.5" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "8.14.0" },
    { fixed = "17.1.7" },
]

[database_specific]
vid = "bcc8b21e-7122-11ef-bece-2cf05da270f3"
discovery = "2024-09-11T00:00:00Z"
