schema_version = "1.7.0"
modified = "2024-05-24T00:00:00Z"
published = "2024-05-24T00:00:00Z"
summary = "QtNetworkAuth -- predictable seeding of PRNG in QAbstractOAuth"
details = """
Andy Shaw reports:

> The OAuth1 implementation in QtNetworkAuth created nonces using
> a PRNG that was seeded with a predictable seed.
>
> This means that an attacker that can somehow control the time of
> the first OAuth1 flow of the process has a high chance of predicting
> the nonce used in said OAuth flow."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-36048" },
    { type = "WEB", url = "https://www.qt.io/blog/security-advisory-qstringconverter-0" },
    { type = "WEB", url = "https://codereview.qt-project.org/c/qt/qtnetworkauth/+/560317" },
]
id = "FBSD-2024-0201"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "qt6-networkauth"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "6.7.1" },
    { introduced = "0" },
]

[database_specific]
vid = "f5fa174d-19de-11ef-83d8-4ccc6adda413"
discovery = "2024-05-08T00:00:00Z"
