schema_version = "1.7.0"
modified = "2024-10-02T00:00:00Z"
published = "2024-10-02T00:00:00Z"
summary = "redis,valkey -- Multiple vulnerabilities"
details = """
Redis core team reports:

> CVE-2024-31449
> :   Lua library commands may lead to stack overflow and potential RCE.
>
> CVE-2024-31227
> :   Potential Denial-of-service due to malformed ACL selectors.
>
> CVE-2024-31228
> :   Potential Denial-of-service due to unbounded pattern matching."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-31449" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-31227" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-31228" },
    { type = "WEB", url = "https://github.com/redis/redis/releases/tag/7.4.1" },
]
id = "FBSD-2024-0088"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "redis72"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "7.2.0" },
    { fixed = "7.2.6" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "redis62"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "6.2.0" },
    { fixed = "6.2.16" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "valkey"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "8,0,0" },
    { fixed = "8.0.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "7.2.0" },
    { fixed = "7.2.7" },
]

[database_specific]
vid = "8b20f21a-8113-11ef-b988-08002784c58d"
discovery = "2024-10-02T00:00:00Z"
