schema_version = "1.7.0"
modified = "2024-02-14T00:00:00Z"
published = "2024-02-14T00:00:00Z"
summary = "chromium -- security fix"
details = """
Chrome Releases reports:

> This update includes 1 security fix."""
id = "FBSD-2024-0293"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2024/02/stable-channel-update-for-desktop_13.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "121.0.6167.184" },
    { introduced = "0" },
]

[database_specific]
vid = "4edbea45-cb0c-11ee-86bb-a8a1599412c6"
discovery = "2024-02-13T00:00:00Z"
