schema_version = "1.7.0"
modified = "2025-02-02T00:00:00Z"
published = "2025-02-02T00:00:00Z"
summary = "qt6-webengine -- Multiple vulnerabilities"
details = """
Qt qtwebengine-chromium repo reports:

> Backports for 9 security bugs in Chromium:
>
> * CVE-2024-12693: Out of bounds memory access in V8
> * CVE-2024-12694: Use after free in Compositing
> * CVE-2025-0436: Integer overflow in Skia
> * CVE-2025-0437: Out of bounds read in Metrics
> * CVE-2025-0438: Stack buffer overflow in Tracing
> * CVE-2025-0441: Inappropriate implementation in Fenced Frames
> * CVE-2025-0443: Insufficient data validation in Extensions
> * CVE-2025-0447: Inappropriate implementation in Navigation
> * CVE-2025-0611: Object corruption in V8"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-12693" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-12694" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0436" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0437" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0438" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0441" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0443" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0447" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0611" },
    { type = "WEB", url = "https://code.qt.io/cgit/qt/qtwebengine-chromium.git/log/?h=122-based" },
]
affected = []
id = "FBSD-2025-0238"

[database_specific]
vid = "72b8729e-e134-11ef-9e76-4ccc6adda413"
discovery = "2025-01-09T00:00:00Z"
