schema_version = "1.7.0"
modified = "2025-07-08T00:00:00Z"
published = "2025-07-08T00:00:00Z"
summary = "MongoDB -- may be susceptible to privilege escalation due to $mergeCursors stage"
details = """
cna@mongodb.com reports:

> An unauthorized user may leverage a specially crafted
> aggregation pipeline to access data without proper
> authorization due to improper handling of the $mergeCursors
> stage in MongoDB Server. This may lead to access to data
> without further authorisation."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-6713" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-6713" },
]
id = "FBSD-2025-0048"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "mongodb70"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "7.0.20" },
    { introduced = "0" },
]

[database_specific]
vid = "77dc1fc4-5bc5-11f0-834f-b42e991fc52e"
discovery = "2025-07-07T00:00:00Z"
