schema_version = "1.7.0"
modified = "2024-11-25T00:00:00Z"
published = "2024-11-25T00:00:00Z"
summary = "chromium -- multiple security fixes"
details = """
Chrome Releases reports:

> This update includes 3 security fixes:
>
> * [377384894] High CVE-2024-11395: Type Confusion in V8. Reported by Anonymous on 2024-11-05"""
id = "FBSD-2024-0031"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2024-11395"

[[references]]
type = "WEB"
url = "https://chromereleases.googleblog.com/2024/11/stable-channel-update-for-desktop_19.html"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "ungoogled-chromium"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "131.0.6778.85" },
    { introduced = "0" },
]

[database_specific]
vid = "9dfca0cd-ab09-11ef-8c1c-a8a1599412c6"
discovery = "2024-11-19T00:00:00Z"
