schema_version = "1.7.0"
modified = "2024-10-18T00:00:00Z"
published = "2024-10-18T00:00:00Z"
summary = "oauth2-proxy -- multiple vulnerabilities"
details = """
The oauth2-proxy project reports:

> Vulnerabilities have been addressed:
>
> * CVE-2024-24786
> * CVE-2024-24791
> * CVE-2024-24790
> * CVE-2024-24784
> * CVE-2024-28180
> * CVE-2023-45288"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-24786" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-24791" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-24790" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-24784" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-28180" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-45288" },
    { type = "WEB", url = "https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.7.0" },
]
affected = []
id = "FBSD-2024-0073"

[database_specific]
vid = "dbe8c5bd-8d3f-11ef-8d2e-a04a5edf46d9"
discovery = "2024-10-02T00:00:00Z"
