schema_version = "1.7.0"
modified = "2024-03-12T00:00:00Z"
published = "2024-03-12T00:00:00Z"
summary = "Intel CPUs -- multiple vulnerabilities"
details = """
Intel reports:

> 2024.1 IPU - Intel Processor Bus Lock Advisory
>
> A potential security vulnerability in the bus lock regulator
> mechanism for some Intel Processors may allow denial of service. Intel
> is releasing firmware updates to mitigate this potential
> vulnerability.

> 2024.1 IPU - Intel Processor Return Predictions Advisory
>
> A potential security vulnerability in some Intel Processors may
> allow information disclosure.

> 2024.1 IPU - Intel Atom Processor Advisory
>
> A potential security vulnerability in some Intel Atom Processors
> may allow information disclosure.

> 2024.1 IPU - Intel Xeon Processor Advisory
>
> A potential security vulnerability in some 3rd and 4th Generation
> Intel Xeon Processors when using Intel Software Guard Extensions (SGX)
> or Intel Trust Domain Extensions (TDX) may allow escalation of
> privilege.

> 2024.1 IPU OOB - Intel Xeon D Processor Advisory
>
> A potential security vulnerability in some Intel Xeon D Processors
> with Intel Software Guard Extensions (SGX) may allow information
> disclosure."""
affected = []
id = "FBSD-2024-0269"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-39368"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-38575"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-28746"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-22655"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-43490"

[[references]]
type = "WEB"
url = "https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20240312"

[database_specific]
vid = "b6dd9d93-e09b-11ee-92fc-1c697a616631"
discovery = "2023-03-12T00:00:00Z"
