schema_version = "1.7.0"
modified = "2024-08-19T00:00:00Z"
published = "2024-08-19T00:00:00Z"
summary = "mozilla products -- spoofing attack"
details = """
security@mozilla.org reports:

> Select options could obscure the fullscreen notification dialog.
> This could be used by a malicious site to perform a spoofing attack.
> This vulnerability affects Firefox < 129, Firefox ESR < 128.1,
> and Thunderbird < 128.1."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-7518" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-7518" },
]
affected = []
id = "FBSD-2024-0139"

[database_specific]
vid = "d0ac9a17-5e68-11ef-b8cc-b42e991fc52e"
discovery = "2024-08-06T00:00:00Z"
