schema_version = "1.7.0"
modified = "2025-01-13T00:00:00Z"
published = "2025-01-13T00:00:00Z"
summary = "keycloak -- Multiple security fixes"
details = """
Keycloak reports:

> This update includes 2 security fixes:
>
> * CVE-2024-11734: Unrestricted admin use of system and environment variables
> * CVE-2024-11736: Denial of Service in Keycloak Server via Security Headers"""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-11734" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-11736" },
]
affected = []
id = "FBSD-2025-0260"

[database_specific]
vid = "5e2bd238-d2bb-11ef-bc0e-1c697a616631"
discovery = "2025-01-13T00:00:00Z"
