schema_version = "1.7.0"
modified = "2024-04-11T00:00:00Z"
published = "2024-04-11T00:00:00Z"
summary = "jose -- DoS vulnerability"
details = """
cve@mitre.org reports:

> latchset jose through version 11 allows attackers to cause
> a denial of service (CPU consumption) via a large p2c (aka
> PBES2 Count) value."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2023-50967" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2023-50967" },
]
affected = []
id = "FBSD-2024-0247"

[database_specific]
vid = "02be46c1-f7cc-11ee-aa6b-b42e991fc52e"
discovery = "2024-03-20T00:00:00Z"
