schema_version = "1.7.0"
modified = "2024-03-29T00:00:00Z"
published = "2024-03-29T00:00:00Z"
summary = "electron{27,28} -- Object lifecycle issue in V8"
details = """
Electron developers report:

> This update fixes the following vulnerability:
>
> * Security: backported fix for CVE-2024-2625."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-2625" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-j7h3-fcrw-g6j8" },
]
id = "FBSD-2024-0256"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "electron28"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "28.2.9" },
    { introduced = "0" },
]

[database_specific]
vid = "bdcd041e-5811-4da3-9243-573a9890fdb1"
discovery = "2024-03-28T00:00:00Z"
