schema_version = "1.7.0"
modified = "2025-01-12T00:00:00Z"
published = "2025-01-12T00:00:00Z"
summary = "asterisk - path traversal"
details = """
cve@mitre.org reports:

> An issue in the action\\_listcategories() function of Sangoma Asterisk
> v22/22.0.0/22.0.0-rc1/22.0.0-rc2/22.0.0-pre1 allows attackers to
> execute a path traversal."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2024-53566" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2024-53566" },
]
id = "FBSD-2025-0261"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "asterisk20"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "20.11.0" },
    { introduced = "0" },
]

[database_specific]
vid = "7624c151-d116-11ef-b232-b42e991fc52e"
discovery = "2024-12-02T00:00:00Z"
