schema_version = "1.7.0"
modified = "2025-07-24T00:00:00Z"
published = "2025-07-24T00:00:00Z"
summary = "Mozilla -- XSLT document CSP bypass"
details = """
security@mozilla.org reports:

> XSLT document loading did not correctly propagate the
> source document which bypassed its CSP."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-8032" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-8032" },
]
id = "FBSD-2025-0025"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "140.1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "firefox-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.13" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "141.0" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird-esr"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "140.1" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "thunderbird"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "128.13" },
    { introduced = "0" },
]

[database_specific]
vid = "4a357f4b-685e-11f0-a12d-b42e991fc52e"
discovery = "2025-07-22T00:00:00Z"
