schema_version = "1.7.0"
modified = "2025-07-24T00:00:00Z"
published = "2025-07-24T00:00:00Z"
summary = "Gitlab -- vulnerabilities"
details = """
Gitlab reports:

> Cross-site scripting issue impacts Kubernetes Proxy in GitLab CE/EE
>
> Cross-site scripting issue impacts Kubernetes Proxy in GitLab CE/EE using CDNs
>
> Exposure of Sensitive Information to an Unauthorized Actor issue impacts GitLab CE/EE
>
> Improper Access Control issue impacts GitLab EE
>
> Exposure of Sensitive Information to an Unauthorized Actor issue impacts GitLab CE/EE
>
> Improper Access Control issue impacts GitLab CE/EE"""
id = "FBSD-2025-0033"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-4700"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-4439"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-7001"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-4976"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-0765"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2025-1299"

[[references]]
type = "WEB"
url = "https://about.gitlab.com/releases/2025/07/23/patch-release-gitlab-18-2-1-released/"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "gitlab-ee"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "18.2.0" },
    { fixed = "18.2.1" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "18.1.0" },
    { fixed = "18.1.3" },
]

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { introduced = "15.0.0" },
    { fixed = "18.0.5" },
]

[database_specific]
vid = "5683b3a7-683d-11f0-966e-2cf05da270f3"
discovery = "2025-07-23T00:00:00Z"
