schema_version = "1.7.0"
modified = "2025-03-07T00:00:00Z"
published = "2025-03-07T00:00:00Z"
summary = "electron32 -- multiple vulnerabilities"
details = """
Electron developers report:

> This update fixes the following vulnerabilities:
>
> * Security: backported fix for CVE-2025-0445.
> * Security: backported fix for CVE-2025-0998."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0445" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-q4fq-38gr-ccp3" },
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-0998" },
    { type = "ADVISORY", url = "https://github.com/advisories/GHSA-4v9x-qxmv-4h58" },
]
affected = []
id = "FBSD-2025-0204"

[database_specific]
vid = "6e27040b-61b7-4989-9471-dfb10c3cd76e"
discovery = "2025-03-03T00:00:00Z"
