schema_version = "1.7.0"
modified = "2024-09-30T00:00:00Z"
published = "2024-09-30T00:00:00Z"
summary = "Slixmpp -- Lack of SSL Certificate hostname validation in XMLStream"
details = """
NIST reports:

> Slixmpp before 1.8.3 lacks SSL Certificate hostname validation in XMLStream,
> allowing an attacker to pose as any server in the eyes of Slixmpp."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2022-45197" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2022-45197" },
]
id = "FBSD-2024-0090"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py39-slixmpp"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.8.3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py310-slixmpp"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.8.3" },
    { introduced = "0" },
]

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "py311-slixmpp"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "1.8.3" },
    { introduced = "0" },
]

[database_specific]
vid = "f9cfdb00-7f43-11ef-9b27-592d55dd336d"
discovery = "2022-12-25T00:00:00Z"
