schema_version = "1.7.0"
modified = "2024-01-07T00:00:00Z"
published = "2024-01-07T00:00:00Z"
summary = "QtNetwork -- potential buffer overflow"
details = """
Andy Shaw reports:

> A potential integer overflow has been discovered in Qt's HTTP2
> implementation. If the HTTP2 implementation receives more than 4GiB
> in total headers, or more than 2GiB for any given header pair, then
> the internal buffers may overflow."""
id = "FBSD-2024-0327"

[[references]]
type = "ADVISORY"
url = "https://api.osv.dev/v1/vulns/CVE-2023-51714"

[[references]]
type = "WEB"
url = "https://www.qt.io/blog/security-advisory-potential-integer-overflow-in-qts-http2-implementation"

[[affected]]

[affected.package]
ecosystem = "FreeBSD:ports"
name = "qt6-base"

[[affected.ranges]]
type = "ECOSYSTEM"
events = [
    { fixed = "6.6.1_2" },
    { introduced = "0" },
]

[database_specific]
vid = "e2f981f1-ad9e-11ee-8b55-4ccc6adda413"
discovery = "2023-12-14T00:00:00Z"
