schema_version = "1.7.0"
modified = "2024-10-31T00:00:00Z"
published = "2024-10-31T00:00:00Z"
summary = "keycloak -- Missing server identity checks when sending mails via SMTPS"
details = """
Red Hat reports:

> A vulnerability was found in Apache Sling Commons Messaging
> Mail(angus-mail), which provides a simple interface for sending
> emails via SMTPS in OSGi, does not offer an option to enable
> server identity checks, leaving connections vulnerable to
> \"man-in-the-middle\" attacks and can allow insecure email
> communication."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2021-44549" },
    { type = "WEB", url = "https://www.cve.org/CVERecord?id=CVE-2021-44549" },
]
affected = []
id = "FBSD-2024-0063"

[database_specific]
vid = "fd538d14-5778-4764-b321-2ddd61a8a58f"
discovery = "2024-10-01T00:00:00Z"
